- build/build.xml
There were duplicate environmental variables relating to github. This consolidates them.
> Update remove duplicate envars

- build/whitelists/metadata.txt
This fixes the issue where calls to the ant target "uninstallUnpackagedPost" will fail if unpackaged/post contains PersonAccount.object (error: "The CustomObject called 'PersonAccount' is standard and cannot be deleted")
> Add PersonAccount to whitelist

- cli/metadata/package.py
- cli/metadata/tests/package_metadata/namespaced_report_folder/destructiveChanges.xml
- cli/metadata/tests/package_metadata/namespaced_report_folder/package.xml
- cli/metadata/tests/package_metadata/namespaced_report_folder/reports/namespace__TestFolder/TestReport.report
- cli/metadata/tests/test_package.py
- Create tests structure for PackageXmlGenerator
- use urllib.quote to escape the package name to handle &'s in the
package name
- Don't include namespaced report/dashboard folders in package.xml
> package.xml generation fixes

- build/cumulusci.xml
Support the injection of the namespace in the filename during pre and post deploy. I have tested this in an unpackaged org. I am not sure how to test this in a packaged org. @jlantz, I will chat with you about it tomorrow.
> Support namespace injection in filenames.

- build/cumulusci.xml
Pass the cumulusci configured api version to all sf:retrieve calls, instead of using the default from the force.com migration tool jar.
> Add apiVersion to sf:retrieve calls

- cli/release_notes/provider.py
- cli/release_notes/tests/test_provider.py
- cli/release_notes/tests/util_github_api.py
> use tag commit date instead of tag date when finding PRs between tags

- cumulusci/tasks/salesforce.py
> use temp files for test results

- cumulusci/core/flows.py
- cumulusci/core/tests/test_flows.py
make flows.py pass pylint and pep8, functional tests for flow to support implementing #233 - formal task return values.
> Flows.py tests and linting

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce.py
This just adds RetrieveUnpackaged to cumulusci.yml. this is very useful for the interactive consultant.
> add a retrieve unpackaged task for pulling metadata given a package.xml

- cumulusci/tasks/salesforce.py
* Skips RecordType metadata when constructing a package.xml for deletion (i.e. destructiveChanges.xml)
> Fixes #267, skip RecordType when generating package.xml for deletion

- cumulusci/tasks/push/tasks.py
If no start time is given to the SchedulePushOrgList-based tasks, the push upgrade will not be automatically monitored.
> Pushes will now only be monitored if no start time is given.

- cumulusci/tasks/push/push_api.py
- cumulusci/tasks/push/tasks.py
* Push org lists (text files with one org ID per line) can now have comments and blank lines. The first word on the line is assumed to be the org ID and anything after that is ignored.
Fixes #294 
Fixes #306 
Fixes #308
> Push enhancements

- cumulusci/cli/cli.py
add `--debug-before` and `--debug-after` options to task execution via the cli, which drops the user into pdb, the Python debugger, to debug your task.
> add task before/after debug

- cumulusci/tasks/util.py
Support glob expressions in the Delete task, e.g. reducing the need to chdir and more easily clean up build artifacts. 
```
new_delete:
description: Delete, but with glob
class_path: cumulusci.tasks.util.Delete
options:
path:
- package_customizations/**/classes
```
> add glob support

- cumulusci/cumulusci.yml
adds task:
```
cci task info unschedule_apex
cci task run unschedule_apex
Description: Unschedule all scheduled apex jobs (CronTriggers).
Class:: cumulusci.tasks.anonymous_apex.AnonymousApexTask
Options:
• apex (required): The apex to run. Default: for (CronTrigger t : [SELECT Id FROM CronTrigger]) { System.abortJob(t.Id); }
```
#354 - task: delete scheduled jobs
> add an unschedule_apex task

- cumulusci/core/config.py
when reading a scratch org config from SFDX, if the password is not set or expired, cci will now generate a new password before continuing.
#351: generate password for scratch org info
> generate scratch org passwords when expired

- cumulusci/tasks/anonymous_apex.py
- cumulusci/tasks/bulkdata.py
- cumulusci/tasks/salesforce.py
- cumulusci/tasks/tests/test_salesforce.py
- docs/cookbook.rst
Removes `cumulusci.tasks.salesforce.BaseSalesforceToolingApiTask` and `cumulusci.tasks.salesforce.BaseSalesforceBulkApiTask` and consolidates their functionality into `cumulusci.tasks.salesforce.BaseSalesforceApiTask`, a single class that has access to the Enterprise, Tooling, and Bulk APIs.
Customer changes: Custom tasks that subclass either `BaseSalesforceToolingApiTask` or `BaseSalesforceBulkApiTask` must now subclass `BaseSalesforceApiTask`. No other change to the task is required.
fixes #347 - allow bulk, tooling, and enterprise api access from the same base task class
> converging enterprise/bulk/tooling into one task class

- cumulusci/cumulusci.yml
- cumulusci/tasks/batch_apex.py
- requirements.txt
- setup.py
Adds a new task class `cumulusci.tasks.batch_apex.BatchApexWait` that blocks until a batch job completes.
Usage: 
`cci task run batch_apex_wait -o class_name BDI_DataImport_Batch`.
```
2017-07-07 13:14:01: Running task: batch_apex_wait
2017-07-07 13:14:02: Options:
2017-07-07 13:14:02:   class_name: BDI_DataImport_BATCH
2017-07-07 13:14:02: Beginning task: BatchApexWait
2017-07-07 13:14:02:
2017-07-07 13:14:08: BDI_DataImport_BATCH: 1 of 20 (0 failures)
2017-07-07 13:14:10: BDI_DataImport_BATCH: 1 of 20 (0 failures)
2017-07-07 13:14:12: Increased polling interval to 3 seconds
[...]
2017-07-07 13:15:54: Increased polling interval to 9 seconds
2017-07-07 13:15:54: BDI_DataImport_BATCH: 20 of 20 (0 failures)
2017-07-07 13:15:54: Job is complete.
2017-07-07 13:15:54: BDI_DataImport_BATCH took …
```
> add initial batch_apex_wait task

- cumulusci/cumulusci.yml
- cumulusci/tasks/release_notes/generator.py
- cumulusci/tasks/release_notes/parser.py
- cumulusci/tasks/release_notes/task.py
- cumulusci/tasks/release_notes/tests/test_generator.py
- cumulusci/tasks/release_notes/tests/test_parser.py
- cumulusci/tasks/release_notes/tests/test_provider.py
Need to support per-project parser customizations for release notes. YAML to the rescue!
Once this is merged and deployed to mrbelvedereci, SAL has an associated change to take advantage (https://github.com/SalesforceFoundation/sal/commit/a61684fc871954dab029debe1907c2903a303293). Otherwise all other repos should work without any modifications.
Tested in multiple repos with lots of option toggling.
> Specify release notes parser config in yml

- cumulusci/cli/cli.py
We hide the input when entering the client secret in `cci org config_connected_app`. Apparently this breaks things on Windows and the value stored in client secret is just `u'\x16'`. Confirmed that settings hide_input=False gets around the problem. I'd like to gather more evidence and file an issue in [click](https://github.com/pallets/click) but in the meantime this should unblock those working in Windows.
@cdcarter asking for your review just to get your opinion if showing the input is a big deal. I think it's okay since it's just local to the shell session.
> Don't hide input when entering client secret on windows machines

- cumulusci/tasks/apex/testrunner.py
Pin testrunner with API v38.0 to get at the ApexTestResultLimit object and fields on ApexTestResult.
> retrieve test results with api38

- cumulusci/cumulusci.yml
- cumulusci/tasks/github.py
- cumulusci/tasks/github_commit.py
- cumulusci/tasks/release_notes/generator.py
- cumulusci/tasks/release_notes/task.py
- cumulusci/tasks/release_notes/tests/test_generator.py
- cumulusci/tasks/release_notes/tests/test_parser.py
Everywhere we have a "dry run" option the default should be False. This makes it more in line with how dry run works in popular tools e.g. `git remote prune origin --dry-run`.
> Make dry run defaults False

- cumulusci/cumulusci.yml
- cumulusci/tasks/release_notes/generator.py
- cumulusci/tasks/release_notes/parser.py
- cumulusci/tasks/release_notes/task.py
- cumulusci/tasks/release_notes/tests/test_parser.py
Used this task today with dry_run option and it felt wrong. I think it makes more sense to have a "publish" option default=False. It used to be like this so this would just go back to how it was.
> Change github_release_notes task option dry_run (back) to publish

- cumulusci/core/config.py
- cumulusci/core/tests/test_config.py
allow a user of YamlProjectConfig to pass in additional yaml.
right now, additional project_config yaml can only be added to the project_config with an actual file in the filesystem.
this the MBCI YamlProjectConfig implementation to load yaml from the database with highest precedence.
> allow yaml to be passed to YamlProjectConfig in python

- cumulusci/core/tests/test_flows.py
One thing I'm not happy about is that `test_task_raises_exception_fail` for some reason prints the traceback from the raised exception it's testing.  I'm not sure if that's worth trying to figure out now or if we just chalk it up to a cost of higher coverage for now.
> 100% test coverage for core/flow.py

- heroku_ci.sh
Changed from using `git checkout` to `git reset` to reset the branch to the build commit.  This keeps the branch reference in the local git repo so coveralls can get the right branch in the report.
> Fix coveralls.io reporting from Heroku CI to properly report branch of build

- cumulusci/cli/cli.py
- cumulusci/core/config.py
Closes #441 by allowing projects to specify that certain scratch org configurations defined in cumulusci.yml should have the namespace applied.  The default still remains that all orgs are created without a namespace even if the sfdx-project.json has a namespace configured.  This is because in a full feature + beta test environment, you need orgs without the namespace applied to install a managed version.
Since most projects using CumulusCI were previously set up to not hard code namespaces in order to enable unmanaged feature builds, we keep this as the default behavior.  Individual projects could easily flip the default `dev` and `feature` orgs to use the namespace while other orgs remain non-namespaced with the following in their cumulusci.yml file:
```
orgs:
scratch:
dev:
namespaced: …
```
> Allow for namespaced and non-namespaced scratch orgs in the same project

- cumulusci/cli/cli.py
- cumulusci/core/config.py
Fixes #451 by adding support for auto detecting CI system build environments via environment variables.  If a known CI environment is detected, its repository information will be injected into the project config instead of relying on parsing the files in the .git directory.
An initial implementation is included for Heroku CI which should allow Heroku CI to run cci builds easily.
> Auto Detection of CI environments

- cumulusci/cli/cli.py
Fixes #456 by throwing a nice one line error on BrowserTestFailure instead of a traceback.
> Issue #456, handle BrowserTestFailure in the CLI

- cumulusci/core/config.py
- heroku_ci.sh
We were capturing that tests failed but the bash script was always returning a 0 exit status so it looked like a passed build even with failing tests.  This is now properly handled.
> heroku_ci.sh test script should throw proper exit status on failed test

- cumulusci/cli/cli.py
- cumulusci/core/config.py
- cumulusci/core/keychain.py
- cumulusci/core/tests/test_keychain.py
- heroku_ci.sh
Fixes #474 
Fixes #475 
Fixes #313 
This branch implements a few enhancements to the workflow of using the `cci org` grouping of commands.  More detail is available in the linked issues above but a quick summary:
* `cci org remove` now exists to remove an org from the keychain
* CumulusCI now sets an alias in sfdx for all created scratch orgs using the naming format `ProjectName__orgname`
* Named scratch org configs are now automatically created in the keychain.  If an org with the same name already exists, the existing org is not changed.  CumulusCI includes 4 by default and projects can define their own.
> cci org * enhancements

- HISTORY.rst
- cumulusci/__init__.py
- cumulusci/cli/cli.py
- cumulusci/cumulusci.yml
- setup.cfg
- setup.py
* There was an issue introduced in beta65 with the filename token `___NAMESPACE___` used for injecting the namespace prefix into deploys.  The issue was caused by the change from `DeployNamespacedBundles` to `DeployBundles` which now requires the `namespace_inject` option to be set for namespace injection to be enabled.  This release fixes the issue by setting the `namespace_inject` option to `$project_config.project__package__namespace` which will look up the project's namespace and inject it as the option value.
* As part of debugging this issue, I realized that the exceptions we were handling in `cci` to throw nicer exceptions were being excluded from handling via the `--debug` flag.  This branch abstracts out the `--debug` flag logic so it can be applied to all exceptions for easier …
> Configure for beta66 bug fix release

- HISTORY.rst
- cumulusci/__init__.py
- cumulusci/cumulusci.yml
- setup.cfg
- setup.py
deploy_post_managed was causing an error in the ci_beta flow because it wasn't running token replacement.  The cause was that namespace_inject wasn't set.  This branch simply sets a defualt value of the project's namespace in the core cumulusci.yml file.
> Configure default namespace_inject on deploy_post_managed

- cumulusci/core/config.py
For the purposes of https://github.com/SalesforceFoundation/mrbelvedereci/issues/104
Looking for the error message when scratch org fails to create, I didn't want to just copy the string, so I have it here as a constant that is imported into the mrbelvedereci code.
> scratch org creation error as constant for usage by metaci

- cumulusci/cli/cli.py
- cumulusci/cumulusci.yml
I had previously left `cci project init` alone in favor of using a cookiecutter template to launch the project config.  The problem is that we don't have as much control over the process with cookiecutter, cookiecutter is another dependency, and cookiecutter can't run against an existing directory.
The two most common use cases we really want to handle are:
1. You're starting a new project
2. You have a Github repo with metadata under `src/` and you want to enable that repo for CumulusCI
Cookiecutter won't help in use case #2.  This new task will run against any local git repository that doesn't already have a `cumulusci.yml` file and configures the following:
* `cumulusci.yml`
* `sfdx-project.json` if none exists already, otherwise leaves existing file alone
* `orgs/*.json` Starter files …
> Enhancements to cci project init

- cumulusci/utils.py
refactor of utils.py previously switched to using BytesIO instead of StringIO for zip files, since they are indeed binary files. missed one instance.
utils imports `io` with the `future` standard librry overrides, which meant that StringIO is more stringently checking its types, causing this method to throw a TypeError
> update utils.py to use bytesio

- cumulusci/salesforce_api/metadata.py
cci was crashing when decoding \u2019 from the SF API response (seems there by mistake). Using unicode literals from future fixes the crash.
> use unicode literals in metadata API file

- cumulusci/tasks/salesforce.py
- cumulusci/utils.py
- docs/tasks.rst
Two new tokens are now supported in namespace injection:
* %%%NAMESPACE_OR_C%%%: Replaced with either 'namespace' or 'c'
* %%%NAMESPACED_ORG_OR_C%%%: Replaced with either 'namespace' if the `namespaced` argument is set or with 'c' if not
> Add support for new tokens to handle namespaced lightning components

- cumulusci/cli/cli.py
- cumulusci/core/config.py
- cumulusci/core/flows.py
- cumulusci/core/keychain.py
- cumulusci/core/tests/test_flows.py
- cumulusci/core/tests/test_keychain.py
- cumulusci/core/tests/test_tasks.py
- cumulusci/tasks/apex/tests/test_salesforce.py
- cumulusci/tasks/salesforce.py
- cumulusci/tasks/tests/test_salesforce.py
- cumulusci/tasks/tests/test_sfdx.py
- cumulusci/tests/util.py
This branch changes flows and tasks so they will always write a modified org config back to the keychain.  This helps avoid the scenario where `cci flow run` or `cci task run` creates a scratch org, fails, then fails to write the scratch org info into cci keychain which effectively creates an orphaned scratch org.
> Avoid orphan scratch orgs from flow and task run

- cumulusci/cli/cli.py
- cumulusci/core/config.py
- cumulusci/core/keychain.py
- cumulusci/cumulusci.yml
- docs/features.rst
- docs/index.rst
- Scratch org configs in cumulusci.yml can now specify a days attribute that sets the number of days the scratch org should persist (1-30)
- `cci org scratch` now supports the `--days N` option to override the days value on the scratch config
- Scratch orgs now have `date_created` stored in their config
- Scratch orgs now have new calculated properties: `expired`, `expires`, `days_alive`
- `cci org list` now shows days and if orgs are expired
- All cci commands that interact with an org from the keychain now check if the org is expired.  If the org is expired, the user is prompted to recreate the org config to continue
>  Add support for setting durationdays on scratch orgs and tracking org expiration

- HISTORY.rst
- cumulusci/__init__.py
- cumulusci/cli/cli.py
- cumulusci/tasks/github/release.py
- setup.cfg
- setup.py
Fixes #520 and also fixes a newly introduced bug in `cci task run` when trying to run a task that doesn't require a Salesforce org and none is specified via `--org <name>`
> Beta79: Bug fix release for #520

- cumulusci/core/config.py
- cumulusci/core/exceptions.py
- Removes the previous implementation of the `version` option on github
dependencies
- If a tag is specified, it will be used for all retrieves of content
from the repo (cumulusci.yml, unpackaged/*, and src)
- The tag is not recursive to dependencies specified by the referenced
project.  If the referenced project has a github dependency without a
tag, the latest version of that dependency will be installed
> Allow github dependencies to specify a tag

- cumulusci/tasks/salesforce.py
- cumulusci/utils.py
Since CumulusCI already handles dependencies, deploying meta.xml files containing the `<packageVersions>` element and its children (namespace, majorVersion, and minorVersion) can cause errors if the versions don't match up.  That previously required a commit to update all the meta.xml files to a new underlying package version.
This change automatically strips the `<packageVersion>` element and its children from all meta.xml files by default on all Deploy based tasks.  The target Salesforce org will automatically add those elements back using whatever version of the referenced package is installed in the org.  This way, CumulusCI gets to fully manage the dependencies.
Since the meta.xml files are updated by the org automatically, this should have no impact on packaging orgs or managed …
> Clean meta.xml of namespace version references on deploy

- cumulusci/tasks/bulkdata.py
- docs/bulk_data.rst
closes #525 - if a mapping defines a record_type, when retrieving that sobject, filter by that record type.
additionally fixes a bug where a second mapping on the same sqlite table would not properly add newly mapped fields to the table in retrieve mode.
adds an `api` flag on the mapping, currently doesn't do anything, i can roll that back if you want a clean merge, but eventually it will support loading objects that bulk doesn't.
> filter sobjects by record type in bulkdataretrieve

- cumulusci/tasks/salesforce.py
as of Spring 18 we are seeing a delay in the `MetadataPackageVersion` record being available after the `PackageUploadRequest` reports success. This PR adds a 5 sec sleep, under the assumption that this is now an asynch process on the platform side. Working to confirm that with someone on DX.
closes #548
> add a sleep between queries

- cumulusci/tasks/salesforce.py
- docs/tutorial.rst
the UploadPackage task now uses the Tooling API for all calls, instead of using the Data API to query MetadataPackage. This means UploadPackage no longer requires the Push API permissions.
> use tooling API for packageuploadrequest

- cumulusci/tasks/metadata/metadata_map.yml
`cci task run update_package_xml` now parses Metadata Type GlobalValueSetTranslations correctly
> Added support for GlobalValueSetTranslation Metadata Type

- cumulusci/core/config.py
This fixes an issue where beta tags were not properly identified and could result in getting the wrong version from get_latest_version. Seen in HEDA where get_latest_version was returning 1.0 from tag beta/1.0.
> fix issue in config get_latest_version

- cumulusci/tasks/salesforce.py
Fixes #530 
The zip file is opened in write mode, then later read for processing. Closing the zip file after writing, then reopening in read mode before processing fixes the issue.
> close zip and reopen in read mode before processing

- cumulusci/tasks/command.py
Users could pass `False` to the `pass_env` option in a `Command` task. It would have the desired result of assigning the `False` boolean value to `self.options['pass_env']`. The default value is `True` and if not provided, the `True` boolean value is assigned as expected.
The unexpected case is that when you explicitly provide `True` to the option, the `True` boolean value was not assigned.
This rectifies that issue.
> Allow user to pass True into pass_env in the Command task

- cumulusci/tasks/command.py
- docs/tasks.rst
Needed a way to be able to call out to an interactive shell script during a custom flow. Adding an option to the `Command` class seemed like the cleanest way to accomplish this.
> Add the ability to have interactive commands via the Command task.

- cumulusci/tasks/command.py
Fixes #379 
As far as I know there's no reason we need to specify /bin/bash in the Popen command. Removing this allows Windows to use the command task.
> Make Command tasks work on Windows

- HISTORY.rst
- cumulusci/__init__.py
- cumulusci/tasks/release_notes/provider.py
- setup.cfg
- setup.py
Fixes #608 
Working on a better solution that uses github3.py instead of directly calling the API in the release notes task, but wanted to fix this in the meantime since it is causing issues in our release notes. 100 is the max results per page.
> get 100 PRs per page instead of 30

- cumulusci/core/flows.py
- cumulusci/core/tests/test_flows.py
Allow flows to call other flows. Example usage in `cumulusci.yml`:
```
flows:
example_flow:
tasks:
1:
task: example_task
2:
flow: another_flow
```
- A given flow may only occur once in the tree, to prevent infinite recursion
- Nested flows inherit the project config, org config, flow options, and skipped tasks from parent flows
- Return values from nested flows can be referenced just like tasks: flow1.flow2.task.key
> support nesting flows

- cumulusci/cumulusci.yml
adds a flow to just run unschedule_jobs and deploy, for when you've pulled down some updates on a shared branch and know you don't need to update deps or any of that other stuff...
> add dev_deploy flow

- cumulusci/cli/cci.py
I've run into this a few times now where I run a flow thinking I have set a default org, but I haven't. The stack trace that's output is relatively unhelpful, so let's replace it with something more user friendly.
> Better error message for running a flow without a default org.

- cumulusci/cli/cci.py
- cumulusci/core/exceptions.py
- cumulusci/core/flows.py
- cumulusci/cumulusci.yml
- cumulusci/oauth/salesforce.py
- cumulusci/tasks/command.py
- cumulusci/tasks/release_notes/tests/test_generator.py
- cumulusci/tasks/salesforce/RetrieveReportsAndDashboards.py
- cumulusci/tasks/tests/test_sfdx.py
- cumulusci/tasks/util.py
- setup.py
Like I mentioned, over the weekend I worked on this megabranch. I can split it up into smaller PRs but it's just a few small things. Make sure to review with ?w=1.
- Replace all print statements w/ print() calls and change one encoding method.
- Various fixes that Py3 work revealed: fix some imports for util tasks, weirdness w/ setup script.
- Adds three new utility task classes: PassOptionAsResult, PassOptionAsReturnValue, LogLine
- Flow executions (inner or outer) now know their flow name, and inner flows now know their step number.
- Adds pre-/post- hooks for flow & subflow executions.
- Add a `prep` argument to skip _init_flow when instantiating a flow class. The flow cannot execute til it is `prepped`.
- Sub-flow executions will use the same flow runner class as their parent flow if …
> Py3 Compats & Some Miscellaney

- cumulusci/cli/cci.py
- cumulusci/core/config/BaseProjectConfig.py
- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/utils.py
If a project has a github dependency to a repo without a namespace
configured or if the dependency has the unmanaged option set, pass the
Github authentication from the github service in a header to allow
depending on an unmanaged private repository.
Fixes #643
> Support Dependency on a Private Github repo in unmanaged mode

- README.rst
- cumulusci/cli/cci.py
The canonical domain for PyPI changed to pypi.org a few months ago. This should avoid getting redirected.
> Update PyPI URL

- cumulusci/robotframework/Salesforce.py
- cumulusci/robotframework/Salesforce.robot
This adds a script which is run in the browser after each click to wait for any pending Aura XMLHTTPRequests to complete, to increase the chances of being ready for the next command.
I also removed some sleeps which seem to be no longer necessary. 
Other minor fixes:
- Return the result of a `_call_selenium` retry
- Increased selenium timeout to 30s
- Set Chrome's `--disable-background-timer-throttling` flag to avoid slowing things down when it's running in the background.
> Wait for Aura XHRs after clicks

- docs/tutorial.rst
Attempting to activate a virtualenv using `source` will result in
`CommandNotFoundException`.
> Use correct command to activate virtualenv on Win10

- cumulusci/robotframework/Salesforce.py
It's not triggered automatically since there's no click.
> Robot: Wait for ajax after typing into a lookup field

- cumulusci/tests/test_utils.py
- cumulusci/utils.py
This also fixes several bugs found while writing the tests:
* %%%NAMESPACED_ORG_OR_C%%% was not replaced by zip_inject_namespace
* zip_strip_namespace and zip_tokenize_namespace would omit binary files rather than keeping them with no changes
* zip_strip_namespace would remove the necessary colon when replacing a lightning component xml namespace with c
* package_xml_from_dict would generate invalid xml if package_name was specified
> Coverage for cumulusci/utils.py

- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/tests/test_config.py
- cumulusci/salesforce_api/metadata.py
- cumulusci/tests/util.py
Previously, the refresh_oauth_token method did not require a keychain param for DummyOrgConfig and ScratchOrgConfig, but it did for OrgConfig. As a result, I think this token refresh in metadata.py would fail with a persistent org. This standardizes the interface to always pass a keychain.
> Be consistent about passing a keychain to refresh_oauth_token

- cumulusci/cli/cci.py
- cumulusci/cli/config.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/config/OrgConfig.py
- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/tasks.py
This one's a bit of a doozy. Some changes that warrant special attention:
- Moved global functions taking an initial 'config' param from cci.py to become methods of the CliConfig class
- Removed the unused 'e' arg for handle_exception_debug
- Made render_recursive handle lists better.
- Stop passing the return from render_recursive to click.echo, because it takes care of echoing itself.
- Make check_latest_version handle its own exceptions
- Removed unused --extend option for `project init`
- Removed unimplemented project_list and project_cd commands
- Don't echo scratch org expiration when using `org info` with the --json flag
- Delegate check for whether an org can be deleted to a `can_delete` method on the org config
- Remove unused --delete option for `org scratch`
- Fix exception …
> Coverage for cumulus.cli.cci

- cumulusci/tests/test_utils.py
- cumulusci/utils.py
From:
```python
File "/Users/jestevez/.pyenv/versions/2.7.15/envs/cci/lib/python2.7/site-packages/cumulusci/core/flows.py", line 231, in _run_step
self._run_task(stepnum, step_config)
File "/Users/jestevez/.pyenv/versions/2.7.15/envs/cci/lib/python2.7/site-packages/cumulusci/core/flows.py", line 307, in _run_task
raise e
xml.etree.ElementTree.ParseError: mismatched tag: line 3, column 6
```
To:
```python
File "/Users/jestevez/projects/rel/CumulusCI/cumulusci/core/flows.py", line 231, in _run_step
self._run_task(stepnum, step_config)
File "/Users/jestevez/projects/rel/CumulusCI/cumulusci/core/flows.py", line 307, in _run_task
raise e
xml.etree.ElementTree.ParseError: mismatched tag: line 3, column 6 (Account.object)
```
> Add error handling for removeXmlElement

- cumulusci/cli/cci.py
- cumulusci/core/flows.py
Instead of allowing a FlowConfig to define a flowrunner class_path, the flowrunner class is determined by the execution environment. Subflows inherit the flowrunner from their parent. 
There's presumably some work we can do in cumulusci.cli for a cli specific flowrunner, but now all CLI flow invocations will use BaseFlow. MetaCI will continue to use its custom MetaCIFlow and now child flows will too.
> Don't support dynamic flowrunner

- cumulusci/tasks/salesforce/BaseSalesforceApiTask.py
- cumulusci/tasks/salesforce/BaseSalesforceTask.py
- cumulusci/tasks/tests/test_bulkdata.py
- cumulusci/tasks/tests/test_salesforce.py
For all SimpleSalesforce instances we summon up, set the Sforce-Call-Options header to include a client id when registered or the CumulusCI clientName.
> set client id in call options

- .circleci/config.yml
- cumulusci/core/config/BaseProjectConfig.py
- cumulusci/core/tests/test_config.py
This sets up a Circle CI workflow that is similar to the existing Heroku CI script, but with several jobs running in parallel: unit tests, robot tests, and CumulusCI-Test release tests.
It also lays the groundwork for running separate python2 and python3 builds -- that just needs to get uncommented in the feature/python3 branch once this is merged.
Once this is merged to master we can follow up with decommissioning the heroku CI setup and removing heroku_ci.sh
> Add CircleCI config

- cumulusci/cumulusci.yml
- cumulusci/tasks/command.py
The sfdx force:source:convert command reorders xml elements inside .object files (and probably others) which causes unnecessary diffs.  Since the src directory in a CumulusCI project should for now be in the format retrieved via mdapi, this branch adds retrieve_unpackaged and update_package_xml to the end of the flow to properly format the files under src.
> Reduce diff from retrieve_scratch by adding retrieve_unpackaged/update_package_xml

- HISTORY.rst
- cumulusci/__init__.py
- cumulusci/tasks/salesforce/UpdateAdminProfile.py
- setup.cfg
- setup.py
Contains fix for a bug with deploying record types via dependencies.  Switches update_admin_profile to use etree instead of string replace to better target the elements to be modified
> Release 2.0.11

- cumulusci/core/flows.py
- cumulusci/core/keychain/EncryptedFileProjectKeychain.py
- cumulusci/core/keychain/EnvironmentProjectKeychain.py
- cumulusci/core/tasks.py
- cumulusci/core/tests/test_flows.py
- cumulusci/core/tests/test_keychain.py
- cumulusci/core/tests/test_tasks.py
(except for the retry and polling parts of tasks.py)
Changes made in passing:
- Removed some unused code in BaseFlow
- Fixed EncryptedFileProjectKeychain._load_files when the key doesn't exist yet
- Fixed EncryptedFileProjectKeychain.remove_org to remove the org in the instance's config, not just on disk.
> Coverage for the rest of cumulusci.core

- cumulusci/tasks/salesforce/UpdateAdminProfile.py
- cumulusci/tasks/salesforce/tests/test_UpdateAdminProfile.py
to avoid "Error: More than 1 default record type specified for: [sObject]"
I also ran black and added tests for UpdateAdminProfile
> Set all record type defaults to false before updating

- cumulusci/robotframework/locators.py
This covers modals opened by a Quick Action which don't set a title on the button
element
> Change to XPath using button label text for Click Modal Button

- cumulusci/core/config/BaseProjectConfig.py
- cumulusci/core/tests/test_config.py
- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
Adds a flow, `ci_beta_dependencies` to install the latest beta of project dependencies and run tests. Includes task error when running against non-scratch orgs.
> Add Beta Dependency Flow

- cumulusci/tests/test_utils.py
- cumulusci/utils.py
* Decode as UTF-8 instead of ASCII to handle files with non-ASCII characters
* Be more consistent about how we're structuring the UnicodeDecodeError handlers
* Explicitly re-encode before writing to the zipfile to avoid implicit ascii encoding in Python 2
* Fixed the utils for processing namespaces in package zip files to handle non-ASCII characters
> Clean up the zip-processing utils

- cumulusci/tasks/push/pushfails.py
- cumulusci/tasks/tests/test_pushfails.py
* Improvements to push failure report:
* Include subscriber org info
* Sort by stacktrace id and error title
* Don't write file if no results
* Fix gack regexp to match more gack ids
* Add option to ignore specified error types/titles
* Fix writing output with non-ASCII characters
> Improvements to push failure report

- cumulusci/cumulusci.yml
* In the push failure report, ignore "Package Uninstalled" and "Salesforce Subscription Expired" errors by default.
> Ignore push errors that aren't problematic by default

- cumulusci/cli/cci.py
- cumulusci/core/exceptions.py
- cumulusci/core/tests/test_exceptions.py
* Improved error messages for errors while executing anonymous Apex
> Print a more useful error than 'ApexException' for anon apex task

- cumulusci/cli/cci.py
- cumulusci/cli/config.py
- cumulusci/cli/tests/test_cci.py
* Fixed ``cci project init`` command. In addition, other command no longer require an existing project or keychain unless necessary to run the command. For example, it's now possible to run ``cci version`` from anywhere.
#816
> Pass config to click commands using custom decorator

- cumulusci/tasks/salesforce/UninstallPackagedIncremental.py
- cumulusci/tasks/salesforce/tests/test_UninstallPackagedIncremental.py
I intend to use this to avoid trying to delete quick actions that get implicitly added to the package in DE orgs but can't be deleted because they are referenced from layouts.
* ``uninstall_packaged_incremental`` task: Added "ignore" option to specify components to skip trying to delete even if they are present in the org but not in the local source.
> Add an 'ignore' option for UninstallPackagedIncremental

- cumulusci/robotframework/Salesforce.py
- cumulusci/robotframework/locators.py
- requirements.txt
- setup.py
No tests because standard layouts don't use tabular related lists :(
* New/revised keywords for related lists in robot Salesforce library:
- ``Load Related List``: Scrolls to a related list and waits for it to load
- ``Click Related List Button``: Automatically calls ``Load Related List`` first
- ``Click Related Item Link``: Clicks the main link for an item in a related list
- ``Click Related Item Popup Link``: Clicks a link in the popup menu for an item in a related list
- Updated to robotframework-seleniumlibrary 3.2.0 which includes a ``Scroll Element Into View`` keyword
> New/revised keywords for related lists in robot Salesforce library

- cumulusci/tests/test_utils.py
- cumulusci/utils.py
* Fix issue deploying `-meta.xml` files with non-ASCII characters in Python 2.
> Fix bug in handling non-ascii characters in remove_xml_element utils

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/config/BaseTaskFlowConfig.py
- cumulusci/cumulusci.yml
Let the bikeshedding over group assignments begin!
* Group the results of `cci task list`. Set the `group` key of a task in cumulusci.yml to assign it to a group.
* #772: Task Groupings
> Display task list in groups

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- docs/tutorial.rst
Add the `org import` command. When given a sfdx username (or an alias) and an org name `import` will import a scratch org into the cumulusci keychain.
- #877 
- #674
> Add scratch org import

- .flake8
- .pre-commit-config.yaml
- CONTRIBUTING.rst
- requirements_dev.txt
Install `pre-commit`:
```shell
pip install pre-commit
```
Install the hooks:
```shell
pre-commit install --install-hooks
```
Added `pre-commit==1.12.0` to `requirements_dev.txt`. Created a yaml file (`.pre-commit-config.yaml`):
```yaml
repos:
-   repo: https://github.com/ambv/black
rev: stable
hooks:
- id: black
-   repo: https://github.com/pre-commit/pre-commit-hooks
rev: v2.0.0
hooks:
- id: check-merge-conflict
- id: flake8
```
Includes three hooks:
1. `black` 
2. `flake8`
3. `check-merge-conflict` : Refuse to commit files containing conflict markers
The only hook we've discussed is `black`... the other two can be removed if necessary.
> Add pre-commit hooks

- cumulusci/robotframework/Salesforce.py
* Robot Framework: Fix "Load Related List" keyword to time out if the list isn't found instead of waiting forever.
> Avoid infinite scrolling if the related list isn't found

- cumulusci/__init__.py
- cumulusci/robotframework/Salesforce.py
- setup.cfg
- setup.py
We can't jump all the way to the bottom because then the list ends up underneath the header and can't be clicked. So scroll a bit at a time instead.
> Fix scrolling to related lists

- cumulusci/cumulusci.yml
- cumulusci/salesforce_api/package_zip.py
- cumulusci/tasks/salesforce/InstallPackageVersion.py
- cumulusci/tasks/salesforce/tests/test_InstallPackageVersion.py
* The `install_managed` and `install_managed_beta` tasks now take optional `activateRSS` and `password` options. `activateRSS` is set to true by default so that any active Remote Site Settings in the package will remain active when installed.
> Add InstallPackageVersion options for activateRSS and password

- cumulusci/cli/cci.py
- cumulusci/cli/logger.py
- cumulusci/cli/tests/test_logger.py
* When running a task with the `--debug` flag, HTTP requests are logged.
> Turn on requests logging when using debug flag

- cumulusci/tasks/apex/tests/test_apex_tasks.py
- cumulusci/tasks/salesforce/BaseSalesforceApiTask.py
- cumulusci/tasks/salesforce/tests/test_base_tasks.py
- cumulusci/tasks/tests/test_bulkdata.py
- cumulusci/tasks/tests/test_salesforce.py
* Fixed a bug where using the Salesforce REST API did not work if the `instance_url` was configured with a trailing slash.
> Strip trailing slash from instance URL

- cumulusci/robotframework/Salesforce.py
- cumulusci/robotframework/Salesforce.robot
* Robot Framework: Retry when there is a connection reset while opening the browser (probably due to delays in custom domain propagation). Due to a selenium bug, this was already retried in Python 2 but not in Python 3.
> Retry Create Webdriver on connection reset

- cumulusci/robotframework/CumulusCI.py
- cumulusci/robotframework/Salesforce.py
- cumulusci/robotframework/Salesforce.robot
I think this'll work out as a cleaner way to avoid the ConnectionResetErrors we've been seeing. In Python 2 selenium would do this after catching the ConnectionResetError, but in Python 3 the exception is not caught because it is no longer a subclass of socket.error. My theory is that the ConnectionResetError is a consequence of the DNS delays so this may help. But it's possible we'll still need to explicitly catch ProtocolError (which urllib3 wraps around the ConnectionResetError).
* Robot Framework: Make sure org domain can be resolved before trying to connect.
> Make sure Login Url can be resolved before continuing

- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
Add a test demonstrating that it's possible to use UpdateDependencies to install a single metadata bundle.
> Clean up UpdateDependencies tests

- cumulusci/tasks/salesforce/UninstallPackagedIncremental.py
* The uninstall_packaged_incremental task will now delete S-Controls that are no longer in the repository.
> S-Controls are deletable now

- cumulusci/core/config/BaseProjectConfig.py
- cumulusci/core/tests/test_config.py
- cumulusci/core/utils.py
- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/salesforce/DeployBundles.py
- cumulusci/utils.py
- This gives the metadeploy publishing task the ability to release a tag even if it's not what's currently checked out. The task fetches the archive for the specified tag into a temporary directory, constructs a project_config for it, and uses that to freeze the installation steps.
- Make get_static_dependencies return a specific commit ref for metadata bundles -- for the tag if specified, otherwise for the most recent release if there is one, otherwise for the head of master.
> Handle publishing a different tag than what is currently checked out

- cumulusci/cli/cci.py
- cumulusci/cli/config.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/keychain/EncryptedFileProjectKeychain.py
- cumulusci/core/runtime.py
- cumulusci/core/tests/test_keychain.py
* The `cci service` commands are now available even if not in a local git repository configured for CumulusCI.  The `--project` flag is not available on `cci service connect` when outside a project.
* `cumulusci.core.runtime.BaseCumulusCI` now supports the `allow_global_keychain` kwarg which will fall back to initializing the keychain with the global config run from outside a project git repository.
Fixes #963
> Allow cci service commands to be run from outside a project repository

- cumulusci/core/config/BaseProjectConfig.py
- cumulusci/core/tasks.py
- cumulusci/core/tests/test_config.py
- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/DeployBundles.py
- cumulusci/tasks/salesforce/InstallPackageVersion.py
- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/tasks/salesforce/tests/test_DeployBundles.py
- cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
- cumulusci/tasks/tests/test_metadeploy.py
This adjusts how the names for metadeploy steps are determined so that we can show the actual package name and version.
> Label metadeploy steps with package name & version

- cumulusci/tasks/release_notes/parser.py
None
Added two characters.
https://bugs.python.org/issue27364
You can see that they went through a similar process for the stdlib here:
https://bugs.python.org/file43550/invalid_stdlib_escapes_1.patch
> Clear up a couple of warnings by making regepx into raw-strings.

- .flake8
- cumulusci/cli/cci.py
- cumulusci/cli/config.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/cli/tests/test_config.py
- cumulusci/core/keychain/BaseEncryptedProjectKeychain.py
- cumulusci/robotframework/CumulusCI.py
- cumulusci/utils.py
- docs/tutorial.rst
- requirements.txt
This updates where the CLI looks for the keychain key. Rather than requiring the user to configure the CUMULUSCI_KEY environment variable, we now generate a key and store it in the system keychain using the `keyring` library. The environment variable is still given priority for backwards compatibility, and if there's no key in the keyring yet it will be migrated from the environment variable.
Apologies for also mixing some cleanup into the same pull request (updating CliConfig references to CliRuntime and misc flake8 fixes). The primary changes are in cumulusci/cli/config.py
> Generate encryption key and store using keyring

- cumulusci/cli/cci.py
w+ erases the file first. r+ doesn't.
So before, it would erase the file before trying to read the value. The value was therefore always replaced with "0". Now it will read the result or write the result based on the caller's preference.
We don't cache this underlying file object so its safe that we read it and then write to it a few milliseconds later. It's a different file object.
> Fix update checking timestamp reading.

- cumulusci/core/config/ScratchOrgConfig.py
* Deletes the "date created" field when deleting a scratch org. This makes the "days" column in `cci org list` display properly after deletion. Thanks to @21aslade for the fix.
> Clear date_created when deleting a scratch org

- .pre-commit-config.yaml
This will avoid a `CalledProcessError` on pre-commit's first run when a virtualenv has been created without the `-p python3.6` option.
> Use python3 as default language version

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
> For cci org info --json, serialize unknown types by stringifying them

- cumulusci/cumulusci.yml
We already have a check to make sure that the `include_beta` option for update_dependencies can't be used with a persistent org. But that means that if a project has turned include_beta on for the update_dependencies task in general, it can't be deployed to its packaging org. This makes sure that include_beta is turned off when using update_dependencies in the ci_master flow.
> Make sure we don't try to install beta dependencies into the packaging org

- cumulusci/core/flowrunner.py
- cumulusci/core/tasks.py
- cumulusci/cumulusci.yml
- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/salesforce/DeployBundles.py
- cumulusci/tasks/salesforce/InstallPackageVersion.py
- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/tasks/tests/test_metadeploy.py
This makes some significant changes to the metadeploy publish task:
* Plan options are now read from a new `plans` section of cumulusci.yml instead of from task options. (See https://github.com/SalesforceFoundation/Cumulus/pull/4111 for an example of how the plan configuration will look for NPSP.) This means that a single run of the task can now handle publishing multiple plans, and we can configure a generic `metadeploy_publish` task instead of needing to set up different tasks for each project.
* Plan steps are now defined inline in the plan configuration rather than by naming a flow. This makes it easier to configure a plan that is like an existing flow with one or two adjustments.
* There is now a way to customize MetaDeploy step settings such as `name` and `is_required` on a …
> Publish to MetaDeploy using plan configuration

- cumulusci/cumulusci.yml
* Rename it to install_regression since it's really focused on that use case
* Install beta versions of dependencies
* Install beta version of the main package
* Run config_managed after upgrading so it works if the metadata refers to new components from the package
> Various updates to the install_upgrade flow

- cumulusci/tasks/bulkdata.py
- cumulusci/tasks/tests/test_bulkdata.py
-  `cumulusci/tasks/bulkdata.py`
-  `EpochType.process_result_value` supports a `None` value
- Updated test `TestEpochType.test_process_result_value` in `.../tests/test_bulkdata.py'
> bulkdata task supports NULL DATETIME

- cumulusci/cumulusci.yml
This fixes an error I was getting with the install_prod_no_config flow when running deploy_post after installing the managed package
> Inject namespace when deploying post for install_prod_no_config flow

- cumulusci/cli/config.py
- cumulusci/core/keychain/BaseProjectKeychain.py
* A project's predefined scratch org configs now default to `set_password: True`
(which was already the case for orgs created explicitly using `cci org scratch`)
* A scratch org config's set_password flag is now retained when recreating an expired org.
Fixes #670
> Fix a couple bugs related to generating passwords for new scratch orgs

- cumulusci/tasks/salesforce/Deploy.py
- cumulusci/tasks/tests/test_metadeploy.py
Tasks based on `Deploy` should show up in MetaDeploy as "metadata" rather than "other"
> Default the step 'kind' to 'metadata' for Deploy tasks

- cumulusci/cli/cci.py
- cumulusci/files/templates/project/scratch_def.json
- orgs/beta.json
- orgs/dev.json
- orgs/feature.json
- orgs/release.json
- Reformat scratch org definition files to use [`orgPreferenceSettings` instead of `orgPreferences`](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs_def_file_config_values.htm), which is now deprecated.
- Parameterize generation of scratch org definition files based on managed or unmanaged environments.
> Update scratch org definition files to use orgPreferenceSettings

- cumulusci/core/config/BaseProjectConfig.py
- cumulusci/core/tests/test_config.py
- When multiple namespaces (tag prefixes) coexist in a repository, `repo.latest_release()` may return the incorrect tag. This PR adds a check for the correct tag prefix, and iterates over all releases when there is a mismatch.
> Filter tags by prefix

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/tests/test_config.py
- cumulusci/core/tests/test_config_expensive.py
- cumulusci/salesforce_api/metadata.py
- cumulusci/salesforce_api/tests/test_metadata.py
The purgeOnDelete flag for MD-API deployments is only valid in Developer Edition orgs and sandboxes. This automatically sets it to false for orgs that don't meet those criteria.
This involves adding a REST API call to query the Organization object after refreshing the oauth token so that the OrgConfig can provide awareness of the org's edition.
> Force purgeOnDelete to false for production orgs

- .circleci/config.yml
- CONTRIBUTING.rst
- tox.ini
pip 19.1 breaks when doing an editable (`-e`) install of a package that has a pyproject.toml without a build_system specified. Unfortunately we have such a file because it's where `black` looks for configuration.
See https://github.com/pypa/pip/pull/6370 and https://github.com/pypa/pip/issues/6433 for more discussion.
> Workaround for pip's change in behavior

- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/tests/test_config_expensive.py
- cumulusci/tests/test_utils.py
- cumulusci/utils.py
- Allow configuration of the email address assigned to scratch org users, with the order of priority being (1) any `adminEmail` key in the scratch org definition; (2) the `email_address` property on the scratch org configuration in `cumulusci.yml`; (3) the `user.email` configuration property in Git.
> Allow configuration of scratch org user email address

- cumulusci/tasks/release_notes/parser.py
- cumulusci/tasks/release_notes/tests/test_parser.py
- CCI's release notes parser now recognizes issues closed if they are linked in Markdown format.
> Make release notes parser recognize linked issues

- cumulusci/tasks/salesforce/UpdateAdminProfile.py
* The `update_admin_profile` task now uses Python string formatting on the package.xml file used for retrieve.  This allows injection of namespace prefixes using `{managed}` and `{namespaced_org}`.
> String format package_xml to allow for handling of namespace prefixes

- cumulusci/tasks/salesforce/EnsureRecordTypes.py
- cumulusci/tasks/salesforce/__init__.py
- cumulusci/tasks/salesforce/tests/test_EnsureRecordTypes.py
- Add a task, Ensure Record Types, to generate a Record Type and optional Business Process for a specific sObject and deploy the metadata.
> Add Ensure Record Types task

- .circleci/config.yml
- CONTRIBUTING.rst
- tox.ini
pip 19.1.1 fixed editable installs when the project has a pyproject.toml that doesn't specify a build system, so we shouldn't need this workaround any longer -- but let's see what CI says.
> Remove pip workaround

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/tests/test_config.py
* If Salesforce returns an error response while refreshing an OAuth token, we'll now show the response instead of just the HTTP status code.
> Improve ability to debug oauth token refresh errors

- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/keychain/BaseProjectKeychain.py
- cumulusci/core/sfdx.py
- cumulusci/core/tests/test_keychain.py
- cumulusci/utils.py
This makes it so that setting a default org in CCI also updates the default org in sfdx.
Ancillary changes: pep8 fixes, factored out a util for calling sfdx
* Setting a default org in CCI (using `cci org default` or the `--default` flag when creating a scratch org) will now also update the sfdx `defaultusername`.
Fixes #868
> Make CCI manage the sfdx default org

- cumulusci/cli/cci.py
- cumulusci/cli/config.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/flowrunner.py
- cumulusci/core/github.py
- cumulusci/core/tests/test_github.py
- cumulusci/core/utils.py
- cumulusci/cumulusci.yml
- cumulusci/robotframework/CumulusCI.py
- cumulusci/tasks/release_notes/generator.py
- cumulusci/utils.py
This involves adding a general mechanism for a service to configure a validator. If configured, the `cci service connect` command will call the validator passing the service attributes that were input, and abort if the validator raises an exception.
I also renamed cumulusci.core.utils.import_class to import_global since it can import anything from a module's globals. import_class remains as an alias for backwards-compatibility.
Fixes #909
> Validate GitHub service attributes before saving

- cumulusci/salesforce_api/metadata.py
(This is possible according to the WSDL and has been seen in the wild.)
> Avoid error if the MD-API returns componentFailures with no problem node

- cumulusci/cumulusci.yml
* Refactored the `install_regression` flow to better parallel other flows. The `install_regression` flow now installs the package without configuring it. Use the new `regression_org` flow to both install and configure.
> refactor install_regression flow

- .circleci/config.yml
- added || true to every robot step, so all robot tests run even if some fail.
- screenshots are copied to the output directory
> Make circleci run all tests and preserve output even if some fail

- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
Added two options to the UpdateDependencies task:
- `allow_newer`: If the org already has a newer release, use it. Defaults to True.
- `allow_uninstalls`: Allow uninstalling a beta release or newer final release if needed in order to install the requested version. Defaults to False.
These defaults are a change from prior behavior since uninstalling packages is not commonly needed when working with scratch orgs, and it is potentially destructive.
> Add options to control UpdateDependencies downgrades

- cumulusci/core/flowrunner.py
- cumulusci/core/tasks.py
- cumulusci/core/tests/test_flowrunner.py
- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/salesforce/BaseSalesforceMetadataApiTask.py
- cumulusci/tasks/salesforce/DeployBundles.py
- cumulusci/tasks/salesforce/InstallPackageVersion.py
- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/tasks/salesforce/tests/test_DeployBundles.py
- cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
- cumulusci/tasks/tests/test_metadeploy.py
Preflight checks can be defined in the `checks` list at either the flow or step level. The PreflightFlowCoordinator contains the logic to evaluate them and produce `preflight_results`, which MetaDeploy will make use of.
Each check consists of:
- `when`: a jinja2 expression. Evaluated in a context that has access to `project_config`, `org_config`, and `tasks` which is a way of accessing tasks in a way that will cache their results so that multiple checks using the same task will only run the task once (for example if there are multiple checks making use of a task that gets the current installed package versions)
- `action`: a string that will be set as the `status` in the preflight result if the `when` condition evaluates to true
- `message`: a string that will be set as the `message` in …
> Add PreflightFlowCoordinator to evaluate preflight checks

- cumulusci/cli/logger.py
Before:
After:
- Log colors now display correctly on Windows.
Fixes #813
> Fix color escapes on Windows

- MANIFEST.in
- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/cumulusci.yml
- cumulusci/files/templates/project/.gitignore
- cumulusci/files/templates/project/README.md
- cumulusci/files/templates/project/cumulusci.yml
- cumulusci/files/templates/project/mapping.yml
- cumulusci/tasks/bulkdata.py
- cumulusci/tasks/tests/test_bulkdata.py
- docs/bulk_data.rst
- docs/tasks.rst
* Updates to the project template created by `cci project init`:
* Added .gitignore
* Added README.md
* Added a template for GitHub pull requests
* Added an option to store metadata in DX source format
* Added tasks for retrieving and deploying unpackaged metadata for QA
* Added a sample mapping.yml for the bulkdata tasks
* Pin the minimum CumulusCI version
* Added validation of the project name
* The bulkdata tasks are now available by default as `extract_data` and `load_data`. Renamed QueryData to ExtractData to better fit with the concept of extract-transform-load.
> Updates to "cci project init" template

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/config/BaseTaskFlowConfig.py
- cumulusci/core/tests/test_config.py
Before:
```console
$ cci flow info derpendencies
Traceback (most recent call last):
[...]
File "/Users/jestevez/.pyenv/versions/3.7.1/envs/cci-prod/lib/python3.7/site-packages/cumulusci/core/config/BaseTaskFlowConfig.py", line 47, in get_flow
raise FlowNotFoundError("Flow not found: {}".format(name))
cumulusci.core.exceptions.FlowNotFoundError: Flow not found: derpendencies
```
After:
```console
$ cci flow info derpendencies
Checking the version!
Usage: cci flow info [OPTIONS] FLOW_NAME
Error: Flow not found: derpendencies. Did you mean "dependencies"?
```
- `cci` no longer prints tracebacks when a flow or task is not found. Additionally, it will suggest a name if a close enough match can be found.
#960
> Use Click's UsageError when flow/task is not found

- HISTORY.rst
- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/sfdx.py
- cumulusci/utils.py
TextIOWrapper's default encoding is locale.getpreferredencoding(False) which makes sense for file I/O but not for console I/O. This switches to specify the same encoding that Python determined for the parent process's stdout.
> Fix decoding subprocess output if console encoding is different from preferred file encoding

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- Fixed a bug in reporting scratch org creation errors encountered while running a flow.
> Don't swallow exception messages in flow_run

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/salesforce_api/tests/test_utils.py
- cumulusci/salesforce_api/utils.py
- cumulusci/tasks/salesforce/BaseSalesforceApiTask.py
- Add the `cci org shell` command, which opens a Python shell pre-populated with a `simple_salesforce` session on the selected org (as `sf`).
> Add cci org shell command

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/tests/test_config.py
When CumulusCI connects to an org, it fetches the Organization sObject and stores some information from it in the org config that gets saved to the keychain. This makes a change to also cache the returned data on the org config instance (i.e. more temporarily than the keychain) so that it can be accessed by tasks. The immediate need is access to SignupCountryIsoCode to enforce a regional restriction on where an installer can be used.
With this in place we should be able to configure a preflight check like this:
```
{
"when": "org_config.organization_sobject['SignupCountryIsoCode'] != 'US'",
"action": "error",
"message": "Sorry, this product is not available in your region."
}
```
> Provide access to the Organization sobject data on OrgConfig

- cumulusci/cumulusci.yml
- The install_regression flow now upgrades to the latest beta from the most recent final release instead of from the previous final release.
> Start regression upgrade from latest final release instead of the previous one

- cumulusci/core/config/BaseProjectConfig.py
- cumulusci/core/github.py
- cumulusci/core/tests/test_github.py
- cumulusci/tasks/github/base.py
- cumulusci/tasks/github/tests/test_commit.py
- cumulusci/tasks/github/tests/test_pull_request.py
- cumulusci/tasks/github/tests/util_github_api.py
- cumulusci/tasks/release_notes/tests/test_generator.py
- cumulusci/tasks/release_notes/tests/test_provider.py
- cumulusci/tasks/salesforce/UpdateDependencies.py
This adds a new function `get_github_api_for_repo` for getting an authenticated github API client, and updates to use it throughout the codebase. The new function will authenticate as an app instead of the user configured in the CumulusCI keychain if the GITHUB_APP_ID and GITHUB_APP_KEY environment variables are set. The reason for the new function is that authenticating as an app requires specifying the id of that app's installation for a particular user/org, so we need to know which repository the caller is intending to interact with.
- CumulusCI can now authenticate for GitHub API calls as either a user or an app. The latter is for use when CumulusCI is used as part of a hosted service.
> Refactor to support interacting with github as a github app

- cumulusci/tasks/bulkdata.py
- cumulusci/tasks/tests/test_bulkdata.py
- The `LoadData` task will throw a `BulkDataException` if any records fail during the load operation.
> Bulk Data: fail loudly on load errors

- cumulusci/core/github.py
The default gave us an occasional error
"AuthenticationFailed: 401 'Expiration time' claim ('exp') is too far in the future"
possibly due to rounding errors.
> Set a shorter expiration for the JWT used for getting an app installation token

- cumulusci/core/flowrunner.py
- cumulusci/core/tests/test_flowrunner.py
Show the new tree summary of flow steps at the beginning of running a flow. This avoids showing the step_num which is meant to be an internal representation.
> Log the new step summary before running a flow

- cumulusci/cumulusci.yml
- cumulusci/tasks/release_notes/generator.py
- cumulusci/tasks/release_notes/parser.py
- cumulusci/tasks/release_notes/task.py
- cumulusci/tasks/release_notes/tests/test_generator.py
- cumulusci/tasks/release_notes/tests/test_parser.py
* The `github_release_notes` task now has an `include_empty` option to for the ability to include links to PRs that have no release notes.
> Include option for including links to PRs with no release notes

- requirements.txt
- utility/build-homebrew.sh
- Use an older version of simple-salesforce because the newest one doesn't have an sdist published on PyPI
- Change the install stanza that we generate for the homebrew formula to use pip as is currently recommended in docs, but with a workaround to avoid breaking on the `entrypoints` package
I've tested installation of the formula locally.
> Fixes for homebrew formula

- cumulusci/__init__.py
- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- docs/index.rst
- docs/install.rst
- docs/tutorial.rst
I also moved the install docs to their own page so it's easier to link to them without including the whole tutorial.
* Add additional info to the `cci version` command, including the Python version, an upgrade check, and a warning on Python 2.
> Expand `cci version` info

- utility/build-homebrew.sh
* Fix accidentaly interpolation of commands via backticks
* Don't generate a resource stanza for cumulusci, because it's installed as the main package and having the resource stanza prevents its binary from getting linked
> Fixes for build-homebrew script

- cumulusci/core/flowrunner.py
Freezing a flow to publish to MetaDeploy can generate sub-steps where one step from the original flow is split into multiple steps.
For example update_dependencies gets split into one sub-step for each package.
The sub-steps get an extra number like ".1" added to the end of the step path, which breaks the flow summary code.
This is a quick fix to just skip trying to display the sub-steps.
> Fix a bug in printing the flow summary when there are sub-steps.

- cumulusci/cumulusci.yml
- cumulusci/tasks/apex/testrunner.py
- cumulusci/tasks/apex/tests/test_apex_tasks.py
To test this PR against an org, make sure it is generated _without_ the org setting `DisableParallelApexTesting`.
- The `run_tests` task now supports a `retry_errors` parameter. When all unit test failures' message or stack trace match one of the regular expressions specified there, the failing tests will be retried serially. By default, this will happen only when all unit test failures are due to row locking errors.
- Existing retry options have been removed from `run_tests`; these options controlled retrying result queries.
> Automatically retry UNABLE_TO_LOCK_ROW Apex test failures

- .circleci/config.yml
- cumulusci/cli/cci.py
- cumulusci/core/config/OrgConfig.py
- cumulusci/core/keychain/BaseProjectKeychain.py
- cumulusci/core/keychain/__init__.py
- cumulusci/core/tests/test_config.py
- cumulusci/oauth/salesforce.py
- cumulusci/tasks/connectedapp.py
- cumulusci/tasks/tests/test_connectedapp.py
- requirements.txt
* There is now a default CumulusCI global connected app that can be used to connect to persistent orgs (assuming you know the credentials) without creating a new connected app. It's still possible to configure a custom connected app using `cci service connect connected_app` if more control over the connected app settings is needed.
* When CumulusCI is being run in a non-interactive context it can now obtain an access token for a persistent org using a JWT instead of a refresh token. This approach is used if the SFDX_CLIENT_ID and SFDX_HUB_KEY environment variables are set. This makes it easier to manage persistent org connections in the context of a hosted service because it's possible to replace the connected app's certificate without needing to obtain new refresh tokens for each org.
> Updates to persistent org connections

- cumulusci/core/flowrunner.py
- cumulusci/core/tests/test_flowrunner.py
@davidmreed This should fix the problem we saw with cached preflight task results. Do you see any easy way to improve the test so that we're actually testing for that?
> Fix returning cached preflight task results

- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/generate.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/mapping_after.yml
- cumulusci/tasks/bulkdata/tests/test_bulkdata.py
- `LoadData` now supports the key `action: update` to perform a Bulk API update job
- `LoadData` now supports an `after: <step name>` on a lookup entry to defer updating that lookup until a dependent sObject step is completed.
- `GenerateMapping` now handles self-lookups and reference cycles by generating `after:` markers wherever needed. 
- A small issue in `QueryData` affecting mappings using `oid_as_pk: False` has been fixed.
> Bulk Data: sObject Updates

- cumulusci/cli/cci.py
- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/tests/test_config_expensive.py
Clean up scratch org aliveness testing, per your suggestion.
None of these functions are used as often as I would have guessed so it wasn't a big deal yet. Cleaning up the API now will avoid that as the code base grows.
> Add method for cleanly asking if an org is alive

- cumulusci/tasks/salesforce/CreateCommunity.py
- cumulusci/tasks/salesforce/tests/test_CreateCommunity.py
- docs/tasks.rst
Create Community task now allows a blank url path prefix.
[1208](https://github.com/SFDO-Tooling/CumulusCI/issues/1208)
> Add No Url Path Prefix Option to Create Community Task

- cumulusci/tasks/metadata/metadata_map.yml
This PR adds two metadata types to metadata_map.yml. This is to fix an issue where `retrieve_changes` will throw an exception after updating a profile.
- We've added support for the `ProfilePasswordPolicy` and `ProfileSessionSetting` metadata types.
> Metadata mapping updates

- cumulusci/robotframework/tests/salesforce/perf/collection_perf.robot
Performance tests now use the Prospecting StageName so that they work with or without NPSP installed.
> Switch to Prospecting as StageName

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/tests/test_config.py
- cumulusci/oauth/salesforce.py
While working on MetaShare I discovered that for scratch orgs it's more reliable to use a specific instance URL for the auth endpoint instead of test.salesforce.com
* Added a workaround for an issue where refreshing the access token for a sandbox or scratch org could fail if the user's credentials were new and not fully propagated.
> Make jwt_session use a specific instance URL for sandboxes

- cumulusci/cumulusci.yml
* Parent change notes are now aggregated in the `ci_feature_beta_deps` flow.
> add parent pr notes task to flow

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/org_settings.py
- cumulusci/tasks/salesforce/tests/test_org_settings.py
- docs/tasks.rst
Moving this here from MetaShare. Useful when creating scratch orgs directly using ScratchOrgInfo instead of using sfdx.
* Added an `org_settings` task which can deploy scratch org settings from a scratch org definition file.
> Add task for deploying org settings from a scratch org definition file

- cumulusci/tasks/metadata/metadata_map.yml
This is largely based on the response from https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_describe.htm
...we're tantalizingly close to just being able to generate our configuration from that, but it does have some discrepancies with the docs, and I suspect we might want to add additional fields to metadata_map.yml such as which types are supported in which types of packages
so we can validate for that.
- Added support for new metadata types when generating package.xml from a directory of metadata using the `update_package_xml` task.
fixes #1261, #898, #312
> Add missing metadata types to metadata_map.yml

- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/tests/test_metadeploy.py
A couple additions to metadeploy_publish to facilitate testing:
- Make it possible to specify a commit hash with `-o commit [sha]`, instead of a tag.
- Require passing `-o publish True` in order to automatically set the Version to is_listed=True (this is backwards incompatible in order to provide a safer default)
> Add ability to publish any commit hash to MetaDeploy, not just a tag

- cumulusci/tasks/metadata/ee_src.py
- cumulusci/tasks/metadata/tests/test_ee_src.py
- The `CreateUnmanagedEESrc` task has been revised to remove the Protected setting on Custom Objects, to ensure that source is deployable to an Enterprise Edition.
> Make CreateUnmanagedEESrc remove Protected settings on Custom Objects

- cumulusci/tasks/command.py
- docs/tasks.rst
Updated current documentation for the Command task to include a couple examples: (1) Running an arbitrary shell command, and (2) simple custom command task.
> Update command task with examples.

- cumulusci/tests/test_utils.py
- cumulusci/utils.py
* `cci task doc` now only adds task_docs when present in `class.__dict__`
> `task_doc` shouldn't be inherited from parent classes

- cumulusci/__init__.py
- cumulusci/salesforce_api/metadata.py
- setup.cfg
- setup.py
* Disabled use of PyOpenSSL by the Python requests library, since it is no longer needed in the versions of Python we support.
* Fixed an issue where posts to the Metadata API could reuse an existing connection and get a connection reset error if Salesforce had closed the connection.
> Don't use persistent connections for MDAPI posts

- .circleci/config.yml
- README.rst
- setup.py
- tox.ini
* tox.ini updated to include 3.8.0
* We now have three separate jobs for python tests that will run in circleci for py versionse: 3.6, 3.7, and 3.8.
> Python 3.8 Updates

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/org_settings.py
- cumulusci/tasks/salesforce/tests/test_org_settings.py
- cumulusci/tasks/salesforce/tests/test_sourcetracking.py
Instead of a hardcoded version. The settings are part of a scratch org definition file stored in the project repository, so may use different versions depending on when they were written.
> Deploy org settings using the project API version

- cumulusci/core/config/project_config.py
- cumulusci/core/github.py
- cumulusci/core/source/github.py
- cumulusci/core/tests/test_config.py
- cumulusci/core/tests/test_source.py
- When including steps from an external GitHub source, it's now possible to specify `release: latest`, `release: latest_beta`, or `release: prevous` instead of a commit, branch, or tag.
> Add support for specifying latest/latest_beta/previous release in a github source spec

- cumulusci/tasks/apex/anon.py
- cumulusci/tasks/apex/tests/test_apex_tasks.py
- `AnonymousApexTask` has been revised to detect when a gack occurred during execution.
> Catch Anon Apex gack results

- cumulusci/tasks/salesforce/UpdateAdminProfile.py
This moves use of the path option into _run_task instead of _init_options so that it happens when CumulusCI has already changed to the correct project directory.
> Fix UpdateAdminProfile when used in a cross-project flow

- cumulusci/__init__.py
- cumulusci/core/config/project_config.py
- cumulusci/core/source/github.py
- cumulusci/core/source/local_folder.py
- setup.cfg
- setup.py
This will allow MetaDeploy's MetadeployProjectConfig to ensure that sub-project configs retain a reference to a MetaDeploy Plan.
> delegate sub-project config construction back to the (possibly custom) project config

- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/keychain/BaseProjectKeychain.py
- cumulusci/core/tests/test_config_expensive.py
- cumulusci/cumulusci.yml
- docs/features.rst
* Added a `devhub` service. This can be used to switch a project to a non-default sfdx dev hub using `cci service connect devhub --project`
> Make it possible to switch a project to a non-default devhub

- cumulusci/cumulusci.yml
- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_bulkdata.py
- cumulusci/tasks/bulkdata/tests/testdata.sql
- docs/bulk_data.rst
- We changed the default path for the mapping file created by the `generate_dataset_mapping` task to `datasets/mapping.yml` so that it matches the defaults for `extract_dataset` and `load_dataset`
- We changed the `extract_dataset` and `load_dataset` tasks to default to storing data in an SQL file, `datasets/sample.sql`, instead of a binary SQLite database file.
- We added a predefined `qa` scratch org. It uses the same scratch org definition file as the `dev` org, but makes it easier to spin up a second org for QA purposes without needing to first create it using `cci org scratch`.
- The `database_url` option for the `extract_dataset` and `load_dataset` tasks is no longer required. Either `database_url` or `sql_path` must be specified. If both are specified, the `sql_path` will be …
> Update bulk data task defaults

- cumulusci/__main__.py
- cumulusci/tests/test_main.py
Developers can now directly execute the local CumulusCI copy from the Python command line like
`python -m cumulusci` or `python cumulusci/__main__.py`
> Make python -m cumulusci work

- cumulusci/__main__.py
- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/tests/test_main.py
@jofsky here are a few suggested changes which you can merge into your branch if you agree:
- I merged recent changes from master
- I removed the check for whether TrialExpirationDate is present in the organization_sobject -- I went to write a test for the else clause, which led me to realize that this can't happen because _load_orginfo would error out if it couldn't get the Organization sobject
- I added assertions to the end of the org_connect tests to confirm that the correct `expires` value was stored
> Feature/connected orgs  davisagli

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/__init__.py
- cumulusci/tasks/salesforce/custom_settings.py
- cumulusci/tasks/salesforce/tests/test_custom_settings.py
- docs/bulk_data.rst
- docs/tasks.rst
- CumulusCI now includes a task, `load_custom_settings`, to upload YAML-defined Custom Settings into a target org.
> Add custom settings uploader

- cumulusci/cli/tests/test_ui.py
- cumulusci/cli/ui.py
- cumulusci/tasks/salesforce/package_upload.py
This PR updates `CliTable` to support the use of loggers where needed by adding a `table` property that returns a properly formatted string.
Also, updated `PackageUpload` to use `self.logger` for reporting apex test failures.
---
> Refactor CliTable to support logger

- .coveragerc
- cumulusci/__init__.py
- cumulusci/cli/logger.py
- cumulusci/tasks/github/merge.py
- cumulusci/tasks/push/pushfails.py
Don't include abstract methods (running them is an error in itself)
> Changes to make coverage checking less strict.

- .dependabot/config.yml
- requirements.txt
This upgrades SeleniumLibrary to version 4.1. There are no code changes, only a change to requirements.txt.
**This introduces backwards incompatibilities** which may trip up some teams. Some keywords which have been deprecated for quite a while have finally been removed and/or replaced. Most notably, `Get matching xpath count` which is a fairly common keyword. It has been replaced with a more general-purpose `Get element count`.
Release notes for SeleniumLibrary 4.1 and 4.0 that document the backwards-incompatible changes can be found on the [Releases](https://github.com/robotframework/SeleniumLibrary/releases)  page of the SeleniumLibrary project
Note: a [post](https://salesforce.quip.com/JbX0AZxopaaZ#LOfACAaMoqt) was written to the robot blog a couple of weeks ago alerting people about …
> bumb SeleniumLibrary version to 4.1

- cumulusci/cli/cci.py
- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/tests/test_config_expensive.py
- Don't add unparsed created_date and expiration_date to the CCI keychain
- Don't break if these dates weren't provided by sfdx for some reason
- Be consistent about working with these as UTC dates
> Fix a few things related to handling scratch org dates:

- cumulusci/core/tests/test_salesforce_locators.py
- cumulusci/robotframework/CumulusCI.py
- cumulusci/robotframework/locators_48.py
- cumulusci/tasks/robotframework/robotframework.py
This includes several fixes for Robot Framework issues:
- Make the CumulusCI library use our central get_simple_salesforce_connection util so that a retry policy is used.
- Create a new simple-salesforce client each time it's used instead of caching a reference on the CumulusCI library instance, since that can lead to trying to reuse a closed connection.
- Fixes using the Salesforce library with orgs on API version 48 (Spring '20) by adding a locator file for API 48.
- Added missing `self` to KeywordLogger.start_keyword; this was showing warnings when running the robot task with `-o debug True`
I've been testing these changes by running the NPSP robot tests locally.
* Updated Robot Framework Salesforce library to support the Spring '20 release.
* When the CumulusCI Robot Framework library …
> Fix Robot Framework issues

- Makefile
- docs/tasks.rst
This adjusts `make docs` to add the command which generates task reference docs from code
> make docs should regenerate task docs

- cumulusci/tasks/bulkdata/load.py
Prior to this fix, a load_data step using sql_path rather than database_url would freeze its options for metadeploy with database_url set to "sqlite://", which would then take precedence when running in MetaDeploy and not work. This avoids the problem for plans published in the future by leaving the database_url set to None at the time when the step is frozen, and moving the default "sqlite://" to get supplied while the task is running.
Fixes W-037718
* Fixed a bug with freezing the load_data task for MetaDeploy where it would use an invalid option for database_url.
> Fix freezing LoadData options for metadeploy

- cumulusci/salesforce_api/metadata.py
- cumulusci/salesforce_api/soap_envelopes.py
- cumulusci/salesforce_api/tests/test_metadata.py
- cumulusci/tasks/salesforce/Deploy.py
- docs/tasks.rst
This is based on @mrcmac's work and replaces #1066 with a branch within the SFDO-Tooling github organization so that the builds will run.
I also made some changes:
- Avoid changing the order of parameters for ApiDeploy.__init__ in case someone is passing the named arguments positionally.
- Provide the `test_level` option as a string instead of `run_tests` as a boolean, in order to better parallel testLevel in the actual API and support passing all of its options.
- Expect that check_only must be passed to ApiDeploy as a boolean, not a string.
@mrcmac please let me know if you have concerns about any of these changes.
- Fixes #1066
> Add check_only and test_level parameters to deploy task

- cumulusci/tasks/salesforce/UpdateAdminProfile.py
- cumulusci/tasks/salesforce/tests/test_UpdateAdminProfile.py
Prerelease [build failure](https://sfdo-metaci.herokuapp.com/builds/165142) when running `update_admin_profile`:
```
MetadataParseError: Could not process MDAPI response: Update of CustomObject Contact: Error on line 7891, col 20: No more than 10 columns may be specified in lookupPhoneDialogsAdditionalFields
```
This commit changes `UpdateAdminProfile` so that it only deploys the modified Admin profile. While it is necessary to retrieve profiles along their associated metadata objects, we don't need to do that for deployments.
----
> Make UpdateAdminProfile deploy profiles only

- cumulusci/cli/logger.py
File:
```
2020-01-15 17:10:25: Getting scratch org info from Salesforce DX
2020-01-15 17:10:27: Beginning task: SalUserGenerator
2020-01-15 17:10:27:        As user: test-zll48jmhtr6h@example.com
2020-01-15 17:10:27:         In org: 00D540000006gBv
```
stdout
```
2020-01-15 17:10:25: Getting scratch org info from Salesforce DX2020-01-15 17:10:27: Beginning task: SalUserGenerator2020-01-15 17:10:27:        As user: test-zll48jmhtr6h@example.com2020-01-15 17:10:27:         In org: 00D540000006gBv
```
File:
```
2020-01-15 17:12:41: Getting scratch org info from Salesforce DX
2020-01-15 17:12:45: Beginning task: SalUserGenerator
2020-01-15 17:12:45:        As user: test-zll48jmhtr6h@example.com
2020-01-15 17:12:45:         In org: 00D540000006gBv
```
stdout:
```
2020-01-15 17:12:41: Getting …
```
> Move null terminator to file logger

- cumulusci/cli/cci.py
- cumulusci/tests/test_utils.py
- cumulusci/utils.py
Fix missing newline between command args and output.
Also added special handling of click.Abort so that we don't print the gist message when the user exits using Ctrl+C.
> Add another missing newline

- HISTORY.rst
- cumulusci/__init__.py
- cumulusci/cli/cci.py
- cumulusci/core/runtime.py
- docs/install.rst
- setup.cfg
- setup.py
I think this will fix our problems (or at least make them no worse than the previous state).
It returns to only trying to load the keychain for commands that actually use it, which should resolve our problem in the `brew test` command. This could do with some sanity checks/testing to make sure I identified the correct commands.
It also will now only try to look up the keychain key if the keychain class declares itself to be an encrypted keychain. This means CI systems that set CUMULUSCI_KEYCHAIN_CLASS to cumulusci.core.keychain.EnvironmentProjectKeychain will no longer need to set CUMULUSCI_KEY if they don't have a working keyring. This is not a new bug, just something that made sense to fix while I was paying attention to it.
> Work around keychain issues

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
* Only suggest `cci gist` command we that command wasn't the last one run. (Fixes #1474) 
* Use `platform.uname` instead of `os.uname` (Fixes #1475)
> Gist fixes

- cumulusci/tasks/release_notes/generator.py
- cumulusci/tasks/release_notes/parser.py
* Fixed a bug where the `github_parent_pr_notes` was attempting to post comments on issues related to child pull request change notes. We want these comments to occur only when running task `github_release_notes` (the comment on the issue notes the tag in which it was fixed). Fixes #1482
> Don't comment on issues when no tag present

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/EnsureRecordTypes.py
- cumulusci/tasks/salesforce/tests/test_EnsureRecordTypes.py
- docs/tasks.rst
- The `EnsureRecordTypes` class is now exposed as `ensure_record_types` and correctly supports the Case, Lead, and Solution sObjects (in addition to other standard objects).
> Enhance EnsureRecordTypes to work properly with Case, Lead, and Solution

- cumulusci/robotframework/Salesforce.py
- cumulusci/robotframework/locators_47.py
- cumulusci/robotframework/locators_48.py
- cumulusci/robotframework/tests/salesforce/ui.robot
This fixes keyword issues that have been reported for Spring '20. The biggest change is in
the populate keywords, where I rewrote the basic algorithm for finding the input elements. There are also fixes for clicking on related item links. 
Unfortunately, an input element and its label can be marked up in at least two different ways, and the ways are so different as to make it almost impossible to craft a single xpath that works in both cases. With this change, we find the label and then use the 'for' attribute on that element to get the id of
the related input element. All of our tests pass with this change, and I've also spot-checked it with several NPSP tests that were brought to my attention.
> Robot spring20 part2

- cumulusci/robotframework/Salesforce.py
The change worked in Spring '20 but not in Winter '20. We don't have any tests for this keyword, I've
been using NPSP to test it. Specifically, the test create_organization.robot
> Revert change to `select_record_type`

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- docs/features.rst
* New top level `cci error` command for interacting with errors in CumulusCI
* `cci gist` moved to `cci error gist`
* `cci error info` displays lines of a stacktrace from the previous `cci` command run. 
* Prompt when encountering error's in cci now suggests `cci error help` (instead of `cci gist`)
* closes #1494 
* closes #1498
> CumulusCI `error` Command

- cumulusci/tasks/bulkdata/generate_from_yaml.py
Previously if num_records was specified on the CLI (as opposed to in the YAML), it would cause a type error in Snowfakery.
> Convert num_records to a number if provided as str

- cumulusci/tasks/bulkdata/generate_and_load_data.py
- cumulusci/tasks/bulkdata/tests/test_generate_and_load.py
This class orchestrates generating and loading data. "Inheriting" options from LoadData directly helps keep its options in sync and in particular gives it access to the bulk_mode property.
> Include LoadData options by default. Especially bulk_mode.

- cumulusci/robotframework/tests/cumulusci/bulkdata.robot
- cumulusci/tasks/bulkdata/delete.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_bulkdata.py
- cumulusci/tasks/bulkdata/tests/test_delete.py
- cumulusci/tasks/bulkdata/utils.py
If a batch job has numberRecordsFailed then _wait_for_job will throw an exception. (this part is controversial)
Unless it is caught, the task that called it will throw an exception.
This means that the keywords Run Task and Run Task Class will also error.
All of this is tested below.
As far as we know, only DeleteData and LoadData uses these functions, but we don't know for sure about customers in the market.
It is unclear whether LoadData behaviour changes significantly, because it already has some error checking and exception raising.
====
This MAY NOT be an entirely backwards compatible change. Who knows how many errors are currently being swallowed in DeleteData (and perhaps also LoadData)? It is possible that some flows which currently seem to succeed will be revealed to actually …
> Failed deletes (and loads) throw an exception

- cumulusci/cli/cci.py
This fixes a regression where the keychain was not loaded for the `flow info` and `task info` commands (it's needed to get the github service when using cross-project flows)
Fixes #1529
> Fix keychain for flow and task info

- cumulusci/tasks/sfdx.py
- cumulusci/tasks/tests/test_sfdx.py
* Fixed a bug where using SFDXOrgTask to run an sfdx command on a non-scratch org would break with "Must pass a username and/or OAuth options when creating an AuthInfo instance."
> Fix env var for passing persistent org access token to sfdx

- cumulusci/__init__.py
- setup.cfg
- setup.py
This updates the package version so that MetaShare can use it before we make a new CumulusCI release.
> Update to dev version

- cumulusci/tasks/salesforce/metadata_etl/__init__.py
- cumulusci/tasks/salesforce/metadata_etl/base.py
- cumulusci/tasks/salesforce/metadata_etl/layouts.py
- cumulusci/tasks/salesforce/metadata_etl/permissions.py
- cumulusci/tasks/salesforce/metadata_etl/sharing.py
- cumulusci/tasks/salesforce/metadata_etl/tests/test_base.py
- cumulusci/tasks/salesforce/metadata_etl/tests/test_layouts.py
- cumulusci/tasks/salesforce/metadata_etl/tests/test_permissions.py
- cumulusci/tasks/salesforce/metadata_etl/tests/test_sharing.py
- cumulusci/tasks/salesforce/metadata_etl/tests/test_value_sets.py
- cumulusci/tasks/salesforce/metadata_etl/value_sets.py
- Use lxml etree for manipulating XML (turns out f-strings make it nicer than it used to be!)
- Use camel case class names for test classes, and don't extend unittest.TestCase because we don't need to
- Declare ABCMeta metaclass the correct way for Python 3
- Add a log line before the metadata retrieve and deploy to clarify what we're showing progress of
- Fix `required` parameter of task options to be a boolean
> Various adjustments to metadata ETL

- cumulusci/core/source/github.py
- cumulusci/core/tests/test_source.py
- Fixed an issue where an error while extracting the codebase of a cross-project source could leave behind an incomplete copy of the codebase which would then be used by future commands.
> Avoid leaving an incomplete codebase in the cache if zipball extraction fails

- cumulusci/tasks/metadata_etl/base.py
- cumulusci/tasks/metadata_etl/layouts.py
- cumulusci/tasks/metadata_etl/tests/test_base.py
- cumulusci/tasks/metadata_etl/tests/test_layouts.py
This PR corrects a couple of small issues with Metadata ETL:
- Failure to correctly omit deployment of entities that the transformer task declined to act on.
- Failure to identify entities pulled by a wildcard and transform them.
- Added code to handle URL-encoded file names for entities like Page Layouts (such as `Contact-Contact %28Marketing%29 Layout.layout`)
> Fix issues with wildcards and dropped entities in Metadata ETL

- cumulusci/tasks/metadata_etl/sharing.py
- cumulusci/tasks/metadata_etl/tests/test_sharing.py
Fixes a conflict between base Metadata ETL classes and SetOrgWideDefaults.
> Make sure SetOrgWideDefaults treats api_names as a set

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
I noticed that commands with missing parameters (e.g. `cci flow info` with no flow specified) were breaking rather than reporting the missing parameter.
* Fixed a regression where errors due to missing command line parameters were not reported correctly.
> Fix formatting of ClickExceptions

- cumulusci/tasks/metadata_etl/layouts.py
- cumulusci/tasks/metadata_etl/tests/test_layouts.py
- docs/tasks.rst
- `add_page_layout_related_lists` now supports suppressing standard buttons and adding custom buttons on related lists.
> Specify excluded and custom buttons to new Related Lists

- cumulusci/__init__.py
- cumulusci/core/flowrunner.py
- cumulusci/core/tests/test_flowrunner.py
- setup.cfg
- setup.py
- Corrected an issue in storing preflight check results where multiple tasks had the same path.
> Use step_num as key for preflight results

- cumulusci/cli/cci.py
- added a note about including access token for json option to the help message for `cci org info command`
- #1566
> add note about including access token for json option to help message for cci org info command

- cumulusci/tasks/apex/testrunner.py
- cumulusci/tasks/apex/tests/test_apex_tasks.py
- CumulusCI now will not attempt to retry class-level concurrency failures when running Apex unit tests in a managed package due to changes made to the Tooling API in Spring '20. Such failures will be logged but will not cause a build failure.
> Fix test runner for Spring '20

- cumulusci/tasks/bulkdata/delete.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_delete.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/utils.py
I have had problems in LDV orgs when the logs got gargantuan due to per-row errors. This avoids that.
> Truncate warnings

- cumulusci/tasks/github/release.py
- cumulusci/tasks/github/tests/test_release.py
- Fixed the github_release task to make sure it was run with a valid 40-character commit hash.
> CreateRelease task option validation

- cumulusci/core/sfdx.py
- cumulusci/core/tests/test_sfdx.py
- cumulusci/tasks/salesforce/sourcetracking.py
The retrieve_components helper now makes sure the target path is absolute before switching to a different working directory. This was not an issue when used from the retrieve_changes task (which is why I'm not putting it in the release notes) but affected MetaShare.
- If there is an error from sfdx while using the `retrieve_changes` task, it will now be logged.
> Fix a couple things related to retrieve_changes

- cumulusci/cumulusci.yml
- cumulusci/files/admin_profile.xml
- cumulusci/tasks/metadata_etl/__init__.py
- cumulusci/tasks/salesforce/__init__.py
- cumulusci/tasks/salesforce/tests/test_Deploy.py
- cumulusci/tasks/salesforce/tests/test_ProfileGrantAllAccess.py
- cumulusci/tasks/salesforce/tests/test_UpdateProfile.py
- cumulusci/tasks/salesforce/update_profile.py
- cumulusci/tasks/tests/test_metadeploy.py
- docs/tasks.rst
This PR converts UpdateAdminProfile/UpdateProfile to a Metadata ETL task called ProfileGrantAllAccess.
- The `UpdateAdminProfile`/`UpdateProfile` task has been revised to use the new Metadata ETL framework as `ProfileGrantAllAccess`. This is a breaking change for local tasks which subclassed `UpdateAdminProfile`. The new task supports updating arbitrary Profiles in addition to System Administrator. 
- **Note**: At time of release, please update `update_profile.py` line 89 to actual version number.
> Rebuild UpdateAdminProfile as a Metadata ETL task

- cumulusci/tasks/salesforce/tests/test_ProfileGrantAllAccess.py
When run on my machine, test_generate_package_xml__retrieve leaves behind a copy of `admin_profile.xml`.
> Use temporary dir for test

- cumulusci/core/tasks.py
- cumulusci/tasks/metadata_etl/base.py
- cumulusci/tasks/metadata_etl/sharing.py
- cumulusci/tasks/metadata_etl/tests/test_base.py
- cumulusci/tasks/salesforce/BaseSalesforceTask.py
This is my attempt to fix the import cycle (W-7346064) by:
1. moving BaseSalesforceTask into cumulusci.core.tasks so that cumulusci.tasks.metadata_etl.base can import it without trying to import other tasks that use the metadata ETL framework
2. moving cumulusci.tasks.metadata_etl.base's import of the Deploy task to happen at runtime
I also switched BaseMetadataETLTask to extend BaseSalesforceTask rather than BaseSalesforceApiTask since metadata ETL tasks do not necessarily use the REST API. Let me know if you have concerns about this @davidmreed -- and could you help confirm that I didn't break the set_organization_wide_defaults task with this change?
* Fixed a bug that caused errors when trying to import metadata ETL tasks.
> Proposed change to resolve import cycle

- cumulusci/tasks/metadata_etl/sharing.py
- cumulusci/tasks/metadata_etl/tests/test_sharing.py
- cumulusci/tasks/salesforce/tests/test_ProfileGrantAllAccess.py
- cumulusci/tasks/salesforce/update_profile.py
- Correct a bug in how the `set_organization_wide_defaults` task operated in namespaced scratch orgs.
> Proposed solution for namespaced orgs

- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/mapping_parser.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- requirements.txt
1. I forgot bulk_mode in the schema because there were no example mapping files with it. Fixed now.
2. Renamed _load_mapping to _execute_step because _load_mapping always implied to me that it was loading the mapping file. This is subjective so tell me if you disagree.
3. I added stronger type checking which is how I found problem 1. Integration tests don't use bulk_mode but unit tests do
4. I deleted the test that checks what happens if a bulk_mode is set to a wrong value in mapping because the mapping parser should handle that now and it is hard to trigger with both pytest and typeguard working at the same time. In any case, the Salesforce API would give you an error pretty quickly if you found a way around all of this type checking...
> 1. bulk_mode. 2. _execute_step. 3. Type checking.

- cumulusci/utils/fileutils.py
- cumulusci/utils/tests/test_fileutils.py
I notice this test fails if the Internet is down. That's because it uses urllib in a doctest example and urrlib was not mocked.
> Mock urllib in addition to Requests

- cumulusci/tasks/robotframework/robotframework.py
- cumulusci/tasks/robotframework/tests/test_robotframework.py
Previously, the robot task assumed the error code represented the number of failed tests. That is only correct up to the value 250. After that, different values mean different things.
For more information see [return codes](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#return-codes
) in the robot user guide
> Robot task now prints correct message based off of error code

- cumulusci/core/config/project_config.py
Since we handle non-breaking spaces when loading cumulusci.yml from a local directory, we should also handle them when loading cumulusci.yml from a dependency. Otherwise it's possible to have a config that works until it's loaded as a dependency. (e.g. https://success.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009M9Z&fId=0D53A00004rLMTz&s1oid=00D300000000iTz&s1nid=0DB30000000072L&emkind=chatterCommentNotification&s1uid=0053A00000CB68z&emtm=1585875372517&fromEmail=1&s1ext=0)
- Don't error when loading a dependency whose cumulusci.yml contains non-breaking spaces.
> Handle nbsp in dependency cumulusci.yml

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/license_preflights.py
- cumulusci/tasks/salesforce/tests/test_license_preflights.py
- docs/tasks.rst
- Two new preflight check tasks are available for use in MetaDeploy: `get_available_licenses()` and `get_available_permission_set_licenses()`. These tasks make available lists of the License Definition Keys for the org's licenses or PSLs.
> Add license-related preflight checks

- cumulusci/tasks/salesforce/org_settings.py
- cumulusci/tasks/salesforce/tests/test_org_settings.py
This is an attempt to fix an issue where Metecho can't deploy org settings for EDA because EDA's package version is 45.0 but it has org definition files using settings that are only available in more recent API versions. sfdx also uses the latest API version when it deploys these settings.
> Deploy org settings using the org's API version, not the package's

- cumulusci/cli/runtime.py
- cumulusci/cli/tests/test_runtime.py
This commit suppreses the user prompt upon scratch org expiration.
----
- We've removed the prompt users see when a scratch org expires, and now automatically recreate the scratch org.
- Fixes #1136
> Don't prompt for scratch org recreation

- cumulusci/__init__.py
OrderDicts are not convenient from the point of view of repr, YAML, pprint and other libraries that prefer standard dicts. They are also less efficient and offer no extra benefit in modern versions of Python.
This PR replaces their use in simple_salesforce with standard dicts.
> Death to OrderedDicts

- cumulusci/cli/cci.py
* change the text which is displayed to users on error to not use backticks.
> change suggest error cmd text

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
* We now set the `tempfile_log` variable to None and check for the presence of its value in the `handle_exception()` method. This fixes a bug that occurred if we encountered an exception when running any of the `cci error ...` commands.
> Don't log stacktrace when running `cci error` cmds

- cumulusci/cli/tests/test_runtime.py
Wasted a few minutes of mine time. I thought maybe I can avoid it for someone in the future.
> Make tests succeed whether or not CUMULUSCI_KEYCHAIN_CLASS is set

- cumulusci/robotframework/locators_49.py
The app launcher container appears to have changed from a `nav` element to a `div`.
> update locator for app launcher button in summer 20

- cumulusci/tasks/metadata/metadata_map.yml
- The `NavigationMenu` metadata type is now supported.
> Add metadata map for Navigation Menu

- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_load.py
If you mistype a record type name, you would previously get an IndexError. Now you get a clearer message.
> Improve error messaging around record types

- cumulusci/tasks/bulkdata/generate_and_load_data.py
- cumulusci/tasks/bulkdata/generate_from_yaml.py
Fix a bug which prevented user from specifying the generate_mapping_file option. The task info implied they could, but we overwrote it with a temp file.
Also simplify the code a bit. There was no reason to open the temp file. The code just evolved that way from previous code where it was a
TemporaryNamedFile().
> Allow the user to specify generate_mapping_file

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/config/OrgConfig.py
- cumulusci/core/flowrunner.py
- cumulusci/core/tests/test_config.py
- cumulusci/files/templates/project/cumulusci.yml
- cumulusci/tasks/apex/testrunner.py
- cumulusci/tasks/apex/tests/test_apex_tasks.py
- cumulusci/tasks/salesforce/BaseSalesforceMetadataApiTask.py
- cumulusci/tasks/salesforce/InstallPackageVersion.py
- cumulusci/tasks/salesforce/UpdateDependencies.py
- docs/tasks.rst
- The `OrgConfig` object exposes an `installed_packages` property, containing a `dict` mapping package namespaces to `StrictVersion` objects with the installed version number. This property is accessible in `when` clauses and is updated automatically when CumulusCI performs a Metadata API deployment.
- `when` clauses may create `StrictVersion` objects, which can be compared with installed package versions.
- The `run_tests` task supports a new option, `required_org_code_coverage_percent`. If set, the task will fail if aggregate code coverage in the org is less than the configured value. Code coverage verification is available only in unmanaged builds.
> Installed package access in OrgConfig + Apex test code coverage enforcement

- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/utils.py
- cumulusci/tasks/salesforce/BaseSalesforceApiTask.py
Bulk API previously defaulted its API Version to SalesforceBulk's API version, which was 40.0. Some fields therefore could not be loaded.
> Bulk API should use project API version.

- cumulusci/salesforce_api/package_zip.py
- cumulusci/tasks/salesforce/InstallPackageVersion.py
- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/tasks/salesforce/tests/test_InstallPackageVersion.py
- cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
- cumulusci/tasks/tests/test_metadeploy.py
- docs/tasks.rst
* The install_managed and update_dependencies tasks now accept a security_type option to specify which users the package should be installed for.
> expose InstalledPackage securityType

- requirements.txt
There doesn't appear to be anything surprising in SeleniumLibrary 4.4.0. I ran all of the CumulusCI tests in both the dev and prerelease orgs without a hitch.
> Upgrade robotframework-seleniumlibrary from 4.3.0 to 4.4.0

- cumulusci/core/config/ScratchOrgConfig.py
* Scratch org creation will now wait up to 120 minutes for the org to be created to avoid timeouts with more complex org shapes
> Add wait of 120 minutes to org creation

- cumulusci/tests/test_utils.py
- cumulusci/utils/__init__.py
- `deploy` now supports the `%%%NAMESPACE_DOT%%%` injection token, which can be used to support references to packaged Apex classes and Record Types. The token is replaced with `ns.` rather than `ns__`, for namespace `ns`.
> Add support for the %%%NAMESPACE_DOT%%% token, to reference Apex classes and managed Record Types

- cumulusci/tasks/apex/testrunner.py
- cumulusci/tasks/apex/tests/test_apex_tasks.py
- The `run_tests` task now gracefully handles the `required_org_code_coverage_percent` option as a string or an integer.
> Handle code coverage levels specified as integers

- cumulusci/cumulusci.yml
- docs/tasks.rst
- A generic `dx` task makes it easy to run Salesforce DX commands against scratch orgs created in CumulusCI. Use the `command` option to specify the DX command.
> Add generic dx task

- README.rst
Remove reference to CumulusCI 1.0 based on `ant` from README.
> Remove reference to CumulusCI 1.0 based on `ant`

- cumulusci/tasks/bulkdata/generate_and_load_data.py
- cumulusci/tasks/bulkdata/tests/test_generate_and_load.py
- docs/tasks.rst
generate_and_load and generate_and_load_from_yaml tasks now respect the working_directory option and store their tempfiles in the working directory. This is primarily helpful for debugging.
debug_dir was another name for working_directory and has been removed.
> Use working directory if provided

- cumulusci/tasks/salesforce/UpdateDependencies.py
- cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
Check org_config.scratch instead of isinstance(org_config, ScratchOrgConfig). In Metecho, OrgConfig is used for scratch orgs too to avoid calling out to sfdx.
- Fixed a bug in the logic to prevent installing beta packages in non-scratch orgs which affected Metecho.
> Fix the logic for blocking beta installs in non-scratch orgs

- .github/workflows/feature_test.yml
- .github/workflows/release_test.yml
- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/config/project_config.py
- cumulusci/core/github.py
- cumulusci/core/tests/test_config.py
- cumulusci/core/tests/test_config_expensive.py
- cumulusci/core/tests/test_github.py
- cumulusci/core/tests/test_source.py
- cumulusci/cumulusci.yml
- cumulusci/files/templates/project/cumulusci.yml
- cumulusci/salesforce_api/tests/test_metadata.py
- cumulusci/tasks/github/tests/test_merge.py
- cumulusci/tasks/github/tests/test_util.py
- cumulusci/tasks/github/tests/util_github_api.py
- cumulusci/tasks/release_notes/provider.py
- cumulusci/tasks/release_notes/task.py
- cumulusci/tasks/release_notes/tests/test_generator.py
- cumulusci/tasks/release_notes/tests/test_task.py
- cumulusci/tasks/salesforce/UninstallPackagedIncremental.py
- cumulusci/tests/test_utils.py
- cumulusci/utils/git.py
- docs/cookbook.rst
- docs/index.rst
- docs/tutorial.rst
Use current branch as default in `cci project init`. Also changed uses of "master" to "main" where it could be done trivially.
- `cci project init` now sets `default_branch` to the current git branch.
- Fixed a formatting error when running `cci project init` with a custom default_branch (fixes #1780)
> Use current branch as default for cci project init

- cumulusci/tasks/salesforce/InstallPackageVersion.py
- The `install_managed` task now recognizes an additional error message that may be issued by the Metadata API when a package version has not yet finished propagating and performs retries appropriately.
> Add new error string to package install retries

- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_extract.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/test_utils.py
- cumulusci/tasks/bulkdata/utils.py
@spelak-salesforce Here are some suggestions for #1829 that I thought would be easier to show than explain:
1. I moved the caching of _person_accounts_enabled into an OrgInfoMixin that is extended by both the extract and load tasks. This encapsulates the caching functionality so it's all in one place and can be tested separately.
2. I renamed some methods to better express what they do:
- `ExtractData._is_person_accounts_enabled` -> `_org_has_person_accounts_enabled`
- `LoadData. _is_person_account_column_exists` -> `_db_has_person_accounts_column`
- `LoadData._is_person_accounts_enabled` -> `_can_load_person_accounts`
3. Stopped using a separate method for `_get_account_id_lookup`, since it can be written as a one-liner.
4. I removed the use of `lower()` to check for schema names case …
> Suggested changes for bulkdata person accounts handling

- cumulusci/tasks/salesforce/CreateCommunity.py
- cumulusci/tasks/salesforce/tests/test_CreateCommunity.py
- docs/tasks.rst
When troubleshooting/developing community automation it can be useful to ignore exceptions caused by an existing community.
- We added a new option, `skip_existing`, to the `create_community` task. When `True`, the task will not raise an exception when a community with the same name exists in the org.
> Add option to ignore existing community

- cumulusci/tasks/push/pushfails.py
- cumulusci/tasks/tests/test_pushfails.py
- requirements.txt
Also finish removing unicodecsv while we're in here.
- Fixed a bug where the push_failure_report task could be missing some failed orgs if there were more than 200 errors.
> Use query_all for push failure reports

- cumulusci/cumulusci.yml
- cumulusci/tasks/github/public_repo.py
- cumulusci/tasks/github/publish.py
- cumulusci/tasks/github/tests/test_publish.py
- cumulusci/tasks/github/tests/test_util.py
- cumulusci/tasks/github/util.py
- docs/tasks.rst
- We added a new task, `github_publish_subtree`, to allow publishing a list of files or directories to another repository after a release. This allows pushing a subset of your project's code from a private repository to a public one, for example.
Closes #1414
> Add task to publish project files for a release to a second repository

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/tests/test_insert_record.py
- cumulusci/tests/cassettes/TestIntegrationInfrastructure.test_integration_tests.yaml
- New projects now default to using API version 49.0
> Update the default API version for new projects

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/keychain/BaseProjectKeychain.py
- cumulusci/core/keychain/encrypted_file_project_keychain.py
- cumulusci/core/tests/test_keychain.py
Previously there were subtle issues where local org files were being created and shadowing global ones. So, for example, removing a global org might not remove it for all projects.
Fixing that bug exposed a logic error because "default" was stored on a boolean in the orgconfig which means that if a global org is defaulted it will be defaulted for all projects. This fixes that bug.
The default is now stored externally in its own file analogous to how Git stores its HEAD.
> Global orgs had bugs relating to defaulting

- .github/workflows/feature_test.yml
- cumulusci/tasks/bulkdata/mapping_parser.py
- cumulusci/tasks/bulkdata/tests/test_mapping_parser.py
- cumulusci/tasks/bulkdata/tests/test_utils.py
A pre-release (?) version of CumulusCI was very strict about requiring the case of sObjects and Fields to be exactly the same as the "canonical" Salesforce name. This puts it back to being case agnostic.
> Case agnostic bulkdata

- cumulusci/tasks/release_notes/parser.py
- cumulusci/tasks/release_notes/tests/test_parser.py
- Fixed a bug in the `github_release_notes` task where a note could be listed under a subheading from another section.
> fix release notes bug: reset subheading when a new heading is found

- cumulusci/core/flowrunner.py
- cumulusci/core/tests/test_flowrunner.py
Use a custom subclass of LooseVersion to parse step numbers, so that we can handle the "/" separator between subflow levels in comparisons without throwing a TypeError
- fixes #1914
> Fix step sorting

- cumulusci/tasks/bulkdata/generate_from_yaml.py
- cumulusci/tasks/bulkdata/tests/test_generate_from_snowfakery_task.py
There is a bug reported by a Windows user relating to Tempfile handling of CCI+Snowfakery. If an exception is thrown by Snowfakery, the continuation file is not closed before the TempDirectory is deleted. This causes another Windows error which obscures the first one and makes it nearly impossible to detect and fix or workaround. This PR fixes that.
I added some test cases, one of which provokes the bug.
I turned the method that opens the continuation file into a context manager and nested everything inside of it.
> Fix CCI+Snowfakery Continuation Tempfile handling on Windows

- cumulusci/core/keychain/encrypted_file_project_keychain.py
- cumulusci/core/tests/test_keychain.py
If the file that designates the default org points to an org that can't be loaded, treat that the same as simply having no default at all.
> Recover gracefully from missing default orgs

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/tests/test_config.py
> Note: there is a child branch #1950 that refactors bulkdata to use the feature in this Pull Request to identify if the org has person accounts enabled.
OrgConfig supports identifying if the org has person accounts enabled via `is_person_accounts` property.
> OrgConfig supports is_person_accounts_enabled

- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_extract.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/test_utils.py
- cumulusci/tasks/bulkdata/utils.py
> Note: Is a child branch of #1949 .   Rebase to `master` after merging #1949  ✅ 
Bulk data extraction and loading use `org_config.is_person_accounts_enabled` to identify if the org has person accounts enabled.
> bulkdata uses org_config.is_person_accounts_enabled

- requirements.txt
- requirements_dev.txt
Remove factory-boy as a runtime requirement of CumulusCI
Its runtime uses have been replaced by Snowfakery now.
> Move factory-boy to requirements_dev

- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/tests/test_metadeploy.py
Make sure language codes like es-mx get passed to MetaDeploy correctly. Also, show a warning rather than aborting if the translation couldn't be loaded.
Actually using these translations requires additional changes in MetaDeploy which are in progress in https://github.com/SFDO-Tooling/MetaDeploy/pull/1652
- The metadeploy_publish task can now update translations for language codes with more than 2 letters.
> Fix publishing regional translations

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/tasks/metadata_etl/base.py
Without this it would use locale.getpreferredencoding(), which at least in some cases is cp1252 in Windows.
Also includes a fix for #1514 to make `cci error info` show the full traceback by default.
- The `cci error info` command now defaults to showing the entire traceback when it is more than 30 lines.
- Fixed a bug where `cci error gist` could throw a UnicodeDecodeError (fixes #1977)
> Fix a couple places where utf-8 was not specified explicitly for Path.read_text/write_text

- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_extract.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/testdata.sql
- docs/tutorial.rst
See https://powerofus.force.com/s/feed/0D51E00005PC9lE?fromEmail=1&s1oid=00D00000000hWLM&s1nid=0DB800000004Fa7&s1uid=0058000000FMbc6&s1ext=0&emkind=chatterCommentNotification&emtm=1598910073619
- Fixed a bug where the `extract_dataset` task could fail with a UnicodeEncodeError on Windows.
> fix .sql extract/load with non-ASCII characters on Windows

- cumulusci/tasks/salesforce/InstallPackageVersion.py
- cumulusci/tasks/tests/test_metadeploy.py
- CumulusCI now tries 10 times (instead of 5) to install managed package versions, which helps ameliorate timeouts when new versions are released.
> Double number of package install retries

- cumulusci/robotframework/Salesforce.py
- cumulusci/robotframework/locators_50.py
- cumulusci/robotframework/tests/salesforce/ui.robot
This has changes to all of the related list locators for winter '21, along with a few other changes that cropped up during prerelease testing. 
Related lists may be rendered in a couple of different ways, this new locator should work for either way. I also took the liberty of refactoring the 'load related list' keyword to use some features in SeleniumLibrary that weren't available when the keyword was written nearly two years ago. I also added some tests for this keyword, which we didn't previously have.
I'm still working on some automated tests. A couple of the issues can be reproduced via an NPSP test, but I can't yet reproduce them in our CumulusCI tests. 
* The following robot keywords have been updated to work with Winter '21: 
- `Load related list`
- `Click related list button`
- …
> Update related list locator for Winter '21.

- cumulusci/tasks/salesforce/sourcetracking.py
- cumulusci/tasks/salesforce/tests/test_sourcetracking.py
Fix retrieving folders that have changes detected by source tracking.
Folders need to be referenced in the package.xml section for the type they contain -- https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_folder.htm
- Fixed an issue where the retrieve_changes task did not actually retrieve folders.
> retrieve_changes: fix retrieving changed folders

- cumulusci/core/config/project_config.py
- cumulusci/core/tests/test_config.py
- cumulusci/tasks/salesforce/BaseRetrieveMetadata.py
- cumulusci/tasks/salesforce/Deploy.py
- cumulusci/tasks/salesforce/UpdateDependencies.py
- docs/tasks.rst
(There is a small chance that these could be used creatively to tokenize one namespace and then inject another, but I'm not aware of that being done in the wild.)
- Removed the `namespace_tokenize` option from tasks that deploy metadata, and removed the `namespace_inject` option from tasks that retrieve metadata, because it's unclear when they would be useful.
> Remove nonsensical namespace options

- cumulusci/tasks/metadeploy.py
I'm changing this so it only matches strings that start with "Install " _and_ end with a number.
- Fix a bug in the metadeploy_publish task where labels starting with "Install " were not extracted for localization.
> metadeploy_publish: fix overeager match for package install labels

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/tests/test_config.py
- cumulusci/oauth/salesforce.py
When the SFDX_CLIENT_ID and SFDX_HUB_KEY environment variables are set, CumulusCI uses the JWT oauth flow to get a fresh access token for an org. In order to do that, it needs to correctly specify `aud` in the JWT as either https://login.salesforce.com or https://test.salesforce.com
Previously, we used the instance URL to pick the `aud` value (based on whether the URL contained a sandbox instance name like cs22, or not). But lately it is possible for there to be sandboxes with "instanceless" instance URLs that do not include the instance name.
As an alternative, this passes the `id` from the org config into the jwt_session function. It will not always be present, but it should be for orgs that were connected using oauth, and it also starts with either the production or sandbox login URL …
> Fix JWT aud for instanceless sandboxes

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/create_permission_sets.py
- cumulusci/tasks/salesforce/tests/test_create_permission_sets.py
- docs/bulk_data.rst
- docs/tasks.rst
- The task `create_permission_set` allows for creating and assigning a Permission Set that enables specific User Permissions. (Note: other types of permissions are not yet supported).
- The task `create_bulk_data_permission_set` creates a Permission Set with the Hard Delete and Set Audit Fields permissions for use with data load operations. The org permission to allow Set Audit Fields must be turned on.
> Add task for creating Permission Set with specific User Permissions

- cumulusci/tasks/bulkdata/dates.py
- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/mapping_parser.py
- cumulusci/tasks/bulkdata/tests/test_dates.py
- cumulusci/tasks/bulkdata/tests/test_extract.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/test_mapping_parser.py
- cumulusci/tasks/bulkdata/tests/test_utils.py
- cumulusci/tasks/bulkdata/utils.py
- docs/bulk_data.rst
- CumulusCI's `load_dataset` and `extract_dataset` tasks now support relative dates. To take advantage of relative dates, include the `anchor_date` key (with a date in `YYYY-MM-DD` format) in each mapping step you wish to relativize. On extract, dates will be modified to be the same interval from the anchor date as they are from the current date; on load, dates will be modified to be the same interval from today's date as they are from their anchor. Both date and date-time fields are supported.
> Bulk Data Relative Dates

- docs/robotframework-debugger.rst
- docs/robotframework-tutorial.rst
This is intended to improve the readability of the navigation sidebar that sphinx creates with the Alabaster theme. The title "Robot Framework Debugger" currently has the word "Debugger" wrapped underneath, which makes it look like there are two separate sections—"Robot Framework" and "Debugger". I removed the word "framework" from the "Robot Framework Tutorial" section as well for consistency. 
Current state looks like this:
The proposed changes  look like this:
> Robot Doc Title Changes

- cumulusci/cli/tests/test_cci.py
- cumulusci/cli/tests/test_runtime.py
- cumulusci/conftest.py
- cumulusci/core/tests/test_config_expensive.py
Create a fake HOME directory to insulate all tests from the user's real HOME directory (and vice versa).
> Make all tests independent of home directory

- cumulusci/core/config/project_config.py
- cumulusci/core/config/universal_config.py
Make sure we're opening config files as utf-8
- Fixed UnicodeDecodeError while opening config files on Windows.
> fix more problems with using the wrong encoding on Windows

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/cumulusci.yml
Closes #1833
Please comment on initial group names / groupings, they are malleable.
* `cci flow list` now displays flows in groups (like `cci task list`)
* Removed the `retrieve_scratch` flow. This predated the `retrieve_changes` task which is the current recommendation for retrieving source-tracked changes.
> Flow Groups

- cumulusci/cumulusci.yml
For a while we'll be using the ci_feature_2gp flow in parallel with the existing ci_feature flow, so let's avoid a race condition where they're both trying to automerge.
> Don't automerge from 2gp feature builds yet

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/tests/test_config.py
- CumulusCI handles a rare situation where installed packages could be in a state that causes failures while fetching installed versions.
> Patch around issue with null SubscriberPackageVersion

- .github/workflows/build_docs.yml
- docs/index.rst
This makes the built docs available for download. It's not super obvious (you have to click into the Details for the Build Docs action, then look for the Artifacts menu, download the docs, unzip and open index.html) but at least it's available.
> upload doc artifact

- cumulusci/tasks/apex/anon.py
- cumulusci/tasks/salesforce/UninstallLocalNamespacedBundles.py
- cumulusci/tasks/salesforce/custom_settings_wait.py
- We corrected edge cases in how we processed Boolean options for the `custom_settings_wait`, `exec_anon`, and `uninstall_post` tasks. (Thanks to @davidjray)
> Fix missing use of process_bool_arg()

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/config/SfdxOrgConfig.py
- cumulusci/core/tests/test_config.py
Constructing a new one is cheap (it doesn't make a request when instantiated with an existing access token) and avoids the potential for using an old connection that was closed by the server.
- Fixed a connection error which could occur if uploading a package took over 10 minutes.
> Stop memoizing the salesforce_client on OrgConfig

- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- We fixed an issue causing non-Person-Account Contacts to be omitted during Person Account data loads when the dataset was extracted using the REST API.
> Fix handling of Boolean in Person Account loads

- cumulusci/tasks/salesforce/tests/test_ProfileGrantAllAccess.py
- cumulusci/tasks/salesforce/update_profile.py
- The `update_admin_profile` task now accepts the `api_names` option to target extra Profiles, even when using a custom `package.xml`.
> Allow update_admin_profile to use a custom package with extra Profile names

- .github/workflows/release_test.yml
- cumulusci/tasks/github/merge.py
- cumulusci/tasks/github/tests/test_merge.py
- docs/tasks.rst
* The task `github_automerge_main` now merges the most recent commit into branches that begin with the `feature_prefix` when the source branch is a non-feature branch (includeing main/master).
> merge non-feature source into feature branches

- cumulusci/cumulusci.yml
- cumulusci/tasks/preflight/settings.py
- cumulusci/tasks/preflight/tests/test_settings.py
- docs/tasks.rst
- CumulusCI offers preflight checks to validate org settings (`check_org_settings_value`) and to check that Chatter is enabled (`check_chatter_enabled`).
> Add preflight checks for org settings, including Chatter

- .github/workflows/release_test.yml
- cumulusci/core/config/OrgConfig.py
- cumulusci/core/tests/test_config.py
- cumulusci/tasks/tests/test_package_2gp.py
We won't want this in the long term, because it adds more queries, but I think it will help avoid the query timeout we're currently seeing with InstalledSubscriberPackage
> Workaround for slow SPV query by splitting it apart

- cumulusci/tasks/metadata/package.py
- cumulusci/tasks/metadata/tests/test_package.py
This adjusts the condition for when a folder should be included in package.xml. We already handled one case where an item is being added to an existing folder that is not itself in the package, by excluding folders with a namespace (indicating they came from another package). Now we look for the existence of a -meta.xml file for the folder, which should handle that case as well as the one where an item is being added to an existing folder that is unpackaged or part of a different unmanaged package (including the Public Reports folder).
- Fixed the update_package_xml task for metadata packages that add items to folders (i.e. reports, dashboards, etc) that already exist.
> Fix update_package_xml for folders without -meta.xml

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/users/permsets.py
- cumulusci/tasks/salesforce/users/tests/test_permsets.py
- docs/tasks.rst
- CumulusCI offers an `assign_permission_sets` task, which assigns one or more Permission Sets to the running user if not already assigned. This task may replace invocations of `dx`.
> Add assign_permission_sets task

- cumulusci/core/tests/test_utils.py
- cumulusci/core/utils.py
- cumulusci/tasks/bulkdata/step.py
- cumulusci/tasks/bulkdata/tests/test_step.py
For dataloads: previously only a "True" and "true" were considered true and everything else was false. Now, we use the same set of true and false strings, ints and bools that the Salesforce Data Loader uses. Anything else throws an exception. One additional argument for this open stance is that the "SQLite standard" string representation of True is "1" and False is "0" and in postgres it is "true" and "false".
For command lines: previously it could return True for known-true values, False for known-false values and None for anything else. Of course the "None" was generally interpreted as "False" so, for example, "yes" was "False". Now it uses the same rules as above.
None is considered a known-false value because many tasks are coded that way. I am open to fixing the ones in our control …
> Tighten up handling of boolean in data loads, CLIs and YAMLs.

- cumulusci/cumulusci.yml
- cumulusci/tasks/package_2gp.py
Skipping validation is much faster, and is appropriate for the feature test use case since the ci_feature_2gp flow will test installation and operation of the package. The issues that blocked us from using it before now seem to be resolved. Also, we don't need to specify dependencies when we're skipping validation.
- The `build_feature_test_package` flow now creates a 2gp package version with the "skip validation" option turned on.
> Skip validation for 2gp package versions for feature tests

- cumulusci/tasks/github/merge.py
- cumulusci/tasks/github/tests/test_merge.py
* `github_automerge_main` now only merges to the lowest numbered release branch when multiple are detected.
> Release Branch Fix

- cumulusci/tasks/apex/testrunner.py
Just noticed this option has a particularly unpleasant usage statement due to its long name.
* Improved the usage statement for `required_org_code_coverage_percent` in the `run_tests` task.
> Improve Option Usage Statement

- docs/robotframework.rst
I was experimenting with a different way to do the linking and didn't intend to check it in. This reverts one line of documentation to what it was previously.
> Revert accidental change in previous commit.

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
This avoids accidentally including the "time to upgrade" notice when piping `cci task doc` to docs/tasks.rst to update the generated task docs.
I also changed a few other calls to click.echo where it seemed like stderr would be more appropriate, and removed the "Checking the version!" output which doesn't seem necessary.
> use stderr for outputting some notices

- .pre-commit-config.yaml
This PR adds `rst-lint` to our pre-commit checks. When run with `pre-commit run --all-files` it'll catch the currently broken HISTORY.rst file (and several others).
> Add rst-lint to pre-commit

- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_extract.py
- cumulusci/tasks/bulkdata/tests/test_load.py
Previously: During the load and extract tasks, on Windows 10 if there is an error triggered by a load or extract task, CCI masks the error message by throwing a second error related to cleaning up the temp data that was built for the process.
This should fix it. I'll do tests to checks whether it also fixes `generate_and_load_from_yaml`. Maybe, maybe not
For release notes:
During the load and extract tasks, on Windows 10 if there is an error triggered by a load or extract task, CCI would mask the real error message by throwing a second error related to cleaning up the temp data that was built for the process. Now the real error will be reported correctly.
> Clean up DB connections carefully for Windows.

- cumulusci/tasks/salesforce/Deploy.py
- cumulusci/tasks/salesforce/install_package_version.py
- cumulusci/tasks/salesforce/tests/test_DeployBundles.py
- Fixed a bug where the ``namespace_inject`` option was not included when freezing deploy steps for MetaDeploy, causing namespace injection to not work.
> Fix missing namespace_inject option when freezing deploy task

- cumulusci/tasks/salesforce/custom_settings_wait.py
- cumulusci/tasks/salesforce/tests/test_custom_settings_wait.py
- Fix the `custom_settings_value_wait` task to not throw an exception if a custom settings record doesn't yet exist. Instead it'll continue to query the object until the record exists and the value matches
- Fix the `custom_settings_value_wait` task to not throw an exception if the field api name passed as an option doesn't exactly match the case of the field api name in the object.
> Fix silly bugs in custom_settings_value_wait

- cumulusci/cumulusci.yml
- An experimental `qa_org_2gp` flow is provided in the standard library. This flow uses `config_qa`, meaning that `config_qa` must be tokenized and not include explicit `managed` or `unmanaged` options so that CumulusCI can manage performing the appropriate injection. This flow may change at any time.
- The `ci_feature_2gp` flow has been changed to use `config_apextest` instead of `config_managed`. This means that `config_apextest` must be tokenized and not include explicit `managed` or `unmanaged` options so that CumulusCI can manage performing the appropriate injection.
> 2GP Standard Library

- cumulusci/salesforce_api/package_zip.py
- cumulusci/salesforce_api/tests/test_package_zip.py
- cumulusci/tasks/salesforce/Deploy.py
- cumulusci/tasks/salesforce/tests/test_Deploy.py
This fixes an error which would happen if you run `dev_org` immediately after starting a project with `cci project init`.
- added a condition to avoid running sfdx force:source:convert if the folder is empty
- added a condition to avoid trying to deploy if the package zip is empty (i.e. not even package.xml)
- Fixed the `deploy` task so that deploying an empty metadata directory does not error.
> Don't error on deploy if sfdx folder is empty

- cumulusci/tasks/bulkdata/generate_and_load_data_from_yaml.py
- cumulusci/tasks/bulkdata/mapping_parser.py
Currently Snowfakery uses a feature that is technically deprecated in mapping files. CumulusCI "warns" the user not to use a feature that they didn't mean to use.
https://github.com/SFDO-Tooling/CumulusCI/issues/2093
This is a bit of a hack but doing it "right" is fairly hard with Pydantic and all of the layers of CumulusCI and the hack seems pretty low risk. The correct option would need to be threaded through about 6-8 layers of CumulusCI/Pydantic stack frames.
Also the whole thing should be fixed in a better way some time soon: CumulusCI should support record names in a column rather than just indirected record IDs. Then Snowfakery will just output the record names in an intuitive fashion.
> Issue #2093: Fix confusing warning message about record_types

- cumulusci/tasks/salesforce/EnsureRecordTypes.py
- cumulusci/tasks/salesforce/tests/test_EnsureRecordTypes.py
- Added optional `record_type_description` option that sets the new Record Type's Description.
- If no option is provided, the Description is blank which is the previous behavior.
`ensure_record_types` supports an optional `record_type_description` option that sets the new Record Type's Description if a Record Type is created.    If no option is provided, the Description is blank.
> EnsureRecordTypes supports Record Type Description

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
One can now use --org for commands like `cci org info`, `cci org default`, `cci org remove` etc. This is a usability improvement requested by users on Slack.
One can now pass no org_name to cci org default to print the default.
One can now pass arguments too cci.main and have those arguments go to Click, which is useful in unit testing and generally a good design.
> Cci org name  and cci org default improvements

- cumulusci/utils/xml/metadata_tree.py
- cumulusci/utils/xml/salesforce_encoding.py
- cumulusci/utils/xml/test/test_metadata_tree.py
@bethbrains found a bug whereby the tostring() method would crash due to trying to look up namespace prefixes for a namespace.
This raised the question of whether elements like that should be printed with or without a namespace. I decided to make it a user-option.
> tostring() works for individual elements and parent namespaces can be printed

- cumulusci/cumulusci.yml
* Flows `ci_feature` and `ci_feature_beta_deps` now only run `github_automerge_feature` if the branch begins with the configured feature branch prefix.
> only automerge if the branch is a feature branch

- cumulusci/robotframework/tests/salesforce/api.robot
- cumulusci/tasks/salesforce/Deploy.py
- cumulusci/tasks/salesforce/tests/test_Deploy.py
(I don't love this change, since it will make typos less obvious, but it solves a particular case that is common immediately after initializing a new project when the force-app directory doesn't exist yet. I'd say we should make `cci project init` create the directory, but it's not possible to add an empty directory to git.)
- Running the `deploy` task with the `path` option set to a path that doesn't exist will log a warning instead of raising an error.
> warning instead of error if Deploy path doesn't exist

- cumulusci/cumulusci.yml
- CumulusCI installs beta dependencies when building 2GP feature test and QA orgs.
> Use betas when building 2GP orgs

- cumulusci/tasks/metadata/metadata_map.yml
- cumulusci/tasks/metadata/package.py
- cumulusci/tasks/metadata/tests/test_package.py
- We fixed an issue that caused CumulusCI to generate invalid `package.xml` entries for Metadata API-format projects that include `__mocks__` or `__tests__` LWC directories.
> Fix issue with LWC mocks in update_package_xml

- cumulusci/tasks/salesforce/tests/test_update_dependencies.py
- cumulusci/tasks/salesforce/update_dependencies.py
- Fixed the update_dependencies task to handle automatic injection of namespace prefixes when deploying an unpackaged dependency. The fix for the same issue in cumulusci 3.25.0 was incomplete.
> fix automatic namespace injection for unmanaged dependencies

- cumulusci/core/config/project_config.py
- cumulusci/core/github.py
- cumulusci/core/tests/test_config.py
@davidmreed here's what I had in mind for the error handling. And I moved find_repo_feature_prefix to be a standalone function rather than a ProjectConfig method, since it doesn't use self.
> Suggested adjustments for feature/2gp-dependency-resolution

- cumulusci/core/config/OrgConfig.py
- cumulusci/core/tests/test_config.py
It's possible to encounter a gack while retrieving details about a specific installed package that was found by querying InstalledSubscriberPackage. Let's handle that so that it doesn't get in the way of detecting packages that are not broken.
- Handle a possible gack while collecting info about installed packages
> handle gack while collecting installed packages

- cumulusci/tasks/push/push_api.py
- cumulusci/tasks/push/tasks.py
- cumulusci/tasks/push/tests/test_push_api.py
- cumulusci/tasks/push/tests/test_push_tasks.py
This is an alternative to #2307 which attempts to simply fix the existing memoization rather than switch to a query cache. I switched from our own `memoize` decorator to `functools.lru_cache`. `lru_cache` uses a cache key with an actual reference to the function arguments rather than stringifying them, so I believe it should avoid the problem with cache collisions due to object ids being reused -- both by no longer using the stringified id, and by preventing the object from getting garbage collected, so its id won't be reused.
I think we're still doing more memoization than really makes sense and probably want to revisit that the next time we're doing bigger work on the push tasks, but for now I'm just looking for a quick fix to avoid the flaky tests.
I also removed the …
> Fix flaky push API memoization

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- cumulusci/utils/yaml/cumulusci_yml.py
- cumulusci/utils/yaml/tests/test_cumulusci_yml.py
I was unable to find an attribute on `ScannerError` for the name of the file being parsed.  I included "likely cumulusci.yml" in the error messaging, because we can't be sure which call to `handle_exception()` is being invoked.
* CumulusCI displays more user friendly error message when encountering parsing errors in `cumulusci.yml`.
> Improve yaml parse error handling

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/org_settings.py
- cumulusci/tasks/salesforce/tests/test_org_settings.py
- docs/tasks.rst
- `org_settings` accepts a dict option called `settings` in addition to (or instead of) the existing `definition_file` option.
> Add dict option for org_settings task

- cumulusci/core/tasks.py
- cumulusci/robotframework/CumulusCI.py
CumulusCI uses this global CURRENT_TASK to store a stack of which tasks are currently running, and it uses a threadlocal to make it safe if there are multiple threads each running a different flow. But that wasn't actually working because CURRENT_TASK.stack was only initialized in the main thread, so there was an AttributeError when trying to access it in other threads.
- Fixed a possible error when running CumulusCI flows embedded in a multi-threaded context.
> Fix running a task in a non-main thread

- requirements.txt
(This is the _old_ library for reporting to sentry, and we removed CumulusCI's support for doing that a while back.)
> Remove raven, which hasn't been an actual requirement for some time

- cumulusci/robotframework/locators_51.py
Small spring '21 locator changes. Thanks to Sravani for bringing these to our attention and offering suggested solutions.  Even without these changes our own test suites were passing, but NPSP in spring '21 is using some new markup that was causing a couple of keywords to fail. 
I was unable to find a scenario that would cause our own tests to fail without these fixes, so I haven't added any new test cases. However, our own tests still pass with these changes, and I manually verified that the failing NPSP tests were fixed with these changes. 
* `Click related list button` keyword has been modified to be more liberal in the types of DOM elements it will click on. Prior to this change it only clicked on anchor elements, but now also works for related list buttons that use an actual button …
> A couple small tweaks to locators for Spring '21.

- cumulusci/cumulusci.yml
- cumulusci/tasks/package_2gp.py
- cumulusci/tasks/salesforce/org_settings.py
- cumulusci/tasks/tests/test_package_2gp.py
W-8839087
In addition to the change noted below, this refactors some of the package version number operations into a PackageVersionNumber class instead of methods on the task.
- The `create_package_version` has a new option, `version_base`, which can be used to increment the package version from a different base version instead of the highest existing version of the 2gp package. The `build_feature_test_package` flow now uses this option to create a package version with the minor version incremented from the most recent 1gp release published to github.
> Add version_base option for the 2gp create_package_version task

- cumulusci/tasks/robotframework/robotframework.py
- cumulusci/tasks/robotframework/tests/test_robotframework.py
This fixes a bug that would cause the robot task to crash if you set the robot option 'tagstatexclude' in cumulusci.yml. I added a test case which fails without the fix and passes with.
> Fixed bug related to using tagstatexclude in cumulusci.yml

- cumulusci/tasks/package_2gp.py
- cumulusci/tasks/tests/test_package_2gp.py
- docs/tasks.rst
W-8847899
- The `create_package_version` task now supports setting a post-install script and uninstall script when creating a managed package version, by setting the `post_install_script` and `uninstall_script` options. By default, these options will use the values of `install_class` and `uninstall_class` from the package section of `cumulusci.yml`.
> Set post-install and uninstall script for 2gp managed packages

- cumulusci/tasks/preflight/recordtypes.py
- cumulusci/tasks/preflight/tests/test_recordtypes.py
Fixes a problem in #2371 , missing the use of `query()` instead of `query_all()`.
> query_all instead of query

- docs/cookbook.rst
auth was moved from force to it's own namespace. Even though there is an alias, I was having trouble getting this to run in Github Actions:
SFDX docs: https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_auth_sfdxurl.htm
- remove "force" from "force:auth:sfdxurl:store
> remove "force" from "force:auth:sfdxurl:store

- cumulusci/core/tests/test_sfdx.py
- cumulusci/robotframework/utils.py
- cumulusci/tasks/bulkdata/extract.py
- cumulusci/utils/xml/test/test_salesforce_encoding.py
Some quick coverage improvements.
- Ignore coverage for some code that is only used for testing.
- Remove extract_dataset's _split_batch_csv method which is no longer used
- Use a mock to test both branches of the shell quoting util regardless of actual platform
> quick coverage improvements

- docs/cookbook.rst
- remove delete org step and add `--delete-org` parameter to dev_org flow for Robot Tests Github Action example
> remove delete org step and add `--delete-org` parameter to dev_org flow for Robot Tests Github Action example

- cumulusci/oauth/salesforce.py
- cumulusci/oauth/tests/test_salesforce.py
* Enhanced error messaging on 400 errors encountered when acquiring a JWT session.
Thoughts on mocking `encode()`? I know, I know; bad practice to mock something that really doesn't need to be mocked. But, without an actual dummy key value (i.e. the contents of a genuine server.key file) I wasn't able to get past that method, and it didn't feel right needing to commit private key value somewhere, even if it's just a throwaway.
> Display Response Body on 400 errors

- .github/workflows/release_test.yml
- cumulusci/tasks/salesforce/BaseUninstallMetadata.py
- cumulusci/tasks/salesforce/UninstallPackaged.py
- cumulusci/tasks/salesforce/UninstallPackagedIncremental.py
- cumulusci/tasks/salesforce/tests/test_UninstallPackagedIncremental.py
- The `uninstall_packaged_incremental` and `uninstall_packaged` tasks now support a `dry_run` option, which outputs the destructiveChanges package manifest to the log instead of executing it.
> Add dry_run option to uninstall_packaged_incremental

- docs/unlocked_package.rst
* Content for the `unlocked.rst` section of the docs. The vast majority of this content was from what already existed in `features.rst`.
> Feature/doc reorg  unlocked

- requirements_dev.txt
- utility/build-homebrew.sh
This updates our script for generating a Homebrew formula to install using pip rather than setup.py install. This brings us more in line with how Python packages are typically installed and makes it possible to take advantage of binary wheels (which will be the easiest way to install the newest versions of cryptography).
The script uses the pip-compile tool from pip-tools to build a pip requirements file for cumulusci and its dependencies which includes the sha256 hashes from PyPI. This is embedded in a heredoc in the formula and written out to a requirements.txt file during installation before running pip install.
> Update homebrew formula to install using pip

- utility/build-homebrew.sh
- Update to Python 3.9 (it comes with a newer version of pip which we need in order to be able to install recent binary wheels of the cryptography library)
- Install with `--ignore-installed` so that we don't accidentally try to uninstall packages from the Homebrew python's main site-packages directory. (This fix has already been confirmed in https://github.com/SFDO-Tooling/homebrew-sfdo/issues/103)
> update script for generating the homebrew formula

- cumulusci/cli/cci.py
- cumulusci/cli/tests/test_cci.py
- The `cci org import` command now shows a clearer error message if you try to import an org that is not a locally created scratch org.
> Better error message for org import

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/promote_package_version.py
- cumulusci/tasks/tests/test_promote_package_version.py
* CumulusCI has a new flow for creating production releases of a 2GP managed package: `release_2gp_production`
> New flow: release_2gp_production

- cumulusci/core/utils.py
- cumulusci/robotframework/tests/cumulusci/datagen.robot
- cumulusci/tasks/bulkdata/generate_from_yaml.py
- cumulusci/tasks/bulkdata/mapping_parser.py
- cumulusci/tasks/bulkdata/tests/mapping_v2.yml
- cumulusci/tasks/bulkdata/tests/simple_snowfakery.recipe.yml
- cumulusci/tasks/bulkdata/tests/snowfakery/simple_snowfakery.load.yml
- cumulusci/tasks/bulkdata/tests/snowfakery/simple_snowfakery.recipe.yml
- cumulusci/tasks/bulkdata/tests/snowfakery/simple_snowfakery_2.load.yml
- cumulusci/tasks/bulkdata/tests/test_generate_from_snowfakery_task.py
- cumulusci/tasks/bulkdata/tests/test_mapping_parser.py
- docs/data.rst
- requirements/prod.txt
Changes
Snowfakery can now use "load files" to drive the load process.
Mapping file params like "Serial", "rest, "bulk" are now case-insensitive.
> Snowfakery uses load files

- cumulusci/tasks/robotframework/robotframework.py
- cumulusci/tasks/robotframework/tests/test_robot_parallel.py
- cumulusci/tasks/robotframework/tests/test_robotframework.py
This adds two new robot task options: `ordering` and `testlevelsplit`. Both of these are options that are passed through to pabot when the `processes` option is set higher than 1.  Parallel test runs are still in the experimental stage, but this will give teams a bit more to experiment with.
We don't do anything with these options other than to pass them through, so the only tests I've added assert that the options are part of the pabot command but are ignored for the normal path through the code.
Jason and I had a brief discussion on whether these should be first class options or a layer deeper under a "parallel" or "pabot" option, and we agreed that first class options are the way to go.
test_robotframework.py is getting a bit large so I split out the parallel tests into their own …
> Added "ordering" and "testlevelsplit" options to the robot task

- cumulusci/tasks/salesforce/custom_settings.py
- cumulusci/tasks/salesforce/tests/test_custom_settings.py
W-9089893
- The `load_custom_settings` task now resolves a relative `settings_path` correctly when used in a cross-project flow.
> validate LoadCustomSettings settings_path in _run_task, not _init_options

- cumulusci/robotframework/CumulusCI.py
- cumulusci/robotframework/tests/test_cumulusci_library.py
The robot logger uses .warn but our tasks use .warning. This fix patches the robot logger to have .warning before passing it to the task.
> Fix bug when passing robot logger as the task logger

- cumulusci/cli/service.py
- cumulusci/core/keychain/encrypted_file_project_keychain.py
- cumulusci/core/keychain/tests/test_encrypted_file_project_keychain.py
- Fix `cci service connect` when service isn't configured yet
- Make _read_default_services return an empty dict instead of raising an exception if the default services file doesn't exist yet
> Named service fixes

- cumulusci/core/dependencies/dependencies.py
- cumulusci/core/dependencies/tests/test_dependencies.py
- cumulusci/tasks/package_2gp.py
- cumulusci/tasks/salesforce/tests/test_update_dependencies.py
- Make UnmanagedGitHubRefDependency discard repo_owner and repo_name after converting to github (when both are present, UnmanagedGitHubRefDependency will not deserialize the dependency)
- When a dependency can't be parsed, show it in the error that is raised
Fixes #2564
> Fix serialization of dependencies while making a 1gp release

- cumulusci/core/dependencies/github.py
- cumulusci/utils/yaml/cumulusci_yml.py
- When parsing cumulusci.yml from a github repo, log the repo it came from instead of `<stream>`
- Only show the explanation of cumulusci.yml warnings once even if multiple files have warnings.
- Cache result of get_remote_project_config in an lru_cache so we don't fetch the same file from github multiple times.
- Improved logging of cumulusci.yml warnings from dependencies.
> Improvements to cumulusci.yml warnings

- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/config/util.py
I'm not clear on how this situation arises yet, but we can handle it more gracefully anyway.
- Fixed a regression with creating a scratch org if the devhub service was configured but not set as the default.
> Handle no default devhub service

- cumulusci/salesforce_api/package_zip.py
* Improved logging of errors from sfdx while converting sfdx format metadata to deploy via the Metadata API, so that they are not lost when CumulusCI is embedded in another system like MetaCI or Metecho.
> Log errors in stderr of sfdx commands during source conversion

- cumulusci/tasks/release_notes/task.py
* Remove reference to an obsolete task option. Provide an example of doing an in-place update of an existing parent PR.
> update task docs: `github_parent_pr_notes`

- cumulusci/tasks/github/merge.py
- cumulusci/tasks/github/tests/test_merge.py
This PR restores support for branch prefixes that do not include a forward slash to `github_automerge_main`.
-------
- The `github_automerge_main` task has a new option, `skip_future_releases`, which can be set to False to disable the default behavior of skipping branches that are numeric (and thus considered release branches) but not the lowest number.
- Fixed an error in the github_automerge_main task when using a branch prefix that doesn't contain a slash.
> Add support for branch_prefixes that do not include a slash

- cumulusci/cli/org.py
- cumulusci/cli/tests/test_org.py
@davisagli - Apologies for closing that PR early. Here are the edits you noted.
> use python naming conventions

- cumulusci/tasks/github/publish.py
- cumulusci/tasks/github/tests/test_publish.py
This PR tweaks how `github_copy_subtree` filters filenames based on an an include list. Previously, this task would silently generate incorrect/truncated commits when a directory was included in `self.options.includes` without a trailing slash. Now, it checks the zipfile namelist's directories (filenames ending with a slash) for includes that are missing a slash and appends it.
-------
> Handle directories missing a trailing slash

- cumulusci/tasks/metadeploy.py
Frozen DeployBundles steps were ending up with `github: None`. That was happening here because we were looking up project_config.repo_url on a project_config with no repo_root set after switching to a different working directory. I'm switching to constructing the URL from the repo_owner and repo_name so that we also avoid freezing an ssh-based github URL.
- Fixed a regression in freezing the deploy_pre/deploy_post tasks for MetaDeploy install plans.
> Fix regression in freezing DeployBundles task

- cumulusci/tasks/robotframework/template.html
One of our teams was running `npx prettier` on the generated HTML and it flagged the closing </input> tag as a violation.
In fixing the </input> I also decided to add the doctype and lang metadata.
* improved the output of the robot_libdoc task by removing an unnecessary closing </input> tag, added a doctype, and specified the  language and charset.
> Remove </input> in libdoc template; added doctype and charset

- cumulusci/core/dependencies/dependencies.py
- cumulusci/core/dependencies/tests/test_dependencies.py
#2628 made me realize that we regressed in handling the `skip` key for dependencies specified as a single string rather than a list. The restores the previous support.
- Fixed a regression where the `skip` key for a dependency could no longer be specified as a single string instead of a list.
> fix support for dependency skip as a string

- cumulusci/cli/org.py
- cumulusci/cli/tests/test_org.py
* Fixed a bug in `cci org connect` where the `--sandbox` flag was directing users to login at `login.salesforce.com` instead of `test.salesforce.com`.
I removed the default value on the `--login-url` option so that it will default to None. This will ensure that the auth and token uris are set to the proper values.
> Fix `--sandbox` flag in `cci org connect`

- cumulusci/cli/flow.py
- cumulusci/cli/tests/test_flow.py
* CumulusCI will now remove orgs when the `--delete-org` option is passed to `cci flow run`, even if an error occurs while running the flow.
I may be missing something here so let me know if I'm way off base. Not sure if there's a good reason we had just a `try/finally` block without an `except` clause in there. It looks like we would always display the "flow complete" message even when a flow encountered an error.
> Delete org when error occurs running flow

- cumulusci/cumulusci.yml
* The `release_2gp_beta` flow now sets the `force_upload` option to `True`. This means that a new package version will be created _even if_ there are no changes to the package contents.
* Fixed an issue where the `tag_prefix` option was being used on the wrong task in the `release_2gp_beta` flow.
> Fix: `release_2gp_beta` flow

- utility/push-homebrew.py
`make release-homebrew` wasn't working due to an issue in the `push-homebrew` script.
> Fix GitHub authentication for Homebrew releases

- cumulusci/utils/git.py
- cumulusci/utils/tests/test_git.py
See https://trailblazers.salesforce.com/_ui/core/chatter/groups/GroupProfilePage?g=0F9300000009M9Z&fId=0D54S00000A7GWS&s1oid=00D4S0000019iJX&s1nid=0DB30000000072L&emkind=chatterCommentNotification&s1uid=0053A00000CB68z&emtm=1623793353675&fromEmail=1&s1ext=0
- Fixed an issue where CumulusCI would not find the right GitHub repository if the project was cloned using an ssh URL including an ssh alias instead of github.com.
> Handle github ssh urls even when using an alias for github.com

- cumulusci/tasks/salesforce/install_package_version.py
- cumulusci/tasks/salesforce/tests/test_install_package_version.py
- We fixed an issue where CumulusCI did not correctly convert a package version specified as a number in YAML to a string. This now raises a warning.
> Handle, and warn about, package versions specified as numbers

- cumulusci/oauth/client.py
- cumulusci/oauth/tests/test_client.py
Response objects from `requests` evaluate to False in a boolean context if the status code is >= 400. (Who knew?!) So let's be sure to check if the response is None instead of whether it is falsy -- and update the test to use a real response object since the mock didn't behave the same.
- Fixed a bug where OAuth errors were not reported in detail.
> fix reporting of oauth errors

- cumulusci/core/utils.py
- cumulusci/tasks/bulkdata/generate_from_yaml.py
One module had a comment that is irrelevant now. Deleted.
The other module copied a file from one place to another which left a vestigial file behind. David Glick asked about it in a code review. Instead I move it now and there is no file left behind.
I changed the indentation to make sure that the file was closed before I tried to move it. (probably should not have copied it while it was open!).
> Fix some doc and move rather than copy

- cumulusci/tasks/datadictionary.py
- cumulusci/tasks/tests/test_datadictionary.py
- We fixed issues in the `generate_data_dictionary` task that resulted in failures when processing fields with blank Help Text or processing standard fields.
> Fix two bugs in Data Dictionary

- cumulusci/core/github.py
- cumulusci/tasks/github/commit_status.py
- cumulusci/tasks/github/tests/test_commit_status.py
- Builds that install feature-test 2GP packages now present a cleaner error message when the current commit is not found on GitHub.
> Handle 2GP lookup errors more cleanly

- cumulusci/tasks/datadictionary.py
- cumulusci/tasks/tests/test_datadictionary.py
- The `generate_data_dictionary` task now includes Custom Settings, Custom Metadata Types, and Platform Events.
- The `generate_data_dictionary` task now excludes any schema with visibility set to Protected. This behavior can be turned off (including protected schema) with the `include_protected_schema` option.
- The `generate_data_dictionary` task now parses object and field metadata anywhere in a Salesforce DX release other than in the `unpackaged/` directory tree.
- We fixed an issue preventing `generate_data_dictionary` from working with four-digit (1.0.0.0) 2GP version numbers.
> Feature enhancements for generate_data_dictionary

- requirements/prod.in
- requirements/prod.txt
Snowfakery 2 is the newest version on PyPI, so we don't need to pin anymore.
> Un-pin Snowfakery

- cumulusci/tasks/create_package_version.py
- cumulusci/tasks/tests/test_create_package_version.py
- We fixed an issue causing `release_2gp_beta` to fail to create a GitHub release with a dependency-parsing error.
> Fix create package version dependency output

- CONTRIBUTING.rst
- cumulusci/cumulusci.yml
- cumulusci/tasks/create_package_version.py
- cumulusci/tasks/salesforce/org_settings.py
- cumulusci/tasks/salesforce/tests/test_org_settings.py
- cumulusci/tasks/tests/test_create_package_version.py
- The `create_package_version` task no longer creates Unlocked Packages from the `unpackaged/pre` and `unpackaged/post` directories of dependencies, or local `unpackaged/pre` directories by default. This behavior is now opt-in via the `create_unlocked_dependency_packages` option, which defaults to False. Projects using the old default behavior must explicitly set this option. We believe the new behavior is a more sane default for most 2GP projects.
- The `create_package_version` task now supports `objectSettings` in the org definition file.
> Support objectSettings in create_package_version and change default behavior to not create unlocked packages

- cumulusci/core/keychain/environment_project_keychain.py
- cumulusci/core/keychain/tests/test_environment_project_keychain.py
* Fixed an issue where the the built-in connected app was not accessible when running CumulusCI in a headless environment. (Fixes #2737)
> Built-in connected_app should be the default if no others are present

- cumulusci/tasks/metadata_etl/tests/test_value_sets.py
- cumulusci/tasks/metadata_etl/value_sets.py
* The `add_standard_value_set_entries` task now supports value sets for `LeadStatus`.
These changes came from [PR 2695](https://github.com/SFDO-Tooling/CumulusCI/pull/2695).
> LeadStatus Picklist Support

- cumulusci/tests/pytest_plugins/pytest_sf_vcr.py
Make VCR resilient to API version changes, so we don't have to edit cassettes when versions change.
Nothing to report in release notes.
> Make VCR resilient to version changes.

- .github/workflows/feature_test.yml
Previously, the `lint` job compared HEAD against origin/main on every push, but that didn't necessarily match the context; you could, for example, be in a child branch. Ultimately, it made the most sense for this to be triggered by the pull_request event instead.
This PR also changes the events triggering the feature test workflow to one of the following:
1. Manual runs:
gh workflow run feature_test.yml
2. Pull requests
3. Commits to `main`
Failing workflow [here](https://github.com/SFDO-Tooling/CumulusCI/pull/2772/checks?check_run_id=3225142344).
---
> Fix lint workflow

- cumulusci/cumulusci.yml
- cumulusci/tasks/metadata_etl/layouts.py
- docs/metadata_etl.rst
Added new metadata etl feature to layouts.py that enables user to add or move fields to a specified Page Layout section.  Note - if a field is labeled as Required or Read-Only in Section A, and user runs task to move to Section B, it will lose those field properties.
> Add add_page_layout_fields Metadata ETL task

- cumulusci/core/config/project_config.py
- cumulusci/core/config/tests/test_config.py
- cumulusci/cumulusci.yml
- cumulusci/tasks/github/publish.py
- cumulusci/tasks/github/release.py
- cumulusci/tasks/github/tests/test_publish.py
- cumulusci/tasks/github/tests/test_release.py
* The `github_release` task now requires the `tag_prefix` option to be passed.
* The `github_copy_subtree` task now requires a `tag_name` option to be passed, and the `version` option has been deprecated.
* Fixed an issue where GitHub tags for 2GP package would always include the "release" prefix (even for Beta packages).
* @jstvz - We're reworking the `project_config.get_tag_for_version()` method to require both a `tag_prefix` and a `version`. The `PublishSubtree` class is the only other place where this method is referenced but is currently not passing a prefix.  I don't know too much about this task; is there a way we can derive which tag prefix to use—either `beta/` or `release/`—based on the the value of the `create_release` option? If not, is there another way we can infer what …
> Fix tag prefix and name inconsistencies

- cumulusci/core/config/project_config.py
- cumulusci/core/config/tests/test_config.py
- We fixed an issue causing 2GP commit-status builds to fail when the local Git repository has a detached HEAD (fixes #2801).
> Get commit sha when in detached HEAD

- docs/dev.rst
Adding docs for the `password_env_name` key for dependencies.
> Add docs for password_env_name

- .github/ISSUE_TEMPLATE/bug_report.yml
Github's form schema treats the `checkbox` type as a tasklist. Since the
intention is to allow the user to select more than one environment we should use a dropdown and give the user the _option_ to select more than one option.
> Don't use checkboxes in bug issue form

- cumulusci/cli/error.py
- cumulusci/cli/tests/test_error.py
* The `--max-lines` option on the `cci error info` command has been deprecated.
> remove max-lines option

- cumulusci/tasks/push/tasks.py
- cumulusci/utils/yaml/cumulusci_yml.py
The modification PR #2837 to allow 2GP push upgrades via `push_list` included validation, this introduced a bug because the init options method was already setting `namespace` as default. The validation is not needed because when `metadata_package_id` is present is takes precedence over `namespace`. 
Also added `metadata_package_id` as an available option in project config
- We fixed a regression in the `push_list` task that affected 2GP push upgrades
> Remove bugged task option validation in `push_list`

- cumulusci/cli/logger.py
* Fixes an issue where a log handler wasn't being properly applied to `urllib3` when the `--debug` flag is passed.
> fix log handler for urllib3

- cumulusci/cli/org.py
(to handle orgs like the one discussed in https://salesforce-internal.slack.com/archives/C024ZJ3JYTW/p1636479495076100)
- Adjusted a check for .lightning. domains in the `cci org connect` command.
> Generalize the warning for trying to connect an org with a .lightning. domain

- cumulusci/cli/tests/test_utils.py
- cumulusci/cli/utils.py
Python versions less than 3.8 now give a warning.
"Sorry! Your Python version is not supported. Please upgrade to Python 3.9."
> Add version check

- cumulusci/tasks/bulkdata/tests/test_snowfakery.py
Fix a race condition in test framework
The old code mutated the "last" mock call. If two threads create mock calls at the same time, the data got attached to the wrong call.
```
self.return_values = {"step_results": next(return_values)}
rc = __call__.mock(*args, **kwargs)
values_loaded = db_values_from_db_url(self.options["database_url"])
__call__.mock.mock_calls[-1].values_loaded = values_loaded
```
The new code is more "functional" style: no mutations or dependence on shared variables.
```
values_loaded = db_values_from_db_url(self.options["database_url"])
kwargs = {**kwargs, "values_loaded": values_loaded}
rc = __call__.mock(*args, **kwargs)
```
The other changes are side effects of this change.
> Fix race condition in test framework

- cumulusci/robotframework/Salesforce.py
- cumulusci/robotframework/tests/salesforce/api.robot
- docs/robot/Keywords.html
This lets you spread a SOQL query across multiple rows in the `SOQL Query` keyword. 
Fixes W-10244357
* queries passed to the `SOQL Query` keyword can now span multiple lines.
> Allow `SOQL Query` keyword to accept queries that span multiple lines

- readthedocs.yml
* The CumulusCI repo now includes a `readthedocs.yml` file for configuring builds in readthedocs.
> Use Python > 3.7  for readthedoc builds

- cumulusci/cli/task.py
- cumulusci/cli/tests/test_task.py
* Fixed an issue where the `--json` flag was not outputting properly formatted `JSON` with the `cci task list` command.
> Fix `cci task list --json`

- cumulusci/core/utils.py
(nothing for Release notes in this PR)
A recent change to `process_list_arg` will probably output annoying warnings that the user does not have control over, if the person who wrote the task wrote:
process_list_arg(self.options.get("FOO"))
instead of
process_list_arg(self.options.get("FOO", []))
This skips the warning message in the former case.
Some might argue that process_list_arg should always return a list or throw an exception, but that behaviour would not be backwards compatible, so this is better.
> Better backwards compatible behaviour for some places it is called.

- cumulusci/core/flowrunner.py
- cumulusci/core/tests/test_flowrunner.py
- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/tests/test_metadeploy.py
- We fixed an issue preventing step-level preflight checks from working correctly in MetaDeploy when run as a cross-project flow.
- The `metadeploy_publish` task now displays a clear error message if you supply the wrong API URL.
> Make cross-project step preflights work

- cumulusci/cli/service.py
- cumulusci/cli/tests/test_service.py
- `cci service default --project` presents a better error message when called outside of a project.
> Raise UsageError if project default set outside project directory

- cumulusci/tasks/release_notes/task.py
- cumulusci/tasks/release_notes/tests/test_task.py
- The `github_parent_pr_notes` now handles child PRs with an empty `body`.
> Allow release_notes to process PRs with empty body

- cumulusci/core/config/BaseConfig.py
- cumulusci/core/config/BaseTaskFlowConfig.py
- cumulusci/core/config/OrgConfig.py
- cumulusci/core/config/ScratchOrgConfig.py
- cumulusci/core/config/tests/_test_config_backwards_compatibility.py
- cumulusci/core/config/tests/test_config_expensive.py
Nothing for release notes:
Make backwards compatible shims for OrgConfig stuff.
> Add backwards-compatible files and warnings for OrgConfig rename

- cumulusci/cumulusci.yml
- cumulusci/tasks/marketing_cloud/get_user_info.py
- cumulusci/tasks/marketing_cloud/mc_constants.py
- cumulusci/tasks/marketing_cloud/tests/conftest.py
- cumulusci/tasks/marketing_cloud/tests/test_api.py
- cumulusci/tasks/marketing_cloud/tests/test_get_user_info.py
* A new task is available for getting user information from the Marketing Cloud REST API `/userinfo` endpoint: `marketing_cloud_get_user_info`.
* Created a new `mc_constants.py` file for shared constants across MC files.
* Refactored a couple of pytest fixtures into a mc specific `conftest.py`.
> Marketing Cloud: Get User Info Task

- cumulusci/salesforce_api/mc_soap_envelopes.py
- cumulusci/tasks/marketing_cloud/api.py
- cumulusci/tasks/marketing_cloud/base.py
- cumulusci/tasks/marketing_cloud/tests/test_api.py
* The `marketing_cloud_create_user` task now creates an unlocked user with a notification email address so that it is possible for the user to log in. This task also has a new option, `activate_if_existing`, which can be set to True to ensure that if the user already exists in an inactive state, it will be activated.
> Adjust marketing_cloud_create_user task

- cumulusci/tasks/bulkdata/tests/test_snowfakery.py
- cumulusci/utils/tests/test_org_schema.py
Skip one test temporarily and clean-up a warning in another. Not for release notes.
> Skip one test temporarily and clean-up a warning.

- cumulusci/tasks/bulkdata/snowfakery_utils/snowfakery_working_directory.py
- cumulusci/tasks/bulkdata/snowfakery_utils/subtask_configurator.py
Snowfakery's Unique ID feature depends upon a parent process passing a uniquifying "context identifier" called a "pid" (because it is the ID for this Snowfakery process).
I dug into why the test case didn't catch the problem but the fix for the test is larger and I don't want to slow down this PR, but I'm working on a separate PR to fix that.
The old code was here:
https://github.com/SFDO-Tooling/CumulusCI/blob/f6777e673eca9978a84f70af365835d307885abb/cumulusci/tasks/bulkdata/snowfakery.py#L498
> Fix Snowfakery's Unique ID feature

- cumulusci/tasks/marketing_cloud/deploy.py
- cumulusci/tasks/marketing_cloud/get_user_info.py
- cumulusci/tasks/marketing_cloud/tests/test_deploy.py
- cumulusci/tasks/marketing_cloud/tests/test_util.py
- cumulusci/tasks/marketing_cloud/util.py
* The `deploy_marketing_cloud_package` task now utilizes the new API endpoint for deployments.
Per a discussion I had with Sam Varga, all stacks should now be swapped over to using these new endpoints:
> All stacks are live now from our side. The MC R2 release actually got pushed back to the 18th, but with your server-side integration that doesn't matter. That's only for the UI oauth flow endpoints.
I have tested and confirmed the deploy task works with the new endpoints for our learning account which resides on S4.
> Switch mc package deploy task to new endpoints

- cumulusci/tasks/bulkdata/snowfakery_utils/queue_manager.py
- cumulusci/tasks/bulkdata/tests/test_snowfakery.py
- cumulusci/utils/parallel/task_worker_queues/parallel_worker.py
- cumulusci/utils/parallel/task_worker_queues/parallel_worker_queue.py
- cumulusci/utils/parallel/task_worker_queues/tests/test_parallel_worker.py
Fix a bug where too few records are processed due to a race condition where files are moved around while the controller process is looking at them.
Use a lock to avoid that. My previous solution to this problem had performance consequences.
Thousands of iterations of the flaky test have been run.
> Fix test by removing filesystem-related race conditioon

- docs/robot.rst
- docs/robot_locators.rst
Added a new section to our public documentation about managing locators. If you build it locally, go to the section on robot on the left-hand side and you should see a new section titled "Managing Locators".
I've attached a [rendered pdf](https://github.com/SFDO-Tooling/CumulusCI/files/8075547/Managing.Locators.pdf) of this one page just in case it helps in the initial review.
* New section in our documentation about managing robot framework locators
> New section of robot docs: Managing Locators

- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/mapping_parser.py
- cumulusci/tasks/bulkdata/tests/test_extract.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/test_mapping_parser.py
- cumulusci/tasks/bulkdata/tests/utils.py
- cumulusci/tests/util.py
1. Don't pass org_config to mapping_parser functions. Pass salesforce_client instead. The only reason they need an org_config is for the salesforce_client, and passing in an existing one is cleaner, more performant and easier to mock.
2. Start the process of centralizing the "preferred" Salesforce version for test cases in a single place.
Nothing relevant to release notes.
> Code cleanups: remove org_config in MP and sf_version

- cumulusci/tasks/bulkdata/tests/Contact.json
- cumulusci/tasks/bulkdata/tests/test_step.py
- cumulusci/tasks/bulkdata/tests/test_utils.py
- cumulusci/tasks/bulkdata/tests/utils.py
- cumulusci/tests/pytest_plugins/pytest_sf_orgconnect.py
- cumulusci/tests/util.py
Nothing for Release Notes.
Contact.json was prettied.
CURRENT_SF_API_VERSION was moved from one file to another.
CURRENT_SF_API_VERSION was used in more places than before.
An unused, second copy of `mock_describe_calls` was deleted.
`mock_describe_calls` is now versionable.
> Bulk Test Cleanups - Part 2

- cumulusci/core/keychain/subprocess_keychain.py
- cumulusci/tasks/bulkdata/snowfakery_utils/queue_manager.py
- cumulusci/tests/util.py
- cumulusci/utils/parallel/task_worker_queues/parallel_worker.py
- cumulusci/utils/parallel/task_worker_queues/tests/test_parallel_worker.py
Snowfakery had a bug introduced when the get_service calling code changed in 40520bee4c1c .
This PR changes the method signature for SubprocessKeyChain.get_service()
It's hard to replicate in integration tests because it depends on a connected app-based org_config as opposed to the sfd-based org_config
W-10811651
Fixed a bug running the `snowfakery` task in parallel mode with orgs connected using a Connected App.
> Snowfakery crash when loading into "directly connected" ("persistent") orgs

- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_upsert.py
- datasets/upsert/upsert_before_data.sql
- datasets/upsert/upsert_example_2.sql
- datasets/upsert/upsert_mapping_bulk.yml
- datasets/upsert/upsert_mapping_rest.yml
- docs/data.rst
Allow lookup references to objects inserted or updated in upserts.
Nothing for release notes, assuming this ships with the same version as the rest of the Upsert feature. It merely removes a limitation in that feature.
> Allow references in upserts

- .github/workflows/feature_test.yml
Refactors the robot_ui_* jobs to use a matrix in the same way that unit_test does.
Another change could be to use sfdx via actions/setup-node, using caching to shave a few seconds from its installation step.
> Consolidate robot_ui jobs

- cumulusci/utils/http/requests_utils.py
[update to #3114; no additional release note needed]
> Load certs from the mac keychain but don't use securetransport

- requirements/dev.in
- requirements/dev.txt
- requirements/prod.txt
Several major/minor updates, but no breaking changes listed for any of: `pytz`, `rich`, `authlib`, `readme-renderer`, `wrapt`, `pytest`.
> week 12 updates

- .github/workflows/chores.yml
- .github/workflows/release.yml
- .github/workflows/release_test.yml
Add a new workflow 'chores' containing two jobs:
- `check_api_versions`: polls the sfdo devhub for the latest API
version, then stores that and the current default version from
`cumulusci/cumulusci.yml` in its output.
- `update_api_versions`: if the outputs for the check job do not match,
writes the new version to `cumulusci/cumulusci.yml`, commits, pushes,
and creates a PR with those changes.
This job is scheduled to run Sundays at 00:00 UTC.
In addition, the `release_test` workflow now
- is not triggered on every push to feature branches
- may be manually run
- is triggered from the "Release cumulusci" workflow when `version.txt` is included in a `push` event
> Add automated api version updates via Github Actions

- .github/workflows/release.yml
In order to use `@,` we must specify the full path, i.e. `Owner/Repo/.github/...`. However, in the `./.github/...` syntax `main` is implied.
-------
> fix: remove version spec from local workflow call

- cumulusci/tasks/bulkdata/extract.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_extract.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/test_utils.py
- cumulusci/tasks/bulkdata/utils.py
In upcoming work I'm doing, I'm trying to reduce our dependence on LoadData methods and use more helper functions 
My functions require certain helper features to be available as functions, not methods.
The methods remain in place for backwards compatibility, but I could also rewrite code to use them instead of the Mixin methods if that's the consensus.
Note that a reference to session.flush() was removed but I believe it was extraneous to start with.
> Refactor two bulkdata utils as functions

- cumulusci/robotframework/Salesforce.py
- cumulusci/robotframework/form_handlers.py
- cumulusci/robotframework/locators_54.py
- cumulusci/robotframework/tests/salesforce/forms.robot
- docs/robot/Keywords.html
This adds support for lightning radiobuttons in the robot keyword `input form data`.  
There's one new test in forms.robot that sets and verifies a lightning button. 
* added support for lightning radiobuttons in the robot keyword `input form data`
> Support lightning radiobuttons

- cumulusci/core/tests/test_utils_merge_config.py
- cumulusci/core/utils.py
* Fixed an issue where CumulusCI was incorrectly merging task option overrides.
I used the following in the standard lib while testing:
```
official_testing_flow:
group: foo
description: Does some stuff
steps:
1:
task: util_sleep
2:
task: util_sleep
3:
task: util_sleep
```
Then I modified the project `cumulusci.yml` to include:
```
flows:
official_testing_flow:
steps:
1:
options:
seconds: 1
```
* Also verified setting the flow step to a value of `None` still works.
> link missing task or flow when merging configs

- requirements/dev.txt
- requirements/prod.in
- requirements/prod.txt
* [twine](https://twine.readthedocs.io/en/stable/changelog.html) 4.0.0 is dropping support for py 3.6
* Pinning`robotframework<5` until @boakley can get back to verify that we're ok to move to v5+
> Week 14 Updates

- .github/workflows/release.yml
- .github/workflows/release_test.yml
When we made the release test reuseable we missed that secrets need to
be defined in the workflow_call defn. [docs]
[docs]: https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
-------
> Pass secrets into release_test

- .github/workflows/feature_test.yml
- .github/workflows/release_test.yml
First guess was to pin pip to 22.0.4, but I wondered: What exactly is
pip-sync doing here? There's no virtualenv to synchronize since we get a
fresh environment in each workflow run.
> Workaround for pip-tools issue upstream

- cumulusci/core/config/base_config.py
- cumulusci/core/config/tests/test_config.py
* Fixed an issue causing flows that reference properties of the `$project_config` object to fail.
> Fix property lookups on config objects

- cumulusci/core/dependencies/dependencies.py
- cumulusci/core/dependencies/resolvers.py
- cumulusci/core/dependencies/tests/test_resolvers.py
- cumulusci/core/github.py
- cumulusci/cumulusci.yml
- cumulusci/salesforce_api/package_install.py
- cumulusci/schema/cumulusci.jsonschema.json
- cumulusci/utils/yaml/cumulusci_yml.py
- We added a new dependency resolution strategy, `unlocked`. Like our existing dependency strategies using parallel 2GP package builds, this strategy installs parallel unlocked package builds.
- We added the flows `build_unlocked_test_package`, `install_unlocked_commit`, and `qa_org_unlocked` to support use of parallel unlocked packages.
> Unlocked resolution strategy and supporting flows

- .github/PULL_REQUEST_TEMPLATE.md
- .github/releases.yml
- CONTRIBUTING.rst
- docs/contributing.rst
This PR would change how we generate release notes. Instead of manually collating PRs since the previous release, we can use GitHub's autogenerated release notes feature.
Using the configuration file in this PR, we would now use a label instead of the PR template. Mappings:
1. Critical Changes ↦ `critical-changes`
2. Changes ↦ `enhancements`
3. Issues Fixed ↦ `bug`
4. Use `ignore-for-release` to ignore the PR
Notes could then be generated before a release via:
```shell
$ gh api \
--method POST \
-H "Accept: application/vnd.github.v3+json" \
/repos/SFDO-Tooling/CumulusCI/releases/generate-notes \
-f tag_name='v3.58.1' -f target_commitish='main' -f previous_tag_name='v3.58.0' |
jq .body -r |
sed 's/\(https.*\/\)\([0-9]\{4\}\)$/[#\2](\1\2)/' |
pandoc -f gfm -t rst
```
Output with the default …
> Add release notes configuration

- cumulusci/salesforce_api/org_schema.py
- cumulusci/salesforce_api/org_schema_models.py
- cumulusci/tasks/bulkdata/load.py
- cumulusci/utils/http/multi_request.py
- cumulusci/utils/tests/cassettes/ManualEditTestDescribeOrg.test_minimal_schema.yaml
- cumulusci/utils/tests/test_org_schema.py
If a consumer of the org_schema cache needs only a few objects, they can now download info about just those few objects. If a later consumer needs others, it will fill out the database with what it needs (or everything).
Shaves 4 seconds off of `load` tasks, for example.
Some other benchmarks: 
1. empty org.
```
With Cleared cache, 1 obj 0.7929778099060059
Verify 1 obj fresh 0.5295290946960449
With Cleared cache, all objects 10.970187187194824
Verify 1 obj fresh on full cache 1.1063191890716553
Verify all objs fresh 4.084507942199707
```
2. Giant-metadata org first time (server cache is probably cold)
```
With Cleared cache, 1 obj 12.726238012313843
Verify 1 obj fresh 0.5373942852020264
With Cleared cache, all objects 508.0563840866089
Verify 1 obj fresh on full cache 2.6867473125457764 …
```
> Allow org_schema consumers to download a subset

- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/tests/test_metadeploy.py
When running metadeploy_publish, users received an error from the REST
API:
```
Error: b'{"supported_orgs":["\\"persistent\\" is not a valid choice."]}'
```
because the Plan.supported_orgs field in MDP is case-sensitive. We
switch to title case on client-side in this PR.
> Fix `metadeploy_publish` error caused by supported_orgs case-sensitivity

- cumulusci/cli/tests/test_plan.py
- cumulusci/core/metadeploy/tests/test_api.py
- cumulusci/tasks/tests/test_metadeploy.py
- pyproject.toml
Allows running the subset of MetaDeploy-related unit tests via:
```console
$ pytest -m metadeploy
```
> Mark MetaDeploy REST API tests

- cumulusci/cli/tests/test_plan.py
- cumulusci/core/metadeploy/api.py
- cumulusci/core/metadeploy/tests/test_api.py
- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/tests/test_metadeploy.py
- pyproject.toml
`make_api_session`:
- Extract the logic for setting the base URL into a subclass of
requests.Session. This allows:
- Read the api url and auth token directly from the ServiceConfig,
- Automatically prepend base_url and set auth token,
- First step in allowing calls from outside the task.
`MetaDeployApi`:
- Interface for the MetaDeploy REST API.
Tests for `metadeploy_publish` are left intact to keep them in place
as integration tests.
> Extract MetaDeploy API from publish task

- cumulusci/files/templates/project/dot-gitignore
We previously didn't include the `.sf` directory in our gitignore
template, which resulted in git tracking it. Because `.sf` includes the
git_dir used in source tracking this resulted in a large number of
changes that users did not expect.
Because our copy of the gitignore is pretty old, it didn't include any
of the entries included in the skeleton generated by `sfdx
force:project:create`.
We now inline the contents of the upstream template [source] in our own.
[source]: https://github.com/forcedotcom/salesforcedx-templates/blob/main/packages/templates/src/templates/project/gitignore
> Include default SFDX gitignore files

- pyproject.toml
1. We don't need to know about every `invalid escape sequence` in every library.
2. We added `ClassMovedWarning` in #3250, but we only throw an error in the integration tests, so we add it here.
> Suppress third-party warnings and error on `ClassMovedWarning`

- cumulusci/schema/cumulusci.jsonschema.json
- cumulusci/utils/yaml/cumulusci_yml.py
- cumulusci/utils/yaml/tests/test_cumulusci_yml.py
Validate that MetaDeploy plans only specify a single primary and secondary plan.
Because `plan.tier` defaults to `primary` in the API, we set the same here, with the expectation that users that do not explicitly set `tier` will see these warnings before plan validation is enforced by `cci plan publish`.
Other callers can validate project_configs with:
```python
with pytest.raises(ValueError, match='Only one plan'):
CumulusCIRoot.validate_plan_tiers(plans_with_multiple_primary)
```
> Validate MetaDeploy plans in cumulusci.yml

- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- datasets/sample.sql
Fix two issues which prevented the `set_recently_viewed` feature from working, and add better testing.
Recreating the issues by hand is roughly a 4 step process:
1. Delete the appropriate org_cache in the .cci directory. (or create a new org so it has no client-side cache)
2. Recreate the cache incompletely e.g. by using a mapping file with Account and Contact but not Opportunity.
3. Try again with a mapping file that uses an extra object like Opportunity.
4. Look closely at the warnings in the log for a warning about set_viewed.
All of these steps are automated like this:
`
git fetch && git branch -D temp-test-bug; git switch -c temp-test-bug origin/main && git cherry-pick cf35fee5d2648b2c9487fac445c0e056a1fc0622 && pytest -k test_recreate_set_recent_bug --org qa
`
Whereas this one …
> Fix `load_dataset` `set_recently_viewed` feature

- cumulusci/core/github.py
- cumulusci/core/tests/test_github.py
Github3.py sets `session.base_url` to `f'http(s)://{hostname}/api/v3` for GitHubEnterprise sessions, so `build_url` returns the wrong GraphQL endpoint. This results in an inscrutable `KeyError` when accessing the query results. This commit removes the suffix and manually constructs the URL.
> Fix get_latest_prerelease on github enterprise

- cumulusci/core/metadeploy/api.py
- cumulusci/core/metadeploy/labels.py
- cumulusci/core/metadeploy/models.py
- cumulusci/core/metadeploy/tests/conftest.py
- cumulusci/core/metadeploy/tests/test_api.py
- cumulusci/core/metadeploy/tests/test_labels.py
- cumulusci/core/metadeploy/tests/test_models.py
- cumulusci/core/metadeploy/tests/test_plans.py
- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/tests/test_metadeploy.py
This PR adds:
- Pydantic models to represent entities consumed or
returned by the MetaDeploy (MDP) REST API. These were not autogenerated from the API schema, however, because of the logic needed to handle mapping enums/choices from CumulusCI to MDP, as well as the generation of translation labels.
- a submodule containing functions for processing translation labels. Direct translation of the existing logic from the `metadeploy_publish` task, with those tests left in place as integration tests.
> Add MetaDeploy data models

- cumulusci/core/github.py
- cumulusci/core/tests/test_github.py
Under certain circumstances then authorizing to GitHub Enterprise servers a retry loop will run until retries are exhausted.
The retry loop can take about 4-5 minutes, and this change looks for known SSL verification issues to bypass the loop.
> GitHub enterprise support : bypass retry ssl errors

- cumulusci/tasks/metadeploy.py
- cumulusci/tasks/tests/test_metadeploy.py
- cumulusci/utils/yaml/cumulusci_yml.py
- cumulusci/utils/yaml/tests/test_cumulusci_yml.py
Plans are published in a deterministic order: sorted by tier, and then by the order they appear in the `cumulusci.yml` file.
Clarified error message that appears when a user tries to include more than one primary or more than one secondary Plan in their `cumulusci.yml` file.
> Publish MetaDeploy plans in a deterministic order

- cumulusci/tasks/metadata/package.py
- cumulusci/utils/xml/metadata_tree.py
Fix #3322 and hopefully a few more similar situations.
> Fix crash with unusual Unicode characters in metadata on Windows running `update_package_xml`

- utility/build-homebrew.sh
Users were intermittently reporting that upgrades failed with some
variation of the following error:
```python-traceback
File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
exec(compile(code, __file__, 'exec'), locals())
File "setup.py", line 14, in <module>
from setuptools_rust import RustExtension
File "/private/tmp/pip-build-env-gh8ot2a3/overlay/lib/python3.8/site-packages/setuptools_rust/__init__.py", line 1, in <module>
from .build import build_rust
File "/private/tmp/pip-build-env-gh8ot2a3/overlay/lib/python3.8/site-packages/setuptools_rust/build.py", line 23, in <module>
from setuptools.command.build import build as CommandBuild  # type: ignore[import] …
```
> Specify Python minor version in homebrew formula

- cumulusci/cli/tests/test_cci.py
After this change, our test cases do not need Internet access to run.
> Allow test cases to run offline

- cumulusci/tasks/metadata/metadata_map.yml
* CumulusCI now supports the following types from [Net Zero Cloud's Tooling API](https://developer.salesforce.com/docs/atlas.en-us.netzero_cloud_dev_guide.meta/netzero_cloud_dev_guide/netzero_cloud_tooling_api_parent.htm): `BldgEnrgyIntensityCnfg`, `StnryAssetEnvSrcCnfg`, `VehicleAssetEmssnSrcCnfg`.
> Include net zero cloud tooling objects in metadata_map

- cumulusci/tasks/github/tests/test_util.py
- cumulusci/tasks/github/util.py
Users have reported 502 errors (i.e., timeouts) when using CommitDir to create a commit when the repository is above a certain size. Because CommitDir uses GitHub's [Git Database API] directly to create blob and tree objects before authoring a commit, it made too many calls and triggered rate limiting. For very large repositories (e.g., NPSP), even very small changes will throw an exception because CommitDir constructs the entire Tree and creates a blob for each file that is new or modified.
This PR resolves this issue with two changes:
1. CommitDir now creates a smaller tree object by omitting unchanged files. By using the `parent_tree` property in the `create_tree` request, we only need to include the blobs that are new, modified, or deleted, meaning the overall tree is much smaller.
2. …
> Use parent_tree in CommitDir  to fix timeouts with large repositories

- cumulusci/cumulusci.yml
- cumulusci/tasks/bulkdata/load.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/utils.py
- cumulusci/tasks/tests/test_metadeploy.py
- docs/data.md
If `load_dataset` is called without any path options, it will automatically use a dataset that matches the org shape, if one exists. For example, a `dev` org will automatically use a dataset that exists at `datasets/dev/`. Within that folder, two files must exist, also matching the org shape name: `dev.mapping.yml` and `dev.dataset.sql`, in this example. If the directory or files do not exist and no paths options were specified, the task will look for `datasets/mapping.yml` and `datasets/dataset.sql` by default. When the `org_shape_match_only` option is `True`, this overrides any path options and default files and looks _only_ for a dataset directory that matches the org shape name. The `org_shape_match_only` option defaults to `False`.
In addition, `load_dataset` is included in …
> Auto-load dataset matching org shape name

- cumulusci/core/source_transforms/tests/test_transforms.py
- cumulusci/core/source_transforms/transforms.py
- cumulusci/salesforce_api/package_zip.py
- cumulusci/tasks/salesforce/Deploy.py
- cumulusci/tasks/salesforce/tests/test_Deploy.py
- docs/config.md
- docs/deploy.md
This PR makes significant changes to the structure of the `deploy` task to provide additional automation capabilities that support flexible source transforms during the deployment operation.
Previously, `deploy` ran a sequence of four transformations on source before sending it to the platform: namespace injection; static resource bundling; meta-XML cleaning; and cleaning of FeatureParameter metadata for Unlocked Packages. Additional transformations, such as `package.xml` updating, replacement of tokens other than namespace tokens, such as `//cumulusci-deprecated` and user-defined replacements, are done out-of-band by mutating the working directory. This situation is undesirable for a number of reasons.
This PR refactors `deploy` to create a pipeline of transforms that run on the …
> Refactor `deploy` to support complex source transformations

- cumulusci/tests/test_utils.py
- cumulusci/utils/__init__.py
* Replacing brew update messaging with a deprecation
* CumulusCI will no longer be supporting installations via `brew`. See [our docs](https://cumulusci.readthedocs.io/en/latest/get-started.html#install-cumulusci) for the officially supported install method via `pipx`.
> Remove references to brew

- cumulusci/tasks/metadata/metadata_map.yml
Steps to reproduce with `dreamhouse-lwc`:
1. In a scratch org (`v55.0`), create a custom field with "External ID" checked
2. Run `cci task run retrieve_changes` against that org, retrieving a `CustomField` and `CustomIndex`.
3. Run `cci flow run dev_org --org`
Fixes #3381.
> Add support for CustomIndex metadata type

- cumulusci/tasks/metadata/metadata_map.yml
* We now support the `Territory2`, `Territory2Model`, `Territory2Type`, and `Territory2Rule` MetaData types.
> Include `Territory2` related md types

- cumulusci/tasks/marketing_cloud/deploy.py
* The `deploy_marketing_cloud_package` task will now output the constructed payload sent to Marketing Cloud when the `--debug` flag is passed.
> The deploy_marketing_cloud_package task will now output the constructed payload sent to Marketing Cloud when the --debug flag is passed.

- .github/workflows/feature_test.yml
- cumulusci/cli/tests/test_cci.py
- cumulusci/core/config/tests/test_config.py
- cumulusci/core/config/tests/test_config_expensive.py
- cumulusci/tasks/apex/tests/test_apex_tasks.py
- cumulusci/tasks/bulkdata/tests/test_upsert.py
- cumulusci/tasks/salesforce/tests/test_base_tasks.py
- cumulusci/tasks/salesforce/tests/test_network_member_group.py
- cumulusci/tasks/salesforce/tests/util.py
- cumulusci/tasks/tests/test_salesforce.py
- cumulusci/tests/util.py
Adds 3.11 to feature test workflows and includes the following changes to get them to pass:
- Update enum assert for 3.11
The behavior of string enums has changed in 3.11 [what's new]:
> Changed Enum.__format__() (the default for format(), str.format() and
> f-strings) of enums with mixed-in types (e.g. int, str) to also include
> the class name in the output, not just the member’s key. This matches
> the existing behavior of enum.Enum.__str__(), returning e.g.
> 'AnEnum.MEMBER' for an enum AnEnum(str, Enum) instead of just 'MEMBER'.
- Update create_task_fixture for 3.11
Python 3.11 removed pathlib._Accessor in python/cpython#25701. This
broke our patch when it replaced a call to `os.getcwd()` with
`Path.cwd()` in `Path.absolute()`. As a classmethod `Path.cwd()`
receives the class as its …
> Fix unit tests on Python 3.11

- cumulusci/tasks/metadata/package.py
- cumulusci/tasks/metadata/tests/package_metadata/namespaced_report_folder/package_install_uninstall.xml
- cumulusci/tasks/metadata/tests/test_package.py
Validation Runs
Passing **install_class** on cli
```
cci task run update_package_xml --path ../via_core --managed True --install_class MyInstallClass
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
<fullName>CumulusCI</fullName>
<postInstallClass>MyInstallClass</postInstallClass>
<version>55.0</version>
</Package>
```
Passing **install_class** and **uninstall_class**
```
cci task run update_package_xml --path ../via_core --managed True --install_class MyInstallClass --uninstall_class MyUnInstallClass
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
<fullName>CumulusCI</fullName>
<postInstallClass>MyInstallClass</postInstallClass>
<uninstallClass>MyUnInstallClass</uninstallClass> …
```
> W-12077732: Pass in install class and uninstall class names from cli

- cumulusci/core/datasets.py
- cumulusci/core/tests/test_datasets_e2e.py
- cumulusci/salesforce_api/org_schema.py
- cumulusci/salesforce_api/org_schema_models.py
- cumulusci/tasks/bulkdata/extract_dataset_utils/synthesize_extract_declarations.py
- cumulusci/tasks/bulkdata/extract_dataset_utils/tests/test_synthesize_extract_declarations.py
- cumulusci/tasks/bulkdata/generate_mapping_utils/extract_mapping_file_generator.py
- cumulusci/tasks/bulkdata/generate_mapping_utils/generate_mapping_from_declarations.py
- cumulusci/tasks/bulkdata/generate_mapping_utils/tests/test_generate_extract_mapping_from_declarations.py
- cumulusci/tasks/sample_data/capture_sample_data.py
- cumulusci/tasks/sample_data/test_capture_sample_data.py
1. Tighten up the definition of "required field" and ensure it is consistent across the code base. (Field.requiredOnCreate)
2. Do not load sobjects which are also tooling objects. Tooling objects are generally loaded as metadata so loading them as data causes duplicate errors. The user can opt-in in their extract declaration if they want them.
3. Do not load sobjects which are known to cause problems unless the user opts-in. So far there are six such items.
4. Previously I had forgotten to respect the situation where a user supplied an extract declaration as an option. Fixed now.
> Datasets fixes

- cumulusci/conftest.py
- cumulusci/core/tests/test_datasets_e2e.py
- cumulusci/salesforce_api/org_schema.py
- cumulusci/salesforce_api/org_schema_models.py
- cumulusci/tasks/bulkdata/extract_dataset_utils/tests/test_synthesize_extract_declarations.py
- cumulusci/tasks/bulkdata/tests/integration_test_utils.py
- cumulusci/tasks/bulkdata/tests/test_generatemapping.py
- cumulusci/utils/tests/test_org_schema.py
Previously the org schema was versioned as a unified whole. Not one sobject at a time. This worked until I added the feature of allowing one to download a subset of the schema. Now some objects might be refreshed on Monday, some on Tuesday, a different set on Wednesday etc. To allow this, all objects are independently versioned (with a last_modified_date) now. If it is needed by the application it is refreshed and if it isn't, it isn't.
This bug was hidden because of the ways we were using `get_org_schema` before we added `capture_sample_data`. Now we really need the schema to be complete and up-to-date.
Tasks that use `get_org_schema` include `load_data` (for the Recently Used checking) and `generate_mapping`.
> Refresh all objects in org schema cache

- cumulusci/tasks/metadeploy.py
We have evidence that product translations are being published for products that don't have slugs.
Per David Glick, "a product should have at least one slug and if it’s None, something isn’t set up correctly."
If translations are published while the Product is in this weird state, you get weird translations:
```python
>>> Translation.objects.filter(context__startswith="None").first().context
'None:product'
>>> Translation.objects.filter(context__startswith="None").count()
184
>>> set(c.context for c in Translation.objects.filter(context__startswith="None"))
{'None:plan:ra_einstein_template', 'None:plan:install', 'None:steps', 'None:checks', 'None:product'}
```
We believe this to be the source of web interfaces that are mistranslated.
This code is intended to prevent all of that.
> Ensure that products have a slug before publishing translations

- .github/release.yml
We think the wildcard is clobbering the last entry.
> Re-order release notes config

- pyproject.toml
If not included the sdist will not be installable, and will fail with:
```
hatch_fancy_pypi_readme.exceptions.ConfigurationError:
["Fragment file 'README.md' not found.", "Fragment file 'docs/history.md' not found."]
```
> Include readme fragments in source distribution 

- .github/release.yml
I'm pretty sure this changed silently, but this is the [documented] way to
do it.
[documented]: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configurations
> Exclude label from release notes generator

- pyproject.toml
Snowfakery depends on some of CumulusCI's pytest plugins for integration
tests. This adds about 175 kB to the size of the wheel.
> Force inclusion of pytest plugins in wheels

- cumulusci/oauth/client.py
Apparently this triggered a security scan. Replaces the string with 'x'
and removes a character to fool the regex.
> Mask invalid oauth token

- pyproject.toml
Removing tests from the wheel broke the `cci project init` command.
There may be other hidden dependencies and the tradeoffs in playing
whack-a-mole with issues caused by hidden dependencies on test code have
outweighed the savings in bandwidth and artifact size.
> Include nearly everything in the wheel

- docs/get-started.md
Homebrew users periodically experience `bad interpreter` errors after an upgrade. This PR documents the fix for users.
See also: pypa/pipx#886
> Add Homebrew python upgrade error workaround to docs

- docs/contributing.md
- pyproject.toml
Declare the `use_real_env` marker and make some small fixes to the docs.
> Declare use real env marker

- cumulusci/core/datasets.py
- cumulusci/core/tests/test_datasets_e2e.py
- cumulusci/salesforce_api/filterable_objects.py
- cumulusci/tasks/bulkdata/generate_mapping_utils/dependency_map.py
- cumulusci/tasks/bulkdata/generate_mapping_utils/generate_mapping_from_declarations.py
- cumulusci/tasks/bulkdata/generate_mapping_utils/load_mapping_file_generator.py
- cumulusci/tasks/bulkdata/generate_mapping_utils/tests/test_generate_load_mapping_from_declarations.py
- cumulusci/tasks/bulkdata/mapping_parser.py
- cumulusci/tasks/sample_data/capture_sample_data.py
- cumulusci/tasks/sample_data/test_capture_sample_data.py
- docs/data.md
- docs/data/loading_rules.md
CumulusCI has a feature called a ".[load.yml](https://cumulusci.readthedocs.io/en/stable/data.html#controlling-the-loading-process)" file which is used when generating mapping files in the context of loading Snowfakery recipes. This allows you to, for example, control the API used, change the load order, etc. Basically it allows you to override default loading behaviours.
Our new `capture_sample_data` task also generates mapping files, and therefore could benefit from the same kinds of overrides. It was always anticipated that the `load.yml` would also be relevant in this context, but it was not implemented until now.
This was a problem when an internal team needed to change the load order of two objects. Now users can do that.
> The `capture_sample_data` task now looks for a `datasetname.load.yml` file to influence how it generates its .mapping file

- cumulusci/core/config/project_config.py
- cumulusci/core/runtime.py
- cumulusci/core/utils.py
"tasks" directories for sub-projects were added but not for the "main project" directory.
Now they are.
All of the opt-in, opt-out tests should ensure that I have not changed the strictness of the opt-in code execution feature.
If a project used a directory not called "tasks", it should not have been affected by this regression.
Metecho and MetaDeploy should pick up this code through their use of `BaseCumulusCI` .
Should open another PR with a test that would have caught the regression, but I'll get to that Monday.
> Ensure that top-level 'tasks' directory is read for custom tasks

- cumulusci/tasks/github/merge.py
- cumulusci/tasks/github/tests/test_merge.py
Fixes #3594
As written, skip_future_releases is always `True` for
`skip_future_releases: False` or `skip_future_releases: false` because
those get converted to booleans before being passed to
`process_bool_arg`. This was working as designed when run through the
CLI because the option doesn't go through the Pydantic model so it's a
`str`.
> Fix skip_future_releases option

- AUTHORS.rst
- cumulusci/tasks/github/merge.py
- cumulusci/tasks/github/tests/test_merge.py
Adds a new option `create_pull_request_on_conflict` for tasks using `cumulusci.tasks.github.MergeBranch`, i.e. `github_automerge_main` and `github_automerge_feature`. The default value for this option is True. Setting the option to False will prevent pull requests from being created when automerging encounters a merge conflict.
> Add create_pull_request_on_conflict option to automerge tasks

- cumulusci/tasks/create_package_version.py
This PR fixes an issue where the creation of a beta version of an unlocked package was failing during the `create_package_version` task with a misleading error message about a 1GP dependency.
The workaround is to match the behavior of the [@salesforce/packaging](https://github.com/forcedotcom/packaging/tree/830d45bd52b80b09b7a5f96b9664961eee3ce7f1) typescript library: when the package type is 'unlocked', 'None' is passed instead of the package name. 
Fixes #3633
> fix: Don't pass fullName for Unlocked packages

- cumulusci/tasks/vlocity/tests/test_vlocity.py
- cumulusci/tasks/vlocity/vlocity.py
We discovered that using sf.accessToken for persistent orgs is not
compatible with the local compilation of omniscripts, which requires
this workaround. Moreover, vlocity_build does not support passing the
NPM auth token via CLI or environment variable, so we're adding support
for this to the vlocity_pack_deploy task.
> Add workarounds to support Vlocity local comp in CI

- cumulusci/tasks/apex/testrunner.py
- cumulusci/tasks/apex/tests/test_apex_tasks.py
Changes made for 'run_tests' task:
`run_tests` accepts an optional list of test suites to run.
If provided, `run_tests` enqueues only those tests found in the given suites.
> W-12214520: Adding ApexTestSuite support in run_tests

- cumulusci/core/tasks.py
- cumulusci/core/tests/test_tasks.py
[W-14176826](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001bC27HYAS/view)
Implemented functionality to support variable replacement in nested structures in the `cumulusci.yml` file such as:
```
task:
deploy:
options:
path: $project_config.project__package__path
transforms:
- transform: find_replace
options:
patterns:
- find: foo
replace: $project_config.project__package__namespace
``` 
Here both variables are substituted by the appropriate value. Previously only the `path` would've been substituted
> Implemented variable substitution for nested structures in cumulusci.yml

- cumulusci/core/source_transforms/tests/test_transforms.py
- cumulusci/core/source_transforms/transforms.py
- docs/deploy.md
[W-12189179](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001GgiPYYAZ/view)
- Added `find_and_replace` via xpath along with find under transforms to find and replace items in xml files. 
- Added additional functionality to ensure that 'find' does not mess with the tags in the xml file and only replaces the content of the tags.
> Added xpath 'find_and_replace' functionality to transforms

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/activate_flow.py
- cumulusci/tasks/salesforce/tests/test_activate_flow.py
> Added deactivate_flows_task

- docs/cli.md
[W-14157597](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001asUQrYAM/view)
Fixed broken links in [documentation](https://cumulusci.readthedocs.io/en/stable/cli.html#access-and-manage-orgs)
**Line:** To learn about working with orgs in detail, read (scratch-orgs) and (connected-orgs).
> Fix broken links in documentation

- .github/workflows/feature_test.yml
- cumulusci/cli/tests/test_plan.py
- cumulusci/core/keychain/tests/test_encrypted_file_project_keychain.py
- cumulusci/oauth/client.py
- cumulusci/oauth/tests/test_client.py
- cumulusci/tasks/bulkdata/tests/test_step.py
- cumulusci/tasks/release_notes/tests/test_task.py
- cumulusci/tasks/salesforce/tests/test_PackageUpload.py
- cumulusci/tests/test_main.py
- cumulusci/utils/tests/test_logging.py
- pyproject.toml
Changes needed to get 3.12 working:
`ssl.wrap_socket()` has been discouraged since Python 3.2, deprecated since 3.7, and finally removed in 3.12. In this PR, the `ssl.wrap_socket` function has been removed and replaced with the recommended approach using `ssl.SSLContext`.  Previously, `ssl.wrap_socket` internally set up the SSL context, including loading certificates. Now, we're doing that explicitly with `ssl.SSLContext`. This is a substantive, but low-risk, change.
On the testing side, the previous workaround for suppressing the `CERTIFICATE_VERIFY_FAILED` error has been adapted to utilize the context creation method.
`called_once` and `called_once_with` are [not valid assertions] on mock objects, meaning an instance of `mock.Mock` is returned. Because instances of `mock.Mock` evaluate …
> Support Python 3.12

- pyproject.toml
Pyright changed the default typechecking level from 'basic' to 'standard' in v1.1.339. We don't have time to fix these right now, so this commit explicitly declares our `typeCheckingMode` to 'basic' until we do.
Also, our pre-commit configuration for pyright needs to be improved. First, pyright can't see find our imports because pre-commit installs hooks in their own environments. We could:
1. Fix our local pre-commit hook so it uses the global environment,
2. Install our dependencies into the hook environment,
3. Ignore missing imports until we do (1) or (2).
This commit chooses (3).
Second, using a local hook for Pyright results in inconsistencies in the version used across different environments (local development vs CI). Although an official hook is not available, 'python-pyright' was …
> Update pyright configuration for 1.1.339

- cumulusci/core/sfdx.py
1. CLI team would like to not be missing all the CCI usage of the CLI when monitoring performance and making deprecation decisions
2. setting `SFDX_TOOL` makes it obvious which executions come from CCI.  Useful for debugging/adoption
> fix: re-enable telemetry, make CCI usage identifiable

- cumulusci/tasks/preflight/permsets.py
- cumulusci/tasks/preflight/tests/test_permset_preflights.py
[W-14910021](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001j2AULYA2/view)
Retrieved list of assigned permission sets are assigned for the `task.return_values` to ensure the preflight check conditions are checked properly
> updated return_values for task get_assigned_permission_sets

- cumulusci/tasks/salesforce/nonsourcetracking.py
- cumulusci/tasks/salesforce/tests/test_nonsourcetracking.py
Modified listing components of non source trackable metadata types using SOAP call `APILISTMETADATA`
SOAP call takes maximum 3 queries at a time and so used the existing the soap envelope which takes 1 metadata type at a time.
> ListComponents modified to SOAP call 

- .github/workflows/chores.yml
- .github/workflows/pre-release.yml
Fixes the :cla_missing: errors on bot-authored commits.
> Add a real email for bot commits

- cumulusci/tasks/bulkdata/load.py
Fixed `INVALID_CROSS_REFERENCE` error while inserting lookups and record types simultaneously. This error appeared after [PR: Polymorphic Lookup Data Extraction](https://github.com/SFDO-Tooling/CumulusCI/pull/3741). This error occurred due to mismatch in the order of fields between the step and query during generation of the json for the request.
> Fix for mismatch between fields

- cumulusci/tasks/bulkdata/query_transformers.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/test_query_db__joins_self_lookups.sql
[W-15182566](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001lVihqYAC/view)
These modifications address the error reported in [Slack Thread](https://salesforce-internal.slack.com/archives/C024R3K39R6/p1709223158710319)
**Error Reason:**
The old format of sql files use the `id` field to be of type `INTEGER`:
```
CREATE TABLE "accounts" (
id INTEGER NOT NULL, 
"Name" VARCHAR(255), 
"parent_id" VARCHAR(255), 
PRIMARY KEY (id)
);
INSERT INTO "accounts" VALUES(1,'Bluth','');
INSERT INTO "accounts" VALUES(2,'Funke-Bluth',1);
```
During handling of adding the outerjoins for lookups, when we specified the condition, we were concatenating a string with an integer:
```
def join_for_lookup(lookup):
key_field = lookup.get_lookup_key_field(self.model)
value_column = …
```
> Fix Id Not Specified on Update Call

- cumulusci/core/dependencies/dependencies.py
- cumulusci/core/dependencies/tests/test_dependencies.py
A new option, `collision_check`, was added to the `deploy` task. The new option wasn't added to `core/dependencies.py`, so attempting to deserialize resulted in a DependencyParseError in MetaDeploy.
> Fix dependency parsing errors caused by `collision_check` option

- cumulusci/oauth/salesforce.py
- cumulusci/oauth/tests/test_salesforce.py
Work item : [link](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001mHTY8YAO/view)
Setting the PROD_LOGIN_URL and SANDBOX_LOGIN_URL doesn't update them dynamically. This causing issue while calling the jwt_session for the test environment
> @W-15258380/ Updating the login URL's

- .github/workflows/feature_test.yml
Importing `lxml` in Python 3.8 now throws an `ImportError` on macOS:
```python-traceback
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 743, in import_plugin
__import__(importspec)
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
exec(co, module.__dict__)
File "/Users/runner/work/CumulusCI/CumulusCI/cumulusci/tests/pytest_plugins/pytest_sf_orgconnect.py", line 9, in <module>
from cumulusci.cli.org import org_remove, org_scratch, org_scratch_delete
File "/Users/runner/work/CumulusCI/CumulusCI/cumulusci/cli/org.py", line 12, in <module>
from cumulusci.core.config import OrgConfig, ScratchOrgConfig …
```
> Fix Python 3.8 unit tests on macOS

- pyproject.toml
Postpone SQLAlchemy 2.0 migration until we get the WI included in a future sprint.
> Temporarily pin SQLAlchemy

- .github/workflows/feature_test.yml
Needed until we update the shared workflow to run on pull requests
from forked repositories.
> Allow manually triggering lint workflow

- cumulusci/tasks/preflight/licenses.py
- cumulusci/tasks/preflight/tests/test_licenses.py
The PermissionSetLicenseKey have the naming format as `SalesforceCPQ.CPQStandardPerm` and the actual developer name is `SalesforceCPQ_CPQStandardPerm` and to avoid errors .
Replaced with the developername
> Updated the PermissionSetLicenseKey to DeveloperName

- cumulusci/cumulusci.yml
- cumulusci/tasks/salesforce/salesforce_files.py
- cumulusci/tasks/salesforce/sourcetracking.py
- cumulusci/tasks/salesforce/tests/test_salesforce_files.py
Files uploaded via the app launcher in the orgs are currently not included in the metadata listings.
To address this, the "display_files" task has been introduced to list these files efficiently. 
- This task gives the list of files in a tabular format querying the `ContentDocument`, fetching the fields Id, Filetype, and Filename, as filenames alone are not unique identifiers. 
- Upon uploading a new file, a fresh entry is generated in the `ContentDocument` entity, establishing it as the latest version in the `ContentVersion` entity. Subsequent uploads of new versions of already tracked documents are noted in the ContentVersion entity, without creating additional ContentDocument records. 
- Retrieving the latest version involves filtering the ContentVersion entity by setting IsLatest to …
>  @W-15946941: New task added to display files in the salesforce org 

- .github/workflows/chores.yml
- .github/workflows/feature_test.yml
- .github/workflows/pre-release.yml
- .github/workflows/release.yml
- .github/workflows/release_test.yml
- .github/workflows/slow_integration_tests.yml
We missed the [announcement]:
> Customers will then no longer be able to use multiple labels or target
> non-name labels on larger runners after the 17th of June.
[announcement]: https://github.blog/changelog/2024-05-16-new-dates-for-actions-larger-runner-multi-label-deprecation/
> fix: Use private runner names instead of labels

- cumulusci/cumulusci.yml
- cumulusci/tasks/bulkdata/mapping_parser.py
- cumulusci/tasks/bulkdata/tests/mapping_after.yml
- cumulusci/tasks/bulkdata/tests/mapping_v1.yml
- cumulusci/tasks/bulkdata/tests/person_accounts_minimal.yml
- cumulusci/tasks/bulkdata/tests/test_extract.py
- cumulusci/tasks/bulkdata/tests/test_load.py
- cumulusci/tasks/bulkdata/tests/test_mapping_parser.py
- cumulusci/tasks/preflight/dataset_load.py
- cumulusci/tasks/preflight/tests/test_dataset_load.py
- datasets/default/default.mapping.yml
To ensure field-level permissions and successful dataset load, there are several validations performed on the `mapping.yml` file. These validations check whether the fields and SObjects have the required permissions, and whether namespaces need to be injected, as well as handling case insensitivity for the `mapping.yml`. This functionality is already implemented in the function `validate_and_inject_mapping`.
However, there was a missing corner case where the function did not capture errors for required fields missing in the mapping.yml. This functionality has now been added, and the function is used for the preflight check.
> Update the validation for loading to check the required fields as well

- cumulusci/tasks/metadata_etl/tests/test_value_sets.py
- cumulusci/tasks/metadata_etl/value_sets.py
```
task: add_standard_value_set_entries
options:
api_names: CaseOrigin
entries:
- fullName: New Account
label: New Account
- fullName: Questionable Contact
label: Questionable Contact
ui_options:
name: Add values to Case Origin picklist
```
For the add_standard_value_set_entries task, we noticed that only the fullname and label keys were being considered when generating the XML file for deployment, while other keys were being ignored. We've implemented a fix to ensure that all provided keys are now included in the standard value entry XML file.
For example ,
If the entries were given like this , 
```
entries:
- fullName: testerunner
label: testrunner
groupingString: Scheduled
```     
Now, it generates an XML like this 
```
<standardValue>
<fullName>testerunner</fullName> …
```
> Include All Keys in standardValue XML for add_standard_value_set_entries Task from Entries Option with Backward Compatibility

- .readthedocs.yml
- Rename readthedocs.yml to .readthedocs.yml, 
- update to Ubuntu 22.04 and Python 3.12, 
- add uv setup and Sphinx build commands.
> Fix readthedocs configuration

- cumulusci/tasks/bulkdata/select_utils.py
- cumulusci/tasks/bulkdata/tests/test_step.py
[W-17357226](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000026IWp2YAG/view)
Changes:
- Modified the if clauses from `if threshold` to `if threshold is not None`
- Added tests for 0 threshold to ensure it does not select everything
> @W-17357226: Fix for issue where zero threshold defaulted to select

- cumulusci/tasks/bulkdata/select_utils.py
- cumulusci/tasks/bulkdata/tests/test_select_utils.py
Changes:
- Made a fix for issue where when there are no records in target org and threshold is 0, the records were not being inserted.
> @W-17412267: Fix for records not being inserted when threshold 0

- cumulusci/tasks/bulkdata/select_utils.py
- cumulusci/tasks/bulkdata/tests/cassettes/TestSelect.test_select_random_strategy.yaml
- cumulusci/tasks/bulkdata/tests/cassettes/TestSelect.test_select_similarity_strategy.yaml
- cumulusci/tasks/bulkdata/tests/cassettes/TestSelect.test_select_standard_strategy.yaml
- cumulusci/tasks/bulkdata/tests/test_select_utils.py
- docs/env-var-reference.md
Default records were not being selected earlier. This bug is now fixed.
> Remove default declaration for select rows query

- cumulusci/tasks/bulkdata/mapping_parser.py
- cumulusci/tasks/bulkdata/step.py
- cumulusci/tasks/bulkdata/tests/cassettes/TestSelect.test_select_similarity_select_and_insert_strategy.yaml
- cumulusci/tasks/bulkdata/tests/cassettes/TestSelect.test_select_similarity_select_and_insert_strategy_bulk.yaml
- cumulusci/tasks/bulkdata/tests/cassettes/TestSelect.test_select_similarity_strategy.yaml
[W-17621812](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002876WEYAY/view)
**Issue:**
- The `requote_uri` function did not handle the `%` character correctly when URL-encoding queries, leading to invalid query formats when passed to the Salesforce API. Specifically, it did not encode `%` as `%25`, causing issues in query string formatting. (Example and associated Error given in [W-17621812](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002876WEYAY/view) under point 1)
- The permission type check for `SELECT` operations was incorrectly defaulting to `createable`. As a result, fields were unnecessarily required to be `createable`, even though `SELECT` operations only require them to be `queryable`.
**Changes:**  
- Updated the …
> @W-17621812: Update _get_required_permission_types to handle SELECT operations

- cumulusci/cli/checks.py
- cumulusci/cli/tests/test_checks.py
- docs/cli.md
Hey @jkasturi-sf 
Added the functionality for Running Preflight checks along with documentation
> Added Preflight checks functionality

- cumulusci/tasks/preflight/licenses.py
- cumulusci/tasks/preflight/tests/test_licenses.py
The get_available_permission_set_licenses task returns unavailable permset licenses because removed PSLs are still returned by SOQL. This commit adds a filter for Status to prevent this.
> fix: Make get permset licenses return active only

- .github/workflows/release_test.yml
- .github/workflows/release_test_sfdx.yml
- cumulusci/cumulusci.yml
- cumulusci/tasks/preflight/licenses.py
- cumulusci/tasks/preflight/tests/test_licenses.py
Added new tasks to retrieve assignable licenses and permission sets:
- get_assignable_licenses: Retrieves a list of currently assignable license definition keys based on unused licenses.
- get_assignable_permission_sets: Retrieves a list of currently assignable Permission Sets based on unused associated user licenses.
> Add new tasks get_assignable_permission_sets and get_assignable_licenses

- cumulusci/tasks/salesforce/sourcetracking.py
- cumulusci/tasks/salesforce/tests/test_sourcetracking.py
Added output_dir option to specify a custom output directory for retrieved changes
Updated retrieve_components function to handle the output_dir parameter
Modified error handling to provide clearer messages when no results are found
Updated test cases to verify the output_dir functionality
> Add output_dir option to retrieve_changes task

- cumulusci/tasks/salesforce/sourcetracking.py
PR #3901 added the `--output-dir` option to the `retrieve_components`
task. When `output_dir` was `None`, it used the target (e.g. `force-app`) as
the value. The Salesforce CLI rejects using a package directory as
the output directory, so this caused an error reported in #3918.
This commit builds the sfdx args without `--output-dir` by default.
It appends `--output-dir <path>` only when `output_dir` is not
`None`. This lets the CLI select the default output dir when output_dir
is not given.
When output_dir is not set, files go to the package directory from the
manifest, as the CLI expects.
> fix: include --output-dir only when output_dir is provided
