build/cumulusci.xml

This simply allows CumulusCI to traverse the aura folder in src and add the bundles to package.xml.

Add AuraBundleDefinition types to buildPackageXmlFromDir

---

build/cumulusci.xml

This way SharingReason won't be stripped from package.xml

Added SharingReason subtype

---

build/cumulusci.xml
cli/cumulusci.py
cli/metadata/metadata_map.yml
cli/metadata/package.py
requirements.txt

Provide a new way of generating package.xml and destructiveChanges.xml.  This new generator is optional.  To enable it, set the CUMULUSCI_CLI environment variable to True.  The CLI now uses the python generator for `cumulusci dev update_package_xml` and has some new options.

Python based package.xml and destructiveChanges.xml 

---

cli/release_notes/generator.py

add new release notes sections when updating existing release notes

---

cli/release_notes/parser.py

sort list of issue numbers for release notes

---

cli/release_notes/provider.py
cli/release_notes/release_notes.py
cli/release_notes/tests/test_provider.py

* If no last production tags exists, gather release notes from all pull requests before the current tag
Fixes #151

if no last tag exists, include all pull requests before current tag

---

cli/release_notes/provider.py

added missing import

---

cli/release_notes/parser.py
cli/release_notes/tests/test_parser.py

strip whitespace at end of string only

---

build/build.xml
build/cumulusci.xml

pass through sessionId, serverURL, and apiVersion in all sf: ant calls

---

cumulusci/tasks/salesforce.py
cumulusci/tests/test_tasks.py

Added new class BaseSalesforceToolingApiTask

added BaseSalesforceToolingApiTask

---

cumulusci/__init__.py
cumulusci/newcli/cli.py

honestly no clue if this is pythonic at all, but I needed it to keep track of my venvs, eep.

add a command to print current version

---

cumulusci/newcli/cli.py

this could probably be extended a bit to do some of what BaseSalesforceAPITask does... but it's a useful start

add a command to drop into the shell

---

cumulusci/core/exceptions.py
cumulusci/cumulusci.yml
cumulusci/tasks/mrbelvedere.py

update dependencies on mrbelvedere installer

---

cumulusci/core/config.py
cumulusci/core/exceptions.py
cumulusci/cumulusci.yml
cumulusci/tasks/apextestsdb.py

added task to upload apex test results to apextestsdb

---

cumulusci/core/config.py

fixed use of in_remote_origin

---

cli/release_notes/parser.py
cli/release_notes/tests/test_generator.py

decode pull request notes as unicode

---

cumulusci/core/config.py

Specify username in sfdx calls

---

cumulusci/core/config.py
cumulusci/core/exceptions.py
cumulusci/tasks/salesforce.py
cumulusci/tasks/tests/test_salesforce.py

Use new DebugLevel objects for Apex test debug logs

---

HISTORY.rst
cumulusci/__init__.py
cumulusci/newcli/cli.py
cumulusci/salesforce_api/metadata.py
cumulusci/tasks/salesforce.py
setup.cfg
setup.py

retry deploy for certain failures

---

cumulusci/utils.py

add findRename

---

cumulusci/tasks/salesforce.py

fix uninstall_post task

---

cumulusci/salesforce_api/metadata.py

Escape special XML characters in package name

---

cumulusci/salesforce_api/metadata.py

remove only spaces before XML tags

---

cumulusci/core/tasks.py
cumulusci/tasks/salesforce.py

Retry polling test status

---

cumulusci/tasks/salesforce.py

skip specified metadata types when building destructiveChanges.xml

---

cumulusci/tasks/release_notes/parser.py

- Merge level 2 header sections across pull requests when generating release notes

[release notes] parse level 2 header sections and merge across pull requests

---

cumulusci/tasks/release_notes/exceptions.py
cumulusci/tasks/release_notes/provider.py
cumulusci/tasks/release_notes/tests/util_github_api.py

[release notes] check for annotated tag

---

cumulusci/tasks/salesforce.py

support purge_on_delete option in update_dependencies task

---

cumulusci/tasks/metadata/package.py

handle unicode in package.xml generation

---

cumulusci/core/config.py
cumulusci/core/utils.py

Fix search for repo root on Windows

---

cumulusci/tasks/salesforce.py

pass purge_on_delete option to API class in UninstallPackage

---

cumulusci/tasks/push/push_api.py
cumulusci/tasks/push/tasks.py

Push API enhancements

---

cumulusci/tasks/push/push_api.py

handle DUPLICATE_VALUE when adding orgs to push request

---

cumulusci/tasks/push/push_api.py

Fixes issues introduced with original implementation of retries

Retry batch instead of entire push

---

cumulusci/tasks/push/push_api.py
cumulusci/tasks/push/tasks.py

report push status if start time is less than 1 minute in the future

---

cumulusci/salesforce_api/metadata.py
cumulusci/tasks/push/tasks.py

fix push request status Cancelled --> Canceled

---

cumulusci/cumulusci.yml
cumulusci/tasks/util.py

New task to list metadata types in project

---

cumulusci/tasks/push/tasks.py

Fix datetime namespace issues

---

cci.spec
cci_rth.py

Import project-level modules with run-time hook

---

cumulusci/salesforce_api/metadata.py
cumulusci/salesforce_api/soap_envelopes.py
cumulusci/tasks/salesforce.py

Provide asOfVersion to listMetadata calls

---

cumulusci/core/config.py
cumulusci/tasks/github.py
cumulusci/tasks/release_notes/tests/test_provider.py
cumulusci/tasks/release_notes/tests/util_github_api.py
cumulusci/tasks/salesforce.py

Use UTC for all times

---

cumulusci/tasks/salesforce.py

force metadata types into list

---

cumulusci/core/tasks.py
cumulusci/tasks/salesforce.py

* BaseTask now has _poll() method which polls something in a loop until it is complete. Includes ability to change polling interval per iteration.

Reusable _poll logic in BaseTask

---

cumulusci/salesforce_api/metadata.py
cumulusci/salesforce_api/package_zip.py
cumulusci/salesforce_api/soap_envelopes.py
cumulusci/tasks/salesforce.py

Remove hard-coded API versions

---

cumulusci/core/exceptions.py
cumulusci/tasks/command.py

New exception for browser tests

---

cumulusci/tasks/salesforce.py

Fix JUnit for Apex test results

---

cumulusci/cumulusci.yml
cumulusci/tasks/metaxml.py
requirements.txt

2 new tasks: meta_xml_apiversion, meta_xml_dependencies

Port updateMetaXml from CCI 1.0

---

app.json

Use Heroku CI to run nosetests for CumulusCI

---

app.json
requirements_dev.txt

Switch to using nose-tap for outputting TAP from nosetests for Heroku CI

---

cumulusci/tasks/metaxml.py

use project dependencies for updating XML

---

cumulusci/core/config.py

added force:open:display (used to be :describe)
updated JSON response parsing

Updates for DX Beta

---

cumulusci/core/tasks.py

add org-related tags only when org config is populated

---

cumulusci/tasks/metaxml.py

check dependency contents before appending

---

cumulusci/core/utils.py
cumulusci/tasks/release_notes/exceptions.py
cumulusci/tasks/release_notes/generator.py
cumulusci/tasks/release_notes/parser.py
cumulusci/tasks/release_notes/task.py

Check if repo has issues enabled before adding github issues parser

---

cumulusci/tasks/apex/testrunner.py

@cpolcyn - easy review.
closes #376

don't try to escape None strings

---

cumulusci/core/config.py

May help in resolving https://github.com/SalesforceFoundation/mrbelvedereci/issues/40

log stderr from scratch org info command

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

NOTE: Do not merge this PR until #402 is merged first.

Configure for 2.0.0-beta57

---

cumulusci/tasks/release_notes/task.py

Fix import path for BaseGithubTask

---

cumulusci/core/keychain.py
cumulusci/core/tests/test_flows.py
cumulusci/core/tests/test_keychain.py

Check the commit status from coveralls.io for details :)

100% coverage for core/keychain.py

---

cumulusci/tasks/metadata/manual_instructions.py
cumulusci/tasks/metadata/package.py

closes #428 
same as #423 
no build currently broken on this, so no rush for a cci rev.

whitelist __b

---

cumulusci/tasks/release_notes/parser.py

handle release notes section with only h2 content

---

cumulusci/cumulusci.yml

Renamed branch from https://github.com/SalesforceFoundation/CumulusCI/pull/434

add pull request parsers for New Metadata and Deleted Metadata

---

cumulusci/tasks/github/merge.py
cumulusci/tasks/github/tests/test_merge.py

Check PR head branch before skipping

---

cumulusci/cli/cli.py

closes #349 "check if running latest version"

check for the latest version

---

cumulusci/cli/cli.py

adds a timeout, still will try every time.
would love to merge this and then add a ticket to move the cache write higher up so that it doesn't retry always

add a requests timeout

---

cumulusci/core/exceptions.py
cumulusci/tasks/push/tasks.py

define PushApiObjectNotFound exception

---

cumulusci/tasks/push/tasks.py

Okay really it's 5 seconds from now… but sometimes I don't want to wait 5 minutes!

Add option for push task to start now

---

docs/tutorial.rst

Continuation of https://github.com/SalesforceFoundation/CumulusCI/pull/492

Add Windows sections to tutorial

---

cumulusci/tasks/metadata/metadata_map.yml

Add support for featureParameter* metadata types

---

cumulusci/tasks/salesforce.py

BaseUninstallMetadata was using this option but wasn't set up yet.

add purge_on_delete option to BaseUninstallMetadata

---

cumulusci/cli/cli.py

add option to print org info as json

---

cumulusci/utils.py

pass on unicode decode failures during tokenization

---

cumulusci/utils.py

fix variable name in util method

---

cumulusci/utils.py

Only run meta.xml file cleaning on classes/* and triggers/* directory

---

cumulusci/tasks/metadata/package.py

Skip CODEOWNERS file in package xml generation

---

cumulusci/tasks/command.py

External contribution: https://github.com/SalesforceFoundation/CumulusCI/pull/587

Pipe stderr in base command

---

cumulusci/tasks/command.py

External contribution: https://github.com/SalesforceFoundation/CumulusCI/pull/588

Clean up command task arg "pass_env"

---

docs/tutorial.rst

better isolate from changes to homebrew's python

Change installation instructions for macOS to use pyenv-virtualenv to

---

cumulusci/tasks/command.py
docs/tasks.rst

Sorry, I don't have an active way to update the PR in question. But this incorporates the change requested in the PR to master.

Switch interactive task feature name from use_std to interactive.

---

cumulusci/tasks/command.py
docs/tasks.rst

Contribution by @topherlandry 
https://github.com/SalesforceFoundation/CumulusCI/pull/595

Interactive command task

---

cumulusci/core/utils.py
cumulusci/cumulusci.yml
cumulusci/tasks/github/__init__.py
cumulusci/tasks/github/release_report.py

`cci task info github_release_report`

add task to report info from GitHub release notes

---

.gitignore
cumulusci/core/flows.py
cumulusci/core/tasks.py

Enhances BaseFlow to be more easily subclassed/overridden/observed. We now keep a reference to the flow step_num in the task.
adds three hook methods for subclasses:
- `pre_task`
- `post_task`
- `post_task_exception`

BaseFlow enhancements

---

appveyor.yml
cumulusci/core/keychain.py
cumulusci/core/tests/__init__.py
cumulusci/core/tests/test_config.py
cumulusci/core/tests/test_flows.py
cumulusci/core/tests/test_keychain.py
cumulusci/core/tests/test_tasks.py
cumulusci/core/tests/utils.py
cumulusci/oauth/tests/test_salesforce.py
cumulusci/tests/util.py

Fixes for Windows

---

cumulusci/cli/cci.py
cumulusci/core/config.py
cumulusci/core/keychain.py

Fixes #522 
Also fixes an issue with specifying some org aliases during org creation.

Support disabling password creation for scratch orgs

---

cumulusci/core/config/ScratchOrgConfig.py

use sfdx org password if present

---

cumulusci/cli/cci.py

Implements https://github.com/SalesforceFoundation/CumulusCI/issues/435
Added in error messaging similar to running a flow without a specified or default org.
Brought the oauth refresh error handling that existed in `org_info` into `org_browser` where it didn't exist.

Allowed default org to be used in cci org info and cci org browser.

---

cumulusci/core/tasks.py
cumulusci/robotframework/CumulusCI.py
cumulusci/tasks/robotframework/robotframework.py

cumulusci.core.tasks.CURRENT_TASK which gets set to self from inside a
BaseTask subclass during __init__ and __call__

Switch from a robot listener to the new global python var

---

cumulusci/core/config/BaseProjectConfig.py
cumulusci/core/github.py
cumulusci/core/tests/test_github.py
cumulusci/tasks/github/base.py
cumulusci/tasks/release_notes/tests/test_generator.py
cumulusci/tasks/release_notes/tests/test_parser.py
cumulusci/tasks/release_notes/tests/test_provider.py

Configure github client to retry requests

---

HISTORY.rst

Hopefully fixes rendering on PyPI

Fix rST lint errors

---

cumulusci/salesforce_api/package_zip.py

Fixes #695. Tested locally to confirm that it lets me deploy when I couldn't before the change.

Send required activateRSS field for InstalledPackage

---

cumulusci/cli/cci.py

The goal here is to avoid import-time side effects in the cci.py module,
as a first step toward working on test coverage for it. Initializing the config
and checking the CCI version now happens within the main click entry point
rather than at module import time.

Pass the CCI config to commands via the click context's obj

---

cumulusci/tests/test_utils.py
cumulusci/utils.py

Remove packageVersion from VF and Aura

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py

the CLI was doing stuff that the project_config can already do: get_task, list_flows, get_flow.
i thought this branch had something wrong with it, but then when I went to check it out today all my tests were passing...soo.... I'm gonna say ready for review?

rely on the project_config for more

---

cumulusci/tasks/metadata/metadata_map.yml

(see https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_settings.htm)

Settings md type is plural

---

cumulusci/robotframework/Salesforce.py
cumulusci/robotframework/tests/salesforce/create_contact.robot
cumulusci/robotframework/tests/salesforce/ui.robot

Per https://developer.salesforce.com/blogs/2018/01/heres-need-know-new-url-format-lightning.html

Change to new LEX url paths

---

cumulusci/core/config/BaseProjectConfig.py
cumulusci/core/tasks.py
cumulusci/core/tests/test_config.py
cumulusci/core/tests/test_config_expensive.py
cumulusci/cumulusci.yml
cumulusci/tasks/apex/anon.py
cumulusci/tasks/apex/tests/test_apex_tasks.py
cumulusci/utils.py
docs/tasks.rst

We should be able to replace the similar tasks in SAL and Cumulus with this.
**lurch: attach W-018728

 Add file support to AnonymousApexTask

---

cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/UpdateAdminProfile.py

and set tab visibility to DefaultOn

Set app visibility in update_admin_profile

---

cumulusci/oauth/exceptions.py
cumulusci/oauth/salesforce.py
cumulusci/oauth/tests/test_salesforce.py

(and clean up handling of oauth errors a bit)

Coverage for cumulusci.oauth

---

cumulusci/tests/test_utils.py
cumulusci/utils.py

Fix issue where -meta.xml files with non-ascii characters were not deployed

---

cumulusci/tasks/salesforce/CreatePackage.py
cumulusci/tasks/salesforce/Deploy.py
cumulusci/tasks/salesforce/PackageUpload.py
cumulusci/tasks/salesforce/tests/__init__.py
cumulusci/tasks/salesforce/tests/test_CreatePackage.py
cumulusci/tasks/salesforce/tests/test_Deploy.py
cumulusci/tasks/salesforce/tests/test_DeployBundles.py
cumulusci/tasks/salesforce/tests/test_InstallPackageVersion.py
cumulusci/tasks/salesforce/tests/test_PackageUpload.py
cumulusci/tasks/salesforce/tests/test_UpdateAdminProfile.py
cumulusci/tasks/salesforce/tests/util.py

I started factoring some of the repeated test setup into SalesforceTaskTestCase so I'm curious how you think that looks.

Coverage for some salesforce tasks

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py
cumulusci/core/config/BaseProjectConfig.py
cumulusci/tasks/salesforce/BaseRetrieveMetadata.py
cumulusci/tasks/salesforce/UpdateDependencies.py
cumulusci/tasks/salesforce/tests/test_UpdateAdminProfile.py
cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
cumulusci/tasks/salesforce/tests/test_base_tasks.py

Coverage for the rest of cumulusci.tasks.salesforce

---

cumulusci/cli/config.py
cumulusci/cli/tests/test_config.py
cumulusci/core/tests/test_tasks.py
cumulusci/tasks/github/commit.py
cumulusci/tasks/github/merge.py
cumulusci/tasks/github/tag.py
cumulusci/tasks/github/tests/test_commit.py
cumulusci/tasks/github/tests/test_merge.py
cumulusci/tasks/github/tests/test_pull_request.py
cumulusci/tasks/github/tests/test_release.py
cumulusci/tasks/github/tests/test_release_report.py
cumulusci/tasks/github/tests/test_tag.py
cumulusci/tasks/github/tests/test_util.py
cumulusci/tasks/github/util.py
cumulusci/tasks/release_notes/parser.py
cumulusci/tasks/release_notes/tests/test_generator.py
cumulusci/tasks/release_notes/tests/test_parser.py
cumulusci/tasks/release_notes/tests/test_provider.py
cumulusci/tasks/release_notes/tests/test_task.py
cumulusci/tasks/release_notes/tests/util_github_api.py
cumulusci/tasks/sfdx.py
cumulusci/tasks/tests/test_sfdx.py
cumulusci/tests/test_utils.py
cumulusci/utils.py

Also temporarily removes SFDXJsonPollingTask and SFDXDeploy which were untested and broken.

Coverage for cumulusci.tasks.github and a few other modules

---

cumulusci/utils.py

Fix logging

---

cumulusci/cli/cci.py

* Include task/flow name in alert when complete

Include task/flow name in alert

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py

* Skip beta releases when checking for a newer cumulusci version

Skip prereleases and postreleases in version check

---

cumulusci/cli/cci.py

Avoid using is_prerelease to check version since it's missing in old setuptools

---

.circleci/config.yml

Stop ignoring robot test failures (but try to report coverage anyway)

---

HISTORY.rst
cumulusci/__init__.py
cumulusci/cli/tests/test_cci.py
setup.cfg
setup.py

Prepare 2.1.0b1

---

requirements_dev.txt

I needed this in order to build the release.

Add wheel to dev requirements

---

.circleci/config.yml
requirements_dev.txt

Now we can include black in requirements_dev.txt

---

cumulusci/tasks/salesforce/UpdateDependencies.py

* Add a `dependencies` option to the `update_dependencies` task to override the project dependencies.

Add an UpdateDependencies option for which dependencies to install

---

docs/tutorial.rst

Update Windows install directions from @Auchtor's input

---

HISTORY.rst
cumulusci/__init__.py
cumulusci/robotframework/utils.py
setup.cfg
setup.py

Prepare 2.1.0

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.1.1b1

---

cumulusci/tasks/bulkdata.py

* Fixed bulkdata load task in Python 2.
#827

Fix URI concatenation in py2 (urljoin doesn't like mixed text/bytes)

---

cumulusci/robotframework/Salesforce.py
cumulusci/robotframework/locators.py
cumulusci/robotframework/tests/salesforce/ui.robot

* robot keyword fixes and improvements:
- ``Wait Until Loading Is Complete`` now waits for particular parts of the page to render
- ``Populate Lookup Field`` now tries several times in case there's an indexing delay
- new ``Click Header Field Link`` keyword

robot keyword fixes and improvements

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.1.1

---

cumulusci/tasks/bulkdata.py
cumulusci/tasks/tests/test_bulkdata.py

* Fixed the bulkdata query task.

Unquote csv headers from query results

---

cumulusci/tasks/robotframework/robotframework.py

Fix issue with parsing CLI options in robot task such as vars

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.1.2

---

cumulusci/robotframework/Salesforce.py
cumulusci/robotframework/tests/salesforce/ui.robot

* Robot Framework: The "Populate Field" keyword now clears an existing value using keystrokes to make sure that change events are fired.

Try clearing input using keystrokes

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.2.0

---

cumulusci/core/config/BaseProjectConfig.py
cumulusci/core/tests/test_config.py

* Oops, an update in CumulusCI 2.2.0 ended up breaking the update_dependencies task! Now fixed.

Update BaseProjConf to use github3.repo.{file,directory}_contents

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.2.1

---

cumulusci/core/config/ScratchOrgConfig.py
cumulusci/core/tests/test_config_expensive.py
cumulusci/robotframework/Salesforce.robot

Capture stderr from scratch org creation

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.2.2

---

cumulusci/core/config/ScratchOrgConfig.py

Better explanation of SFDX misreporting scratch org creation error as success

---

cumulusci/core/keychain/EncryptedFileProjectKeychain.py

* Improved the error message when trying to use a service that hasn't been configured yet.

Better error message for missing service config

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.2.3

---

cumulusci/tasks/github/commit.py
cumulusci/tasks/github/tests/test_util.py
cumulusci/tasks/github/util.py

Refactor CommitDir to work with latest `github3.py`.
Fixes #902

Refactor CommitDir

---

cumulusci/tasks/salesforce/Deploy.py

* Metadata deploy task: Log the size of the payload.

log size of mdapi deploy payload

---

cumulusci/robotframework/Salesforce.robot
cumulusci/robotframework/locators.py

Also adjust the locator for related item links to use text instead of title.

Add Robot Framework location strategies to locate elements by text or title

---

HISTORY.rst
cumulusci/__init__.py
requirements.txt
requirements_dev.txt
setup.cfg
setup.py

Prepare 2.2.4

---

cumulusci/robotframework/Salesforce.py

Robot Framework:
* Fix issue where "Get Current Record Id" could accidentally match the object name instead of the record Id.
* Fix issue where "Load Related List" would fail to scroll down to the list.
* Fix issue where errors deleting records during test teardown would cause a hidden test failure.

Fix a couple Robot keyword bugs

---

cumulusci/__init__.py
setup.cfg
setup.py

See if a dev version help MetaCI pick up the changes

---

cumulusci/core/flows.py
cumulusci/core/tests/test_flows.py

* Fixed an issue where overriding a flow step to set flow: None did not work.

Fix overriding a flow to None

---

cumulusci/__init__.py
setup.cfg
setup.py

update dev version

---

cumulusci/__init__.py
cumulusci/robotframework/Salesforce.py
setup.cfg
setup.py

urllib3 wraps the ConnectionResetError as ProtocolError

Fix retry on dropped connection while opening webdriver

---

cumulusci/__init__.py
setup.cfg
setup.py

bump dev version so pip will update

---

cumulusci/robotframework/CumulusCI.py
cumulusci/robotframework/Salesforce.py

* Robot Framework: Try several times to connect to remote webdriver if browser is slow to start.

We're waiting for the browser to start, not for the org

---

cumulusci/__init__.py
setup.cfg
setup.py

bump dev version

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.2.6

---

utility/push-homebrew.py

link to PR as html, not API

---

cumulusci/__init__.py
cumulusci/core/config/BaseProjectConfig.py
cumulusci/core/tests/test_config.py
cumulusci/tasks/github/release.py
cumulusci/tasks/github/tests/test_release.py
cumulusci/tasks/release_notes/generator.py
cumulusci/tasks/release_notes/tests/test_generator.py
cumulusci/tasks/release_notes/tests/utils.py
setup.cfg
setup.py

 Get latest (non-beta) github release with a single request

---

cumulusci/robotframework/Salesforce.py

Handle urlencoded slash before record id

---

cumulusci/tasks/salesforce/UpdateDependencies.py
setup.py

Avoid binding download helpers as instance methods

---

cumulusci/__init__.py
setup.cfg
setup.py

This seems to make a difference in Python3.7

fix setup.py in python3.7

---

cumulusci/cumulusci.yml

This already exists for a couple of our products and should probably be here.

Add dev_org_beta_deps flow

---

cumulusci/tasks/push/pushfails.py

for push failure report, fetch org info in chunks to avoid URI too long error

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

prepare 2.3.0b1

---

cumulusci/utils.py

Be explicit about opening files as utf-8
#962

Be explicit about our expected file encoding in findReplace

---

HISTORY.rst

fix reST formatting

---

cumulusci/core/config/BaseProjectConfig.py
cumulusci/core/tests/test_config.py
cumulusci/tasks/metadeploy.py
cumulusci/tasks/salesforce/DeployBundles.py
cumulusci/tasks/salesforce/UpdateDependencies.py
cumulusci/tasks/salesforce/tests/test_DeployBundles.py
cumulusci/tasks/salesforce/tests/test_UpdateAdminProfile.py
cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py
cumulusci/tasks/tests/test_metadeploy.py

Test coverage for the metadeploy publish task

---

docs/why_cumulusci.rst

#CHANGES 
Fix some minor typos.
Please tell me if I did anything that doesn't fit your processes.

Fix three typos.

---

docs/why_cumulusci.rst

The tutorial says it is linking to a small file but the file has changed over the years so that it is no longer small. I changed it to link to a historical version of the file. Immutability FTW!

Better example of a small file.

---

cumulusci/robotframework/CumulusCI.py
cumulusci/robotframework/Salesforce.py
cumulusci/robotframework/utils.py

Make flake8 happy.
Allows other checkins that would be blocked waiting for this.

Minor Flake8 fixes.

---

cumulusci/tasks/robotframework/robotframework.py

1. Better error messaging for missing org in robot task
2. Make Flake8 happy.

Better error messaging for missing org in robot task

---

cumulusci/cli/cci.py
cumulusci/core/flowrunner.py
cumulusci/core/tasks.py
cumulusci/core/utils.py

Remove unused imports and use "is not None" syntax for None-checking.

Make flake8 happy.

---

Makefile
cumulusci/cli/cci.py
cumulusci/cli/config.py
cumulusci/tests/test_utils.py
cumulusci/utils.py

@davisagli Should we attempt to detect whether cci has been installed via `brew` to display the appropriate upgrade command?

Update version upgrade message to include brew

---

cumulusci/tasks/metadeploy.py

This should make metadeploy publish work again once https://github.com/SFDO-Tooling/metadeploy/pull/223 is deployed.

Update metadeploy publish to match recent server-side changes

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

prepare 2.3.1

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.3.2

---

utility/build-homebrew.sh

TODO: Update the script to use [`python-brewer`] and default to wheels wherever possible.
[`python-brewer`]: https://github.com/thanethomson/python-brewer

Update brew formula generation shell script to pass `brew audit`

---

.circleci/config.yml

Turns out we're already using a CircleCI image that includes firefox.

Run Salesforce library UI tests in Firefox too

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 2.3.3

---

docs/robot/Keywords.html

checked in the new keyword documentation file

add the new keyword documentation file

---

cumulusci/core/config/BaseProjectConfig.py
cumulusci/core/tests/test_config.py
cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/InstallPackageVersion.py

This still needs a test but I wanted to check that it's what we want at a high level.

Add flow to install previous release and then upgrade

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

prepare v2.3.4

---

utility/build-homebrew.sh

Make sure build-homebrew script is installing the right version

---

cumulusci/cumulusci.yml

Add description for robot_testdoc

---

HISTORY.rst
cumulusci/__init__.py
docs/tasks.rst
setup.cfg
setup.py

Prepare 2.4.0

---

utility/build-homebrew.sh

Disable pip cache when installing to produce homebrew recipe

---

cumulusci/tasks/connectedapp.py
cumulusci/tasks/tests/test_connectedapp.py

sfdx is now pretty-printing JSON output which means that it's not all on one line.

Fix connectedapp task

---

cumulusci/tests/test_utils.py
cumulusci/utils.py
docs/tutorial.rst

This pull request adds simplified installation instructions for Windows 10
using `pipx`. This utility automates the creation of a virtualenv, the
installation of `cumulusci`'s dependencies, and linking the `cci.exe`
executable in a known location on the user's PATH.

Support installation via pipx

---

HISTORY.rst
cumulusci/__init__.py
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.4.2

---

HISTORY.rst
cumulusci/__init__.py
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.4.3

---

cumulusci/salesforce_api/metadata.py

* If CumulusCI gets a connection error while trying to call the Salesforce Metadata API, it will now retry several times before giving up.

Retry failed MDAPI connections before giving up

---

cumulusci.yml
orgs/prerelease.json

Add prerelease scratch org

---

cumulusci/tasks/push/push_api.py
docs/tutorial.rst

Flake8 found a bug in the version_number function.
While I fixed that I cleaned up a couple more of its complaints.
Also I changed a very small grammar mistake in a doc.

Minor fixes : May 2019

---

cumulusci/cli/cci.py
docs/features.rst

Update extension menu to change HEDA to EDA

---

docs/features.rst

Add docs for source tracking

---

HISTORY.rst
cumulusci/__init__.py
docs/features.rst
docs/tasks.rst
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.4.4

---

.circleci/config.yml
tox.ini

Fix installation on CircleCI with old pip

---

HISTORY.rst
cumulusci/__init__.py
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.5.0

---

HISTORY.rst
cumulusci/__init__.py
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.5.1

---

cumulusci/cli/cci.py

- Fix wrong help text for `cci flow list`
- Display OS alert even if task or flow failed

Fixes for tiny issues that came up in our team chat

---

cumulusci/tasks/metadata/package.py
cumulusci/tasks/metadata/tests/test_package.py

Translate filename namespace tokens when generating package.xml

---

cumulusci/cli/cci.py

Don't check for updates when outputting JSON

---

cumulusci/salesforce_api/metadata.py

Turn mdapi response processing errors into a MetadataParseError with attached response

---

HISTORY.rst
cumulusci/__init__.py
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.5.2

---

HISTORY.rst
cumulusci/__init__.py
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.5.3

---

cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/tests/test_sourcetracking.py
docs/features.rst

I meant to do this when I made the additions to `cci project init` but it slipped by.

Update default API version

---

cumulusci/tasks/salesforce/sourcetracking.py
cumulusci/tasks/salesforce/tests/test_sourcetracking.py

- CCI's `snapshot_changes` and `list_changes` tasks handle instances where the last revision number of a component is `null`.

Add handling for null RevisionNum SourceMembers

---

.coveragerc
CONTRIBUTING.rst

Coverage checking did not work for me so I fixed it.
And I added documentation about how to do it.

Fix coverage checking and document how to do it.

---

HISTORY.rst
cumulusci/__init__.py
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.5.4

---

cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/CreateCommunity.py
cumulusci/tasks/salesforce/__init__.py
cumulusci/tasks/salesforce/tests/test_CreateCommunity.py
docs/tasks.rst

- Added the `CreateCommunity` task allowing for API-based Community creation.

Add Create Community task

---

cumulusci/tasks/metadata/metadata_map.yml

- We've added metadata support for AppMenu.

Add appMenu to metadata map

---

cumulusci/tasks/bulkdata.py
docs/tasks.rst

Here's my take on adjusting the reporting of unresolved dependencies to include a mention of which field creates the dependency.
I also ran `cci task doc` to update the task docs.

Mapping generator: Report which fields create a dependency

---

cumulusci/core/exceptions.py
cumulusci/core/tests/test_utils.py
cumulusci/core/utils.py
cumulusci/cumulusci.yml
cumulusci/tasks/bulkdata.py
cumulusci/tasks/tests/test_bulkdata.py
docs/tasks.rst

- Add task to generate a Bulk Data mapping file for a package.

Add Bulk Mapping Generator

---

cumulusci/salesforce_api/metadata.py

If so, let's include it in our MetadataApiError.
Also adjusted to avoid parsing the XML response multiple times.
- Made sure that an errorMessage returned from a metadata API deploy will be reported.

Metadata deploy responses can include an errorMessage

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py
cumulusci/core/flowrunner.py
cumulusci/core/tests/test_flowrunner.py
cumulusci/tasks/tests/test_metadeploy.py

new method: `FlowCoordinator.show_summary()` to display sub-flow task info for `cci flow info [flow_name]`

show_info displays step details for cci flow info

---

.gitignore
HISTORY.rst
cumulusci/__init__.py
docs/tutorial.rst
setup.cfg
setup.py

Prepare 2.5.5

---

HISTORY.rst
cumulusci/__init__.py
docs/install.rst
setup.cfg
setup.py

Prepare 2.5.6

---

cumulusci/cumulusci.yml

May need some wordsmithing.
* `clone_tag` task description is correct

Fix clone_tag description

---

HISTORY.rst
cumulusci/__init__.py
docs/install.rst
setup.cfg
setup.py
utility/build-homebrew.sh

Includes reverting the homebrew build script to the approach that works

Prepare 2.5.7

---

cumulusci/tasks/bulkdata/base_generate_data_task.py
cumulusci/tasks/bulkdata/extract.py
cumulusci/tasks/bulkdata/tests/test_base_generate_data_tasks.py
cumulusci/tasks/bulkdata/tests/test_utils.py
cumulusci/tasks/bulkdata/utils.py

A different PR will pull in the FactoryBoy stuff.

Refactor reusable code and add BaseBatchDataTask

---

HISTORY.rst
cumulusci/__init__.py
docs/install.rst
setup.cfg
setup.py

Prepare 2.5.8

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py
cumulusci/core/config/ScratchOrgConfig.py

-- Adds a column to cci org list table to show myDomain URL and pod to quickly compare to browser URL

Add Domain column to cci org list

---

cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/ListCommunities.py
cumulusci/tasks/salesforce/__init__.py
cumulusci/tasks/salesforce/tests/test_ListCommunities.py
docs/tasks.rst

Added task to list communities in the current org.
[1212](https://github.com/SFDO-Tooling/CumulusCI/issues/1212)

Add List Communities Task

---

cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/ListCommunityTemplates.py
cumulusci/tasks/salesforce/__init__.py
cumulusci/tasks/salesforce/tests/test_ListCommunityTemplates.py
docs/tasks.rst

Added task to list community templates.
[1211](https://github.com/SFDO-Tooling/CumulusCI/issues/1211)

Add List Community Templates Task

---

.circleci/config.yml
.gitignore
cumulusci/robotframework/CumulusCI.py
cumulusci/robotframework/Salesforce.py
cumulusci/robotframework/tests/salesforce/api.robot
cumulusci/robotframework/tests/salesforce/perf/collection_perf.robot
cumulusci/robotframework/tests/test_utils.py
cumulusci/robotframework/utils.py
cumulusci/tasks/robotframework/robotframework.py
cumulusci/tasks/robotframework/robotperflistener.py
cumulusci/tasks/robotframework/tests/test_robotframework.py
cumulusci/tasks/robotframework/tests/test_robotperflistener.py
docs/robot/Keywords.html

Add a new performance listener.
Add new custom metrics keywords.
Tests will be added before merging.

Performance listener and Robot keywords

---

cumulusci/cli/cci.py

Creating orgs now generates feedback.

Give feedback on org setup.

---

cumulusci/cli/ui.py

Hopefully we can remove this real soon.

Avoid unicode errors in py2

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare version 2.5.9

---

cumulusci/cumulusci.yml

* Need to add this task back ci_feature as step 0.5

add task back to ci_feature

---

cumulusci/__init__.py
setup.py

Bump version so we can test on MetaCI staging

---

cumulusci/tasks/apex/testrunner.py
cumulusci/tasks/apex/tests/test_apex_tasks.py

When there's 1 Apex test being processed, log its name

---

cumulusci/__init__.py
setup.cfg
setup.py

bump version so MetaCI will install it

---

cumulusci/cumulusci.yml

Update create_community group

---

cumulusci/tasks/bulkdata/factory_utils.py

"flush" is a good middle-ground between the unreasonable memory usage of buffer-in-memory and the unreasonable disk usage of auto-commit.

Performance improvement: DB flush

---

cumulusci/files/templates/project/cumulusci.yml

- Removed incorrect customization of `qa_org` flow in new project template.

Remove errant flow customization in template

---

cumulusci/__init__.py
cumulusci/conftest.py
cumulusci/core/tests/test_github.py
cumulusci/salesforce_api/tests/test_utils.py
cumulusci/salesforce_api/utils.py
setup.cfg
setup.py

- Added a retry mechanism to `get_simple_salesforce_connection`.

Retry simple-salesforce connections

---

.circleci/config.yml

* Draft pull request just to see how I can break things for now.

Windows Config for CircleCI

---

cumulusci/files/templates/project/scratch_def.json

It's JSON and can't have extra commas.

Fix scratch_def.json

---

cumulusci/core/config/ScratchOrgConfig.py

* Switchover to fstrings in ScratchOrgConfig.py

ScratchOrgConfig - fstrings

---

cumulusci/oauth/salesforce.py
cumulusci/oauth/tests/test_salesforce.py
docs/features.rst
docs/tutorial.rst

Nicer confirmation message after you collect an org on CCI.

More compassionate post-authentication message

---

README.rst

Remove pyup status on readme

---

README.rst

Also remove supported versions from readme, since it'll be harder to
keep up to date than just referencing PyPI.
----

Add more badges

---

.circleci/config.yml

CircleCI should ignore dependabot

---

cumulusci/__init__.py
cumulusci/core/flowrunner.py
setup.cfg
setup.py

(There's an edge case we're not handling yet involving checks from other projects, but I want to get a fix out quick.)
* Fixed a bug in processing preflight checks for MetaDeploy.

Make sure preflight check tasks get a valid project_config

---

cumulusci/tasks/bulkdata/tests/dummy_data_factory.py
cumulusci/tasks/bulkdata/tests/mapping_vanilla_sf.yml

Minor internal change to conform to emerging RelEng standards.

Use Salesforce names for everything per RFC

---

cumulusci/tasks/bulkdata/__init__.py
cumulusci/tasks/bulkdata/generate_mapping.py

1. Rename file. 
2. Slightly improve informative output.

1. Rename file. 2. Slightly improve informative output.

---

.dependabot/config.yml
requirements.txt
requirements_dev.txt

* I didn't include the pytest update because of the `# pyup: <5` note.

dependency updates

---

HISTORY.rst
cumulusci/__init__.py
docs/install.rst
setup.cfg
setup.py

Prepare 3.1.2

---

cumulusci/core/keychain/EncryptedFileProjectKeychain.py

fix fstring

---

cumulusci/tasks/apex/testrunner.py
cumulusci/tasks/apex/tests/test_apex_tasks.py

- A rare issue where CumulusCI could fail to load the symbol table for a failed Apex test class is now caught and reported.

Trap symbol table-related errors and report

---

.circleci/config.yml
cumulusci/cli/tests/test_ui.py

Update windows tests for CliTable

---

docs/bulk_data.rst

Use correct values in load_dataset example.

Fix load_dataset example.

---

docs/bulk_data.rst

Fix example to use correct option.

Fix example.

---

cumulusci/cli/config.py

* Store any keychain error and display to users.

store keychain exception

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py

Fix another stray .table

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 3.2.0

---

cumulusci/cumulusci.yml
cumulusci/tasks/metadata/modify.py
cumulusci/tasks/metadata/tests/test_modify.py

Expose RemoveElementsXPath to Command Line CCI users.

RemoveElementsXPath CLI

---

cumulusci/core/flowrunner.py

Fix bad classpath exception message

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py
cumulusci/tasks/metadata/modify.py
docs/cookbook.rst
docs/features.rst
docs/why_cumulusci.rst

Update references to NPSP repository

---

CONTRIBUTING.rst
cumulusci/cli/cci.py
pytest.ini
requirements_dev.txt

Enable type-guard.

---

cumulusci/core/tests/test_tasks.py
cumulusci/tasks/command.py

Fix some warnings

---

orgs/beta.json
orgs/dev.json
orgs/feature.json
orgs/prerelease.json
orgs/release.json

Switch to new org settings format

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 3.3.0

---

.circleci/config.yml
requirements.txt
requirements_dev.txt

Update Python dependencies

---

cumulusci/cli/cci.py
utility/build-homebrew.sh

- Be sure to build homebrew formula using Python 3.7
- Remove inaccurate message at end of `cci project init`

A couple small fixes:

---

.circleci/config.yml

Switch back to newer python for Windows build

---

cumulusci/__init__.py
setup.cfg
setup.py

Bump version to allow deployment to MetaCI.

Bump version: 3.3.0 → 3.3.1dev0

---

cumulusci/tasks/bulkdata/tests/test_generate_and_load.py
cumulusci/tasks/bulkdata/tests/tests/test_generate_from_snowfakery_task.py

This gets to 100% coverage for the new or changed modules:

Get to 100% test coverage

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 3.4.0

---

cumulusci/tasks/salesforce/tests/test_UpdateAdminProfile.py

Don't create destination directory in UpdateAdminProfile deployment test

---

cumulusci/tasks/bulkdata/load.py
cumulusci/tasks/bulkdata/tests/test_bulkdata.py

Make the task_mode ("Serial" or "Parallel") case-insensitive. Also I fixed a small bug in one of your tests.

Make the options case-insensitive.

---

HISTORY.rst

Prepare 3.5.1

---

cumulusci/cli/logger.py
cumulusci/cli/tests/test_logger.py
cumulusci/tasks/command.py

* Set `RotatingFileHandler`'s encoding to `'utf-8'` -- fixes #1480

Set FileHandler's encoding to 'utf-8'

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py

Add new features for running Python code (in a file or string) without bringing up an interactive shell. `--python` and `--script` arguments to `cci shell` and `cci org shell`
$ cci org shell --python "print(sf.query('select Count(Id) from Opportunity'))"
$ cci org shell --script foo.py
$ cci  shell --python "print(config.get_org('dev'))"
$ cci shell --script foo.py
I'm not sure if I need to document this somewhere else or whether the `--help` is the documentation.

New features to run the Python code from CCI command line.

---

requirements.txt
requirements_dev.txt

Week 5 Dependency Updates

---

cumulusci/tasks/apex/testrunner.py

Clarify documentation for RunApexTests task.

Clarify documentation.

---

docs/cookbook.rst

This document requires more updates, but this is a quick fix for an old
reference found via grep.
----

Update cookbook.rst with new variable names for UpdateAdminProfile

---

.circleci/config.yml
cumulusci/core/sfdx.py
cumulusci/core/tests/test_sfdx.py

Fix windows sfdx shell quoting

---

cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/insert_record.py
cumulusci/tasks/salesforce/tests/test_insert_record.py
docs/tasks.rst

New task to insert any Salesforce Record: insert_record

Insert Record task

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py

Fix `gist error info` command
W-7228368

Fix gist error info: W-7228368

---

cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/sourcetracking.py
cumulusci/tasks/salesforce/tests/test_insert_record.py
cumulusci/tasks/salesforce/tests/test_org_settings.py

Update to use API 48.0 by default

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Prepare 3.7.0

---

HISTORY.rst
cumulusci/__init__.py
setup.cfg
setup.py

Release notes for 3.8.0

---

cumulusci/tasks/bulkdata/load.py
cumulusci/tasks/bulkdata/tests/test_load.py

Add back the bulk_mode mapping file feature.

Allow mapping file override of bulk_mode

---

.dependabot/config.yml
requirements.txt
requirements_dev.txt

week 10 dependency updates

---

cumulusci/tasks/bulkdata/tests/mapping-oid.yml
cumulusci/tasks/bulkdata/tests/test_load.py
cumulusci/utils/yaml/model_parser.py
cumulusci/utils/yaml/tests/test_model_parser.py

Fix the bug David Reed identified in integration testing.
Replace the weird behaviour of Pydantic models.

Fix a bug in copying models and add tests

---

cumulusci/tasks/salesforce/tests/test_ProfileGrantAllAccess.py

This PR fixes a unit test that fails only on Windows.

Fix line ending problem on Windows

---

cumulusci/core/config/project_config.py
cumulusci/core/tests/test_config.py
cumulusci/tasks/github/tests/test_release.py
cumulusci/tasks/salesforce/activate_flow.py
cumulusci/tests/util.py
cumulusci/utils/yaml/cumulusci_yml.py

* Show a more helpful error message if CumulusCI can't find a project's repository or release on GitHub.

Improve handling when repo or release are not found

---

cumulusci/core/flowrunner.py

Clarify logging message for optional steps.

Invert log message

---

cumulusci/cli/cci.py

On master:
```$  cci --help
Usage: cci [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
error    If you'd like to dig into an error more yourself, you can get
the...
flow     Commands for finding and running flows for a project
org      Commands for connecting and interacting with Salesforce orgs
project  Commands for interacting with project repository configurations
service  Commands for connecting services to the keychain
shell    Drop into a Python shell
task     Commands for finding and running tasks for a project
version  Print the current version of CumulusCI
```
On this branch:
```
$  cci --help
Usage: cci [OPTIONS] COMMAND [ARGS]...
Options:
--help  Show this message and exit.
Commands:
error    Get or share information about an error
flow …
```

Improve error help.

---

cumulusci/tasks/datadictionary.py

I may have broken it with my refactoring a few weeks ago.

Fix a bug in data_dictionary_generator.py

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py

* Log stacktraces to the temporary logfile

Log stacktraces to temporary logfile

---

utility/build-homebrew.sh

CCI users can now invoke Snowfakery just by issuing the command "snowfakery" from their command line.

Install Snowfakery CLI endpoint alongside CCI's.

---

cumulusci/utils/logging.py
cumulusci/utils/tests/test_logging.py

* Fixed issue where logfile was not being read in 'utf-8' format on Windows. (closes #1619)

Fix encoding issues when reading files in windows

---

requirements.txt

Upgrade Snowfakery to 0.8.1 in order to get RecordTypes support.

Upgrade Snowfakery

---

cumulusci/core/tests/test_salesforce.py
requirements.txt
requirements_dev.txt

2020 week 19 dependency updates

---

cumulusci/cli/runtime.py

Add a missing quote inside an English string.

Fix a typo

---

requirements.txt
requirements_dev.txt

Week 22 dependency updates

---

requirements.txt

Faker was installed transitively but not pinned.
#1773

add missing requirement pin

---

cumulusci/core/config/project_config.py
cumulusci/core/github.py
cumulusci/tasks/datadictionary.py
cumulusci/tasks/github/base.py
cumulusci/tasks/tests/test_datadictionary.py
docs/tasks.rst

- The `generate_data_dictionary` task now has more features for complex projects. By default, the task will walk through all project dependencies and include them in the generated data dictionaries. Other non-dependency projects can be included with the `additional_dependencies` option. The output format has been extensively improved.

Enhance Data Dictionary Generation

---

cumulusci/tasks/bulkdata/extract.py
cumulusci/tasks/bulkdata/load.py
cumulusci/tasks/bulkdata/mapping_parser.py
cumulusci/tasks/bulkdata/tests/test_extract.py
cumulusci/tasks/bulkdata/tests/test_load.py

Fix some bugs discovered in integration testing of Data manipulation features.

Data manipulation fixes

---

CONTRIBUTING.rst

update CumulusCI release docs

---

cumulusci/core/flowrunner.py

Add a success message for flow completion and slight code cleanup.

Add success message for flow

---

cumulusci/tasks/tests/test_datadictionary.py

Avoid generating files in repo during pytest.

Test data dictionary in tempdir

---

cumulusci/salesforce_api/metadata.py
cumulusci/salesforce_api/tests/test_metadata.py
cumulusci/tasks/salesforce/UpdateDependencies.py
cumulusci/tasks/salesforce/tests/test_UpdateDependencies.py

Improve error messaging and add assertions to dependency management features.

Better error messaging for dependency management

---

cumulusci/cli/tests/test_cci.py
cumulusci/core/tests/test_config_expensive.py
cumulusci/core/tests/test_salesforce.py

Fix a bug where $HOME was leaking beyond a single test case.

Improve sandboxing in test classes that make pervasive use of tempdirs.

---

cumulusci/tasks/bulkdata/generate_from_yaml.py
requirements.txt
requirements_dev.txt

week 25 dependency updates

---

requirements.txt

week 26 dependency update

---

cumulusci/tasks/metadata/metadata_map.yml

fix capitalization of customHelpMenuSections in metadata map

---

requirements.txt
requirements_dev.txt

week 27 dependency updates

---

docs/features.rst

fix gist command in docs

---

.github/workflows/release_test.yml
orgs/prerelease.json
requirements.txt
requirements_dev.txt

week 29 dependency updates

---

cumulusci/tasks/salesforce/DeployBundles.py
docs/tasks.rst

Make sure DeployBundles doesn't mutate the description of the Deploy task's path option

---

requirements.txt
requirements_dev.txt

- Installing CumulusCI on macOS 10.9 (Mavericks) is no longer supported due to a change in one of our dependencies.

week 31 dependency updates

---

.github/dependabot.yml
requirements.txt
requirements_dev.txt

Week 32 dependency updates

---

docs/index.rst
docs/metadata_etl.rst

This PR is dependent upon #1800 and #1884.
- Documentation is provided for CumulusCI's Metadata ETL framework.

Add docs for Metadata ETL

---

cumulusci/core/tasks.py
cumulusci/core/tests/test_tasks.py

- Task options can now use $project_config substitutions in any position, not just at the start of the value.

Support $project_config substitution in task options in any position

---

cumulusci/robotframework/Salesforce.py
cumulusci/robotframework/pageobjects/BasePageObjects.py
cumulusci/tasks/bulkdata/tests/test_generate_from_snowfakery_task.py
cumulusci/tasks/github/release_report.py
cumulusci/tasks/github/tests/test_release_report.py
cumulusci/tasks/metadata_etl/sharing.py
cumulusci/tasks/push/push_api.py
cumulusci/tasks/salesforce/Deploy.py
cumulusci/utils/yaml/model_parser.py

Removed all flake8 warnings except the following wanted your take on them @davisagli 
`./cumulusci/tasks/salesforce/tests/__init__.py:1:1: F401 '.util.create_task' imported but unused
./pybuild/lib/cumulusci/tasks/salesforce/tests/__init__.py:1:1: F401 '.util.create_task' imported but unused
./pybuild/lib/cumulusci/core/keychain/__init__.py:4:1: F401 'cumulusci.core.keychain.BaseProjectKeychain.BaseProjectKeychain' imported but unused
./pybuild/lib/cumulusci/core/keychain/__init__.py:5:1: F401 'cumulusci.core.keychain.BaseProjectKeychain.DEFAULT_CONNECTED_APP' imported but unused
./pybuild/lib/cumulusci/core/keychain/__init__.py:8:1: F401 'cumulusci.core.keychain.BaseEncryptedProjectKeychain.BaseEncryptedProjectKeychain' imported but unused …

Creating distinct pull request for flake8

---

CODE_OF_CONDUCT.md
SECURITY.md

Add SFDC community health files

---

requirements.txt
requirements_dev.txt

week 33 updates

---

.github/workflows/feature_test.yml

Re-enable the job to run robot tests in a prerelease org

---

cumulusci/tasks/github/publish.py
cumulusci/tasks/github/tests/test_publish.py

---
- We added a `ref` option to `github_copy_subtree` to allow publishing a git reference (commit hash, branch, or tag).

Allow publishing a subtree by git reference

---

cumulusci/tasks/bulkdata/extract.py
cumulusci/tasks/bulkdata/tests/test_extract.py

- We fixed an issue (#2001) that caused CumulusCI to extract invalid data sets when using `after:` steps with autoincrement primary keys.

Fix bug with after steps in autopk extracts

---

requirements.txt
requirements_dev.txt

Week 37 dependency updates

---

cumulusci/core/sfdx.py
cumulusci/core/tasks.py
cumulusci/core/utils.py

Just some f strings

---

requirements.txt
requirements_dev.txt

Week 38 dependency updates

---

cumulusci/files/templates/project/mapping.yml

Fix lookup reference to Account table

---

cumulusci/tasks/bulkdata/step.py
cumulusci/tasks/bulkdata/tests/test_step.py

- CumulusCI now correctly handles converting stored Booleans for REST API data loads (fixes #2032)

Fix  handling of stored Booleans for REST DML

---

docs/install.rst

Update install docs to current Python

---

docs/concepts.rst

Doc reorg: Key Concepts

---

cumulusci/tasks/bulkdata/mapping_parser.py

New error messaging for load_dataset.

Slightly better error message

---

requirements.txt

Snowfakery 1.1.2
Minor improvements in error reporting.
Update to Faker 4.1.3

Snowfakery 1.1.2

---

cumulusci/tasks/metadata/metadata_map.yml

- We added support for newer metadata components to the `update_package_xml` task.

Add metadata map components

---

cumulusci/cumulusci.yml

Use beta_dependencies for ci_feature_2gp

---

CONTRIBUTING.rst

* Added the topics to add to release announcement posts in the Power of Us Hub as a step in CCI releases.

Contributing tweak

---

cumulusci/cli/cci.py
docs/features.rst

Use correct option name in current docs

---

cumulusci/cumulusci.yml
cumulusci/salesforce_api/tests/test_package_install.py
cumulusci/tasks/github/tests/test_commit_status.py
cumulusci/tasks/package_2gp.py
cumulusci/tasks/preflight/tests/test_settings.py
cumulusci/tasks/salesforce/tests/test_create_permission_sets.py
cumulusci/tasks/salesforce/tests/test_insert_record.py
cumulusci/tasks/salesforce/tests/test_sourcetracking.py
cumulusci/tasks/tests/test_package_2gp.py
cumulusci/tests/cassettes/TestIntegrationInfrastructure.test_integration_tests.yaml

- The default API version for new projects has been updated to 50.0

Update default API version to 50.0

---

cumulusci/tasks/github/merge.py
cumulusci/tasks/github/tests/test_merge.py

* Handle exception when creating a merge conflict pull request.

handle merge conflict when create merge conflict PR

---

cumulusci/cli/cci.py
cumulusci/cli/tests/test_cci.py

@jofsky Your code is working well now, but I have a number of minor suggestions and thought it would be easiest to show in a pull request. I'll add comments to explain the changes on specific lines.

suggested changes for doc_task

---

cumulusci/cumulusci.yml
docs/flows.rst

Update description for config_managed

---

cumulusci/tasks/salesforce/update_dependencies.py

(to remove a tautological condition, fixes #2148)

flatten structure of UpdateDependencies._install_dependency

---

requirements.txt
requirements_dev.txt

Week 46 Dependency Updates

---

HISTORY.rst

Already uploaded to pypi. Will update the tag/release to point at master after merging this.

Add newline to HISTORY.rst

---

cumulusci/tasks/salesforce/users/permsets.py
cumulusci/tasks/salesforce/users/tests/test_permsets.py

Blacken permsets module

---

cumulusci/cli/cci.py
cumulusci/core/config/OrgConfig.py
cumulusci/core/github.py
cumulusci/core/tests/test_config.py
cumulusci/oauth/salesforce.py
cumulusci/tasks/apex/anon.py
cumulusci/tasks/apex/testrunner.py
cumulusci/tasks/metadeploy.py
cumulusci/utils/http/requests_utils.py

Clean up some instances where we assume that the platform will 100% of the time return JSON and never HTML error text or a proxy error or something like that.

Better JSON checks

---

cumulusci/tasks/datadictionary.py
docs/tasks.rst

- Fixed task documentation for `generate_data_dictionary` (closes #2169 )

Update task docs for data dictionary

---

.pre-commit-config.yaml

Have RST linter ignore docs dir

---

cumulusci/tests/pytest_plugins/pytest_typeguard.py
cumulusci/tests/test_utils.py
cumulusci/utils/__init__.py
docs/conf.py
docs/tasks.rst
pyproject.toml

* Include a link for each task so other sections can reference them.

Include a link for each task

---

cumulusci/tasks/bulkdata/tests/test_generate_from_snowfakery_task.py
requirements.txt

Use Snowfakery 1.3

---

cumulusci/cumulusci.yml
docs/tasks.rst

----
- Added preflight task to check that Enhanced Notes are enabled (`check_enhanced_notes_enabled`), intended for use with MetaDeploy install plans.

Add Enhanced Notes preflight

---

cumulusci/tasks/metadata_etl/value_sets.py

I don't think the task actually functions properly when either of the main parameters is missing.

Fix docs and requirements-specification for add_standard_value_set

---

cumulusci/cumulusci.yml
cumulusci/tasks/preflight/settings.py
cumulusci/tasks/preflight/tests/test_settings.py
docs/tasks.rst

- CumulusCI offers a `check_my_domain_active` preflight check to encapsulate the logic of checking for My Domain.

Add My Domain preflight check

---

.github/workflows/feature_test.yml

re-enable prerelease robot tests

---

docs/concepts.rst

New comprehensive edit of Key Concepts.

Feature/doc reorg  key concepts  justin

---

docs/concepts.rst

Reverts SFDO-Tooling/CumulusCI#2253

Revert "Feature/doc reorg  key concepts  justin"

---

.github/workflows/build_homebrew.yml
.github/workflows/feature_test.yml
.github/workflows/release.yml
.github/workflows/release_test.yml
CONTRIBUTING.rst
README.rst
cumulusci/tasks/github/tests/test_publish.py
utility/push-homebrew.py

Preparation for changing the default branch to main

Update automation to use main instead of master

---

docs/install.rst

* Update docs with new homebrew install command

fix homebrew install command

---

docs/concepts.rst

Justin's Comments on Key Concepts Section of the Docs

---

utility/build-homebrew.sh

I think that the script should stop if something fails rather than making a corrupt PR which needs to be deleted.
I admittedly do not know how to test this change and its possible that this script is supposed to tolerate some forms of harmless "failures", so please take the PR as suggestive. If it doesn't make sense we can reject it.

Stricter homebrew script.

---

CONTRIBUTING.rst

Update contributor docs to reduce chances of someone installing into their system Python

Show how to create a virtualenv for contributions

---

docs/cumulusci_flow.rst

Small tweak to be more precise about what this functionality actually does.

Improve Release Automerge Docs

---

docs/scratch_orgs.rst

Rendered: https://cumulusci.readthedocs.io/en/feature-doc-reorg__scratch-org/scratch_orgs.html
First draft of the Scratch Orgs section of CumulusCI docs.

Doc reorg: Scratch Orgs

---

cumulusci/tasks/metadata/metadata_map.yml

- We added support for Muting Permission Set components.

Add mutingpermissionset to metadata map

---

cumulusci/core/flowrunner.py

- add org's name to flow success message

#2389 Add org name to flow success

---

.github/workflows/feature_test.yml
.github/workflows/release_test.yml

Make sure we can easily check what version of sfdx was used for CI

Log sfdx plugin versions in CI

---

CONTRIBUTING.rst
requirements_dev.txt

Make random-order testing easy.
Do we need a 3PP for dev requirements?

Add pytest-random-order.

---

docs/index.rst
docs/metadata_etl.rst
docs/unpackaged.rst

Rendered:
https://cumulusci.readthedocs.io/en/feature-doc-reorg__unpackaged/unpackaged.html and https://cumulusci.readthedocs.io/en/feature-doc-reorg__unpackaged/metadata_etl.html

Doc Reorg: Unpackaged Metadata & Metadata ETL

---

docs/robot.rst
docs/robot_debugger.rst
docs/robot_tutorial.rst

Copy edits for Robot sections of new docs

---

cumulusci/tasks/robotframework/robotframework.py

`make docs` did not work on my computer so I hope this formats correctly.

Docs about robot_outputdir

---

.github/workflows/feature_test.yml
cumulusci/cumulusci.yml
cumulusci/tasks/preflight/licenses.py
cumulusci/tasks/preflight/tests/test_licenses.py

We added a new custom task that retrieves the list of available permission sets in the org. 
[W-8998476](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000008a58bIAA/view)

[W-8998476] Add preflight task to retrieve available permissions sets

---

cumulusci/tests/test_entry_points.py
setup.py

The `snowfakery` command is now available to CumulusCI users.

Entry point for snowfakery

---

cumulusci/utils/fileutils.py
requirements/dev.txt
requirements/prod.txt

Week 13 Dependency Updates

---

docs/data.rst

Oops. Looks better in github preview now.

Markdown syntax -> Restructured Text

---

cumulusci/cli/cci.py

Fix regression in project_dependencies command from my refactoring

---

.github/workflows/feature_test.yml

Re-enable Robot tests on Summer '21 preview org

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

Week 15 dep updates

---

.github/workflows/feature_test.yml
.github/workflows/release_test.yml
cumulusci/tasks/metadata/metadata_map.yml
docs/github_actions.rst

- Updated github actions to the new URL and process for installing sfdx (see https://github.com/forcedotcom/cli/blob/main/releasenotes/README.md#5171-april-8-2021---cli-7961)
- Added recent metadata types to metadata_map.yml
- The `update_package_xml` task now supports additional metadata types.

Updates for Summer '21

---

cumulusci/tasks/bulkdata/generate_from_yaml.py
cumulusci/tasks/bulkdata/tests/test_generate_from_snowfakery_task.py
requirements/prod.txt

Uses the new Snowfakery API instead of duplicating code from the Snowfakery CLI.
Todo: release Snowfakery 1.9 and update requirements.

Support for Snowfakery 1.9 API

---

cumulusci/core/dependencies/resolvers.py
cumulusci/core/dependencies/tests/test_resolvers.py

Fix regression on releases that do not have a namespace

---

.github/workflows/feature_test.yml

Temporary workaround for apparent issue with chromedriver 90 https://bugs.chromium.org/p/chromedriver/issues/detail?id=3782

Use chromedriver 89

---

cumulusci/tasks/salesforce/tests/test_update_dependencies.py
cumulusci/tasks/salesforce/update_dependencies.py

- The `update_dependencies` task now supports a `packages_only` option, which suppresses the installation of unpackaged metadata dependencies. This option is intended to support building update-only or idempotent installers.

Add option to update_dependencies to only install packages

---

cumulusci/tasks/bulkdata/load.py

Fix minor grammar error in load.py

Fix minor grammar error in load.py

---

cumulusci/salesforce_api/org_schema_models.py

Remove a warning from the new version of SQL Alchemy.

Correct warning

---

docs/2gp_testing.rst
docs/continuous_integration.rst
docs/dev.rst

* The CumulusCI docs have a new section: Testing with Second-Generation Packaging

Testing with Second-Generation Packaging

---

cumulusci/cumulusci.yml

Fix broken URL in connected_app description

---

MANIFEST.in

Running tox on a fresh install throws the following exception:
```python-traceback
Traceback (most recent call last):
File "/Users/jestevez/work/rel/CumulusCI/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
main()
File "/Users/jestevez/work/rel/CumulusCI/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/Users/jestevez/work/rel/CumulusCI/.tox/py38/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 114, in get_requires_for_build_wheel
return hook(config_settings)
File "/private/var/folders/0d/4xzp298554g29nnlsrzn_vqc0000gq/T/pip-build-env-qxs728id/overlay/lib/python3.8/site-packages/setuptools …
```

Add requirements directory to manifest

---

.github/workflows/feature_test.yml
.github/workflows/release_test.yml

We're past the period where there is an active preview release, so let's not try to test using it.

disable prerelease testing

---

cumulusci/tasks/bulkdata/snowfakery.py
cumulusci/tasks/bulkdata/tests/test_snowfakery.py
cumulusci/utils/parallel/task_worker_queues/parallel_worker.py
cumulusci/utils/parallel/task_worker_queues/parallel_worker_queue.py
cumulusci/utils/parallel/task_worker_queues/tests/test_parallel_worker.py
datasets/recipe.yml
requirements/prod.in

Add tests to increase coverage of Snowfakery to 100%.
Also remove dead code and a few other stylistic improvements:
* e.g. get_debug_mode() is captured just once as an instance attribute.
* dead code is removed in some places.
* a few assertion or warning branches are covered with pragmas.

Unit Tests for Multiprocessor Snowfakery

---

cumulusci/tasks/apex/anon.py

* Fixed a bug where two task options had text that were missing spaces.
* Refactored logic in `_run_task()` to two methods (`_process_apex_from_path()` & `_process_apex_string()`) to provide better readability
* Refactored to `fstrings` where applicable.
* Updated call to `super()` to use newest syntax

Refactor AnonymousApexTask

---

cumulusci/cumulusci.yml
cumulusci/salesforce_api/tests/test_package_install.py
cumulusci/tasks/create_package_version.py
cumulusci/tasks/github/commit_status.py
cumulusci/tasks/github/tests/test_commit_status.py
cumulusci/tasks/preflight/tests/test_settings.py
cumulusci/tasks/salesforce/tests/test_composite.py
cumulusci/tasks/salesforce/tests/test_create_permission_sets.py
cumulusci/tasks/salesforce/tests/test_insert_record.py
cumulusci/tasks/salesforce/tests/test_sourcetracking.py
cumulusci/tasks/salesforce/users/tests/test_permsets.py
cumulusci/tasks/tests/test_create_package_version.py
cumulusci/tasks/tests/test_promote_package_version.py
cumulusci/tests/cassettes/TestIntegrationInfrastructure.test_integration_tests.yaml

- We updated the default API version to 52.0.

Change default and pinned API versions to 52.0

---

cumulusci/tasks/salesforce/sourcetracking.py

- We fixed issues in working with files containing Unicode characters on some Windows systems when using source-tracking commands.

Specify encoding on all file operations in sourcetracking.py

---

HISTORY.rst

Fix HISTORY.rst typo

---

.github/workflows/release_test.yml

use a github app instead of a personal access token to make releases of CumulusCI-Test

---

cumulusci/cli/service.py
cumulusci/cli/tests/test_service.py

* CumulusCI will now display an informative message if a user attempts to remove a service defined via an environment variable.

Display message if user attempts to remove service defined in environment

---

docs/npsp_eda_2gp.rst

fix flow name in 2gp docs

---

cumulusci/cli/service.py

[CCI] Fixing service connect help typo

---

docs/managed_2gp.rst
docs/unlocked_package.rst

fix flow names in 2gp release docs

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

hold back keyring for now

---

cumulusci/tasks/metadata_etl/layouts.py

Fix typo in Add Fields to Layout task docs

---

cumulusci/cli/runtime.py

Suppress keyring's recommendation to install keyrings.alt on Linux

---

.pre-commit-config.yaml
.prettierrc.yml
cumulusci.yml
cumulusci/cumulusci.yml

- Formatting only; prettier is suggesting these changes

Fix formatting of cumulusci.yml

---

.github/workflows/feature_test.yml
.github/workflows/release_test.yml

We had temporarily been installing an older version of the salesforce-alm plugin due to a bug.

return to testing with latest sfdx

---

docs/continuous_integration.rst

Issue: I find this page easier to read if every major topic has a summary on the home page.
Resolution: Now they do.

More descriptive index page for this section

---

cumulusci/tests/pytest_plugins/pytest_sf_vcr.py

Changes to our integration test to record Content-Type more accurately.

Better header (esp. content-type) handling

---

cumulusci/tasks/marketing_cloud/deploy.py

- added `endpoint` task option to override the API endpoint for deploy_marketing_cloud_package
- handle new entity result status of REUSED
- Updated the `deploy_marketing_cloud_package` task for compatibility with the October 2021 release of Marketing Cloud.
- The `deploy_marketing_cloud_package` now has an option to override the Marketing Cloud package manager endpoint for testing.

adjustments to deploy_marketing_cloud_package task

---

README.rst

* Add the badge from coveralls to our repositories readme.

add coverage badge to readme

---

.github/workflows/feature_test.yml
docs/get_started.rst
requirements/prod.txt
setup.py
tox.ini

Test all supported versions and operating systems

---

cumulusci/tasks/bulkdata/generate_from_yaml.py
cumulusci/tasks/bulkdata/snowfakery.py
cumulusci/tasks/bulkdata/tests/snowfakery/unique_values.recipe.yml
cumulusci/tasks/bulkdata/tests/test_snowfakery.py
requirements/dev.txt
requirements/prod.in
requirements/prod.txt

[Snowfakery 2.2](https://github.com/SFDO-Tooling/Snowfakery/releases/tag/v2.2) is now included with CumulusCI. New features include unique IDs and Numeric Counters.

Snowfakery 2.2 support in CCI

---

docs/get_started.rst

Added a recommendation to click the "Disable path length limit" button when installing Python on Windows.

Update Windows install docs

---

cumulusci/tasks/bulkdata/step.py
cumulusci/tasks/marketing_cloud/api.py
cumulusci/tasks/metadata/modify.py
cumulusci/tasks/metadata_etl/tests/test_value_sets.py
cumulusci/tasks/metaxml.py
cumulusci/tests/test_utils.py
cumulusci/utils/__init__.py
cumulusci/utils/xml/__init__.py
cumulusci/utils/xml/metadata_tree.py
cumulusci/utils/xml/test/test_salesforce_encoding.py

Per the Python documentation, XXE is not a problem for the stdlib: 
https://docs.python.org/3/library/xml.html#xml-vulnerabilities
lxml does have an XXE problem:
https://lxml.de/FAQ.html#how-do-i-use-lxml-safely-as-a-web-service-endpoint

Centralize XML parsing and avoid XXE

---

cumulusci/utils/xml/__init__.py

Add some docs to suggest xml API usage

---

requirements/dev.txt
requirements/prod.txt

* The new version of `black` produces no new formatting changes.

Week 49 Dependency Updates

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

* Removed `contextvars` and `immutables` from dependencies.

Week 1 Updates

---

cumulusci/tasks/salesforce/__init__.py
cumulusci/tasks/salesforce/uninstall_packaged_incremental.py

! Nothing for release notes in this pull request !
* Updated filename to reflect current naming conventions.
* Added missing periods to task option descriptions.

TOTW Updates - `uninstall_packaged_incremental`

---

cumulusci/tasks/apex/testrunner.py

Good catch @davisagli . I usually add a #FIXME comment when I do this but I guess I must have forgotten this time or misinterpreted it when I removed it.

Remove debugging code that slipped in

---

requirements/dev.txt
requirements/prod.in
requirements/prod.txt

! Nothing for Release Notes !
* Pinned `selenium-robotframework` to `<6`. It requires `selenium>4`.
* Major update to `rich`. All looks nominal.

Week 3 Dependency Updates

---

cumulusci/tasks/bulkdata/tests/integration_test_utils.py
cumulusci/tasks/bulkdata/tests/test_snowfakery.py
cumulusci/tasks/bulkdata/tests/test_updates.py

Nothing for Release notes.
Should fix the TestUpdates integration test by ensuring that Accounts always exist so that they can be Updated.

Fix TestUpdates integration tests

---

cumulusci/cli/error.py
cumulusci/cli/tests/test_error.py

Update error command tests to avoid unnecessary mocks

---

.github/workflows/feature_test.yml

disable the prerelease robot build while prerelease orgs are not available

---

.github/workflows/feature_test.yml
.github/workflows/release_test.yml
cumulusci/cli/tests/test_service.py
cumulusci/tasks/bulkdata/tests/test_updates.py
cumulusci/tasks/robotframework/libdoc.py
cumulusci/tasks/robotframework/tests/test_robotframework.py
requirements/dev.in
requirements/dev.txt

Changes the command run on windows to fix a path issue. ) ~I thought we already had a 3PP for pytest-cov, but we don't so it's a draft for now~.

Fix windows path

---

requirements/prod.in
requirements/prod.txt

Snowfakery 3 Dependency

---

cumulusci/tasks/metadata/metadata_map.yml

Adds new metadata type maps for Slack.

Add slack metadata types

---

cumulusci/salesforce_api/tests/test_metadata.py
cumulusci/tasks/github/tests/test_release_report.py
cumulusci/tasks/release_notes/tests/test_generator.py
cumulusci/tasks/salesforce/composite.py

Reformat files to black 22.1.0
No relevance to release notes.

Black is the new black.

---

cumulusci/tasks/metadata_etl/layouts.py
cumulusci/tasks/metadata_etl/value_sets.py

Adds example usage for a couple of tasks.

Usage examples for task reference

---

cumulusci/core/tests/utils.py
cumulusci/salesforce_api/tests/test_metadata.py

A few more references to old-fashioned super() .

Clean up old-fashioned super() references

---

cumulusci/tasks/salesforce/EnsureRecordTypes.py

User noticed that a comment is incorrect.

Fix typo in comment

---

docs/conf.py

Don't log warnings during doc builds

---

docs/data.rst

Fix various RST errors

---

cumulusci/core/config/tests/test_config.py
cumulusci/core/dependencies/tests/test_resolvers.py
cumulusci/core/github.py
cumulusci/core/tests/test_github.py
cumulusci/core/tests/test_source.py
cumulusci/tasks/github/tests/util_github_api.py

Don't rely on github tag sorting to find latest release

---

requirements/dev.txt
requirements/prod.txt

A couple major updates including `cryptography`. I didn't note any breaking changes that were of concern.

Week 17 Dependency Updates

---

cumulusci/tasks/bulkdata/tests/test_load.py

More logical assertion

---

.gitignore
cumulusci.yml
cumulusci/tasks/bulkdata/load.py
cumulusci/tasks/bulkdata/mapping_parser.py
cumulusci/tasks/bulkdata/step.py
cumulusci/tasks/bulkdata/tests/snowfakery/upsert.recipe.yml
cumulusci/tasks/bulkdata/tests/snowfakery/upsert_2.recipe.yml
cumulusci/tasks/bulkdata/tests/snowfakery/upsert_before.yml
cumulusci/tasks/bulkdata/tests/test_load.py
cumulusci/tasks/bulkdata/tests/test_upsert.py
cumulusci/tasks/bulkdata/upsert_utils.py
datasets/upsert/upsert_before_data.sql
datasets/upsert/upsert_mapping_bulk.yml
datasets/upsert/upsert_mapping_bulk_complex.yml
datasets/upsert/upsert_smart__native_field.yml
datasets/upsert/upsert_smart__non_native_field.yml

This PR is dependent on #3184 . Please review that first.
_query_db has been totally refactored to use a sort of Strategy pattern.
This necessitated lots of test changes.
Snowfakery ETL is one of the participants in that pattern.
Snowfakery ETL tests were added.

Refactor loaddata and fix bugs in ETL Upsert

---

.github/workflows/update_dependencies.yml

Nothing for release notes
* This is to be merged after: https://github.com/SFDO-Tooling/.github/pull/4/files

Reference workflow in SFDO-Tooling/.github

---

cumulusci/tasks/metadeploy.py

This PR applies the following refactorings:
- 3.8: named expressions
- Use Pathlib
- Suppress or discard irrelevant tracebacks
- Extract function
- Comprehensions
to `metadeploy_publish`.

Refactor `metadeploy_publish` task

---

cumulusci/cli/plan.py
cumulusci/core/metadeploy/plans.py

Moves `get_frozen_steps` to a new `plans` module.

Create metadeploy.plans submodule

---

cumulusci/salesforce_api/org_schema.py
cumulusci/tasks/bulkdata/extract_dataset_utils/calculate_dependencies.py
cumulusci/tasks/bulkdata/extract_dataset_utils/extract_yml.py
cumulusci/tasks/bulkdata/extract_dataset_utils/hardcoded_default_declarations.py
cumulusci/tasks/bulkdata/extract_dataset_utils/synthesize_extract_declarations.py
cumulusci/tasks/bulkdata/extract_dataset_utils/tests/test_extract_yml.py
cumulusci/tasks/bulkdata/extract_dataset_utils/tests/test_synthesize_extract_declarations.py
cumulusci/utils/salesforce/count_sobjects.py
datasets/test.extract.yml
datasets/test_minimal.extract.yml

Add extract declarations concept to CumulusCI.
Documentation will be added later when we unveil to the public.

Add extract declarations concept to CumulusCI

---

cumulusci/core/config/project_config.py
cumulusci/core/config/tests/test_config.py
cumulusci/core/github.py
cumulusci/core/tests/test_github.py
cumulusci/tasks/salesforce/install_package_version.py
cumulusci/utils/git.py

Fix `install_package_version` task to not hardcode github.com, which helps with GitHub enterprise compatibility

Github Enterprise support task fix

---

.git-blame-ignore-revs

Add docs about how to use blame config

---

.git2gus/config.json

More details at the [bot docs](https://lwc-gus-bot.herokuapp.com/#getting-started).

Add Git2Gus configuration file

---

cumulusci/core/config/__init__.py
cumulusci/core/config/project_config.py
cumulusci/core/config/tests/test_config.py
cumulusci/core/github.py
cumulusci/core/tests/test_github.py
cumulusci/cumulusci.yml
cumulusci/tasks/salesforce/install_package_version.py
docs/get-started.md
docs/headless.md

Added claifying documentation around GES configuration

---

cumulusci/cli/logger.py

* Fixed a bug where requests were not being logged when using the `--debug` flag.

Fix Request Logging

---

cumulusci/core/tests/test_datasets_e2e.py

tmp_path would also probably work

Clean up test_datasets_e2e output

---

cumulusci/tests/shared_cassettes/GET_sobjects_Contact_describe.yaml

Make the YAML for our sample describe() output more human readable, diffable and updatable.
Not relevant for release notes.

Make contact yaml more human readable

---

Makefile

setup.py accepts multiple subcommands

---

cumulusci/core/keychain/encrypted_file_project_keychain.py
cumulusci/core/keychain/tests/test_encrypted_file_project_keychain.py

Put back in the O_TRUNC fix and ensure that it works.

Test that migration from pickle to JSON works

---

cumulusci/tasks/sample_data/test_capture_sample_data.py
cumulusci/utils/yaml/tests/test_cumulusci_yml.py

Make sure that our [tempfile is added](https://github.com/SFDO-Tooling/CumulusCI/compare/minor-test-fixes?expand=1#diff-b4ef8f68ef245e27a700111003e34a6e3cafb1ff5784fb2a98d91f664547132bR73) to a tempdirectory. 
Load another file by an [absolute path](https://github.com/SFDO-Tooling/CumulusCI/compare/minor-test-fixes?expand=1#diff-153724afa6d9e248b7c80fba036ef2882a3f567229fa89051cdf33d83f8c1d5eR31).

Fix two small test issues

---

cumulusci/robotframework/SalesforcePlaywright.py

We missed a major release of `robotframework-browser` ([v15]), which removed the deprecated `execute_javascript` keyword. This resulted in test failures that we initially believed were timeout related because the `AttributeError` was being caught by the bare `except` and re-raised with a misleading error message.
This commit resolves the failures by:
1. Switching to the `evaluate_javascript` keyword
2. Raising the timeout exception using the `raise ... from exc`
[v15]: https://github.com/MarketSquare/robotframework-browser/releases/tag/v15.0.0

Remove deprecated Playwright keywords

---

cumulusci/core/dependencies/resolvers.py
cumulusci/core/enums.py
cumulusci/core/sfdx.py
cumulusci/core/source_transforms/transforms.py
cumulusci/core/versions.py
cumulusci/salesforce_api/package_install.py
cumulusci/tasks/bulkdata/extract_dataset_utils/extract_yml.py
cumulusci/tasks/bulkdata/mapping_parser.py
cumulusci/tasks/bulkdata/step.py
cumulusci/tasks/bulkdata/tests/test_upsert.py
cumulusci/tasks/create_package_version.py
cumulusci/tasks/metadata_etl/base.py
cumulusci/tests/pytest_plugins/pytest_sf_vcr.py
cumulusci/utils/yaml/cumulusci_yml.py

Convert to use StrEnum for all string enums

---

docs/get-started.md

This brings our windows install steps up to parity with what [pipx currently recommends](https://pypa.github.io/pipx/installation/).

Update windows install steps

---

docs/cumulusci-flow.md

Correct indention of example github_automerge_feature

---

cumulusci/tasks/salesforce/package_upload.py
cumulusci/tasks/salesforce/tests/test_PackageUpload.py

Add exception handling for minor release version comparison when uploading packages

Add exception handling for minor release version comparison when uploading packages

---

cumulusci/tasks/bulkdata/load.py
cumulusci/tasks/bulkdata/query_transformers.py
cumulusci/tasks/bulkdata/utils.py
datasets/mapping.yml
datasets/sample.sql

Reverts SFDO-Tooling/CumulusCI#3731

Revert "Polymorphic Reference - Load (merging into another branch)"

---

cumulusci/tasks/bulkdata/mapping_parser.py
cumulusci/tasks/bulkdata/tests/test_mapping_parser.py

Suppress the required field check for the upsert action at mappingstep

Fix the required fields error for the Upsert action 

---

.readthedocs.yml
docs/reference.md

fix: restore task and flow reference docs
